### ISSUE TITLE
Byte order mark in navigation.js

### ISSUE THREAD

**Issue by jmathew** [grahammendick/navigation#104]
There's a UTF-8 byte order mark in navigation.js file. This causes an exception in Chrome unless you explicitly declare your HTML file to have a utf-8 charset 

`<meta http-equiv="content-type" content="text/html; charset=utf-8" />`

This is with version 3.0.0 off NPM.

And navigation.js is the only file at issue here because after removing the BOM from it everything works fine. 

![bom](https://cloud.githubusercontent.com/assets/1046234/20997858/53814c62-bcd7-11e6-8e4f-d0eb2fcecf90.png)

**Comment by grahammendick** [comment]
Hey, thanks for letting me know. Could you give me a few more details about how you encountered this problem, please? Is it source map related? Also, are you able to work around the problem for now?

**Comment by jmathew** [comment]
I don't think my build process is out of the ordinary I just included the navigation library as any npm package. 

```
npm install navigation
```

And I build with webpack. 
```
const path = require('path');

var src = path.resolve(__dirname, "./src");
var dest = path.resolve(__dirname, "./dest");
module.exports = {
    context: src,
    entry: {
        "application": ["./App.ts"],
    },
    resolve: {
        extensions: ['.ts', '.tsx', '.js', '.jsx', '.css']
    },
    output: {
        path: dest,
        filename: "[name].js",
        chunkFilename: "[name].js"
    },
    module: {
        loaders: [{
            test: /\.tsx?$/,
            include: src,
            loader: "ts-loader"
        }, {
            test: /\.css$/,
            include: src,
            loader: [
              'style-loader',
              'css-loader?modules&camelCase=dashes&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]',
              'typed-css-modules-loader?modules&camelCase=1',
            ].join('!')
        }, {
            test: /\.jpe?g$|\.gif$|\.png$|\.svg$|\.woff$|\.ttf$|\.wav$|\.mp3$/,
            loader: "file-loader"
        }]
    },
    externals: {
        jquery: 'jQuery'
    },
    devtool: "source-map"
};
```

I removed the byte order mark to solve the error. Unfortunately don't have time for a pull request but this is the difference between the original:
```
$ xxd navigation.js
00000000: efbb bf6d 6f64 756c 652e 6578 706f 7274  ...module.export
00000010: 7320 3d20 7265 7175 6972 6528 272e 2f6c  s = require('./l
00000020: 6962 2f4e 6176 6967 6174 696f 6e27 293b  ib/Navigation');
00000030: 0d0a
```

and the fixed version. Note the removal of 'efbbbf'
```
$ xxd navigation_fixed.js
00000000: 6d6f 6475 6c65 2e65 7870 6f72 7473 203d  module.exports =
00000010: 2072 6571 7569 7265 2827 2e2f 6c69 622f   require('./lib/
00000020: 4e61 7669 6761 7469 6f6e 2729 3b0d 0a    Navigation');..
```

I removed it by opening the file in vim, `:set nobomb`, and saving.

**Comment by grahammendick** [comment]
Thanks for getting back to me with your webpack config and with the fix!

I didn't expect to see `navigation.js` appear in your webpack bundle because `require` statements are transpiled away. Maybe it's there to support sourcemap debugging (which I haven't tried yet). Does the error go away if you remove `devtool: "source-map"` from your config?

**Comment by jmathew** [comment]
Yup, no source-map no problem.

**Comment by grahammendick** [comment]
Great, thanks for checking. I hope to start work on both your issues this weekend. I'll keep you posted

**Comment by grahammendick** [comment]
I've removed the byte order mark. @jmathew Could you check that [the new navigation.js](https://github.com/grahammendick/navigation/blob/master/build/npm/navigation/navigation.js) works for you, please?

**Comment by jmathew** [comment]
Looks good to me,
