### ISSUE TITLE
testing strategy for an application using this library

### ISSUE THREAD

**Issue by bsr203** [grahammendick/navigation#106]
Hi,

Can you give some pointers or an example on what is best way to test my app to validate everything related to routing works. Any way to make sure all the routes will be transitioned to the component on activation, etc.. At the least, I may take a [snpshot](https://facebook.github.io/jest/docs/tutorial-react.html#snapshot-testing) of all the urls to detect regression.

thanks,
bsr.

**Comment by grahammendick** [comment]
Great to hear from you again.

You can use snapshot testing if you want, but I've got a different approach you might like. All the `Navigation` functionality works on the server, so you can test the routing and component activation. Here's an example that uses `ReactTestUtils` to render the `NavigationLink` component and then checks the `href` goes to the right `State` and passes the right data.

```jsx
var stateNavigator = new StateNavigator([
  {key: 'people'},
  {key: 'person'}
]);

// Render your component
var renderer = ReactTestUtils.createRenderer();
renderer.render(
  <NavigationLink
    key="person"
    navigationData={id: 11}>
    Brenda
  </NavigationLink>
);
var link = renderer.getRenderOutput();

// Navigate along your anchor's href
var url = link.props['href'].substring(1);
stateNavigator.navigate(url);

// Assert you reach the right state and pass the right data
assert.strictEqual(stateNavigator.stateContext.state.key, 'person'); 
assert.strictEqual(stateNavigator.stateContext.data.id, 11); 
```

This is the approach I've used to [test Navigation React](https://github.com/grahammendick/navigation/blob/master/NavigationReact/test/NavigationLinkTest.tsx)

**Comment by bsr203** [comment]
thank you so much for the quick response. This would work great and will try out.

when thinking about it, do you think we can use it for integration / end to end test. If I render my app as
```
const stateNavigator = new StateNavigator(routeConf);
stateNavigator.onNavigate((oldState, state, data) => {
  ReactDOM.render(<Root
    store={store}
    router={stateNavigator}
    Component={state.component}
    // route={} - relay route
    // params={} - addl params
  />, rootEl);
});

stateNavigator.start();
```

then I can do a transition to all states, with a precondition that all the API requests would succeed (or mocked), then we can dump out the rendered page and snapshot testing would detect any regression. One difficulty is that any minor change in UI would result in invalid snapshot, but it is easy to update with jest. 
or do you see more / easier possibilities.

thanks again.

**Comment by grahammendick** [comment]
I wouldn't run `ReactDOM.Render` in a test environment. You're better off using a test renderer on the server.

Isn't it more a question of how you test `Relay` than how you test `Navigation`?

**Comment by grahammendick** [comment]
Here's another option if you just want to test your Urls go to the right state with the right data

```jsx
var stateNavigator = new StateNavigator([
  {key: 'people'},
  {key: 'person'}
]);

stateNavigator.navigateLink('person/10');

assert.strictEqual(stateNavigator.stateContext.state.key, 'person'); 
assert.strictEqual(stateNavigator.stateContext.data.id, 11);
```

This is the approach I've used to [test Navigation](https://github.com/grahammendick/navigation/blob/master/Navigation/test/NavigationDataTest.ts)

**Comment by bsr203** [comment]
Indeed, I am good with your first approach to validate the url builds correctly. But, was thinking aloud the possibility of simpler e2e test without using external tools like protractor, nightwatch. Not to test the use of this library, but a possibility because this library makes it easy to transition to all the application state .

**Comment by grahammendick** [comment]
That sounds like a very interesting idea. Give it a go and please let me know how it works out
