### ISSUE TITLE
No TypeConverter for Object

### ISSUE THREAD

**Issue by PawkaHub** [grahammendick/navigation#108]
Would be awesome if we could include objects in our defaults payload when navigation between routes. For example, I'd love to be able to do this so that certain object state on routes could be easily shared between client and server:

```
const auth = {
  token: '1234'
}

const States = [{
  key: 'home',
  route: '',
  defaults: { pageNumber: 2, auth }
  component: Home,
}];

stateNavigator.configure(States);
```

As it currently stands, passing data this way as an object throws an error stating that there's no TypeConverter for Objects. Is this something that's possible to add, or are we limited to Bools/Arrays/Dates/Numbers/Strings for a reason I'm not aware of?

**Comment by grahammendick** [comment]
Hey, thanks for the interesting question.

The Navigation router is a data-first router. This means you can get all your navigation working without worrying about routes and URLs, at first. But the idea is that, once your navigation is working, you go back and make your URLs look pretty. You do this by configuring default types and route parameters.

I’m not sure if we could stick to this idea if we introduced an object `TypeConverter`. If we converted objects to and from `JSON`, for example, then how could we go back and tidy up our URLs?

Could you show me what the URL in your example might look like once it was tidied up, please?

**Comment by grahammendick** [comment]
I’ve been thinking about this a bit more over lunch. With `object rest/spread` you can pretty much do what you want already, I think, and still have pretty URLs.

```js
const States = [{
  key: 'home',
  route: '',
  defaults: { pageNumber: 2 }
  defaultTypes: { token: 'number' }
  component: Home,
}];

// generates URL /?token=1234
stateNavigator.navigate('home', { ...auth });

// auth = { token: 1234 }
stateNavigator.states.home.navigated = ({ ...auth }) => {
};
```

**Comment by PawkaHub** [comment]
Hey thanks for the response!

Like you said, I did up just using rest/spread to get the values shared between server/client. The use case I had been trying to share the data between the server and the client without the need to have those stored in the URL as query params, which was why not being able to use an object seemed unintuitive to me. After reading your explanation though, I can see that it was just a lack of understanding on my end as to the requirement that everything passed through as data be mappable to the url as query params as well. You can close this off if you like as I've found a solution that works within the design of your awesome framework.

**Comment by grahammendick** [comment]
Thanks again for the question. Have a great New Year.
