### ISSUE TITLE
Qn: refresh API to includeCurrentData 

### ISSUE THREAD

**Issue by bsr203** [grahammendick/navigation#109]
Hello,

As explained [here](http://grahammendick.github.io/navigation/documentation/current-data.html), it is easy to override part of the url data using `RefreshLink`, like 

```
<NavigationReact.RefreshLink 
  navigationData={{page: 2}}
  includeCurrentData={true}
  stateNavigator={stateNavigator}>
  Page Two
</NavigationReact.RefreshLink>
```

I like to do the same with programmatic refresh API

```
stateNavigator.refresh({page: 2});
```
so, I want to retain all the data, and overwrite `page`. From [this test](https://github.com/grahammendick/navigation/blob/master/Navigation/test/navigation-tests.ts#L94) it looks like, I may need to specify all the keys I need to retain. Is there a better way.

My use case is to update the url, when the id is selected through a select box. or update search query in the url when the user invoke search action (so history back preserves the results).

it would be quite convenient if I could do

```
stateNavigator.refresh({page: 2}, true);
```
where `true` indicates `includeCurrentData`

thanks,
bsr.

**Comment by grahammendick** [comment]
Great to see you’re using current data. Here's the equivalent navigation with the programmatic API:
```js
var data = stateNavigator.stateContext.includeCurrentData({page: 2});
stateNavigator.refresh(data);
```
Just to let you know, you can import `RefreshLink` by name and avoid the `NavigationReact` qualifier:
```js
import { RefreshLink } from ‘navigation-react’;

<RefreshLink 
  navigationData={{page: 2}}
  includeCurrentData={true}
  stateNavigator={stateNavigator}>
  Page Two
</RefreshLink>
```
Happy New Year,
Graham

**Comment by grahammendick** [comment]
Another thought, here’s that same navigation using `object spread` notation:
```js
stateNavigator.refresh({...stateNavigator.stateContext.data, page: 2});
```

**Comment by bsr203** [comment]
thank you. `stateNavigator.stateContext.data` probably what I was looking for. may be my question should have simply as how to get current navigation data. thanks again for your prompt response.

**Comment by bsr203** [comment]
One quick qn. With `refresh `, is there a way to replace the history, instead of adding to it. My usecase is, if the view is asked to render without some params, I set it through refresh. This causes back navigation fails as it always refreshes when I back to the invalid (with no params) url. thanks.

**Comment by grahammendick** [comment]
Yes, you pass it as the second parameter if you’re using the programmatic API:
```js
stateNavigator.refresh({page: 2}, ‘replace’);
```
Or as the `historyAction` prop if you’re using the Component:
```jsx
<RefreshLink 
  navigationData={{page: 2}}
  historyAction=“replace”>
  Page Two
</RefreshLink>
```

**Comment by bsr203** [comment]
thanks a ton. it works great. If some of the url params are not set, I do `refresh` at the constructor of the react component with proper default params. It works well, but I am not sure whether it is ok to do at the constructor. `componentDidMount` is too late as it already rendered. [componentWillMount](https://facebook.github.io/react/docs/react-component.html#componentwillmount) doc say, use construct instead. Will feel confident with your approval.

**Comment by grahammendick** [comment]
Yes, `constructor` is recommended over `componentWillMount`.

Did you know that you can set default params with the Navigation router?
```js
const stateNavigator = new StateNavigator([
  {key: ‘search’, route: {page?}, defaults: {page: 1, sort: ‘asc’}}
]);
```
That way a blank Url is still valid and your page number and sort order are always populated so there's no need to redirect.

**Comment by bsr203** [comment]
thank you for quick response. I will utilize default params, but in my case I need to determine the params programmatically (like, default id on initial rendering if none is selected by the user). thanks again for super helpful. cheers.
