### ISSUE TITLE
typescript declaration file link is broken

### ISSUE THREAD

**Issue by bsr203** [grahammendick/navigation#110]
ref: http://grahammendick.github.io/navigation/download/index.html

**Comment by grahammendick** [comment]
Thanks, I'll probably point it at the [one in this project](https://github.com/grahammendick/navigation/blob/master/Navigation/test/node_modules/%40types/navigation.d.ts) instead of the one on Definitely Typed

**Comment by grahammendick** [comment]
The Definitely Typed file's been renamed from navigation.d.ts to index.d.ts. Updated link to point at index.d.ts
