### ISSUE TITLE
question: initial state transition

### ISSUE THREAD

**Issue by bsr203** [grahammendick/navigation#115]
Hi,

a quick question. does the navigator hit root ("/") state first before the specific path at url.
![screen shot 2017-02-12 at 5 08 39 pm](https://cloud.githubusercontent.com/assets/1966521/22866573/c5f8a9b8-f146-11e6-93f2-ddc366c90ec6.png)

above, I navigate to `n/auth/signin`, but the state key is `/`, I was expecting `n/auth/signin`.  I have a valid state registered as seen in `stateNavigator.states`

![screen shot 2017-02-12 at 5 06 50 pm](https://cloud.githubusercontent.com/assets/1966521/22866592/22f1bd1c-f147-11e6-849a-4884879c0e55.png)

thanks you.
bsr.

**Comment by grahammendick** [comment]
Hey there, good to hear from you.

No, there's nothing special about the root url. In fact, `onNavigate` fires before the url updates. So I'm guessing that the url would update to the root if you played the debugger on a bit?

**Comment by bsr203** [comment]
sorry. I wasn't clear. I wasn't navigating to `n/auth/signin` from another url, but directly entering `http://localhost:3000/n/auth/signin` in the browser. I am after this as root(`/`) is currently protected only for authorized users, and have a check to bypass it like

```
const stateNavigator = new StateNavigator(routeConf);
stateNavigator.onNavigate((oldState, state, data) => {

  if (state.isPublic) {
  // render public app
  } else {

  }

}
```

for `n/auth/signin` state, `isPublic` is `true`.

thanks a gain for your quick response.

**Comment by bsr203** [comment]
sorry it should have been `http://localhost:3000/#/n/auth/signin` :-) thanks.

**Comment by grahammendick** [comment]
Cool. Did you know that you can [switch to HTML5 history](http://grahammendick.github.io/navigation/documentation/html5-history.html) to get rid of hashes from your urls?

**Comment by bsr203** [comment]
didn't really think about that :-) thanks for pointing out that.
