### ISSUE TITLE
How to use navigation-react without getting PropTypes errors

### ISSUE THREAD

**Issue by nathggns** [grahammendick/navigation#135]
Hi. It appears there is not a version of `navigation-react` on npm that includes your fixes for the PropTypes deprecation. Could you either add a release to npm or advise on a workaround?

**Comment by grahammendick** [comment]
Hi. My bad. It’s ready to go, I just haven’t released it yet. Thanks for the reminder. I’ll try and release it this evening and will keep you posted

**Comment by nathggns** [comment]
Thank you very much :)

**Comment by grahammendick** [comment]
I just released [Navigation React v2.0.5](https://github.com/grahammendick/navigation/releases/tag/v2.0.5-NavigationReact). Sorry I sat on it for so long and thanks again for the reminder :o)
