### ISSUE TITLE
Qn: use without NavigationLink

### ISSUE THREAD

**Issue by bsr203** [grahammendick/navigation#143]
hi,

I found one case where I cannot use "NavigationLink", but use href directly. [Here](https://github.com/palantir/blueprint/blob/master/packages/core/src/components/menu/menuItem.tsx#L113) they use an anchor to render MenuItem links. When I pass href (obtained with stateNavigator.historyManager.getHref(stateNavigator.getNavigationLink(stateKey, navigationData)); ), everything work except the page reloads whenever I lick the link. I assume "NavigationLink" handles the events so that the page doesn't reload on navigation.

What is the best way to handle this? menuItem component could use the children prop or a custom element to render the content, but need change in that library. Anything I am missing?

Thanks,
bsr.

**Comment by grahammendick** [comment]
You should also pass an `onClick` prop to override the default behaviour.

```
function menuClick(e) {
  if (!e.ctrlKey && !e.shiftKey && !e.metaKey && !e.altKey && !e.button) {
    e.preventDefault();
    var link = stateNavigator.historyManager.getUrl(e.currentTarget);
    stateNavigator.navigateLink(link);
  }
}
```

**Comment by bsr203** [comment]
thanks. that works great!
