### ISSUE TITLE
Error when parsing an URL with a query string containing a number 1 followed by the underscore character

### ISSUE THREAD

**Issue by iox** [grahammendick/navigation#146]
Hi,

First of all, thank you for your fantastic library. I have encountered an issue that it's baffling me. 

I'm getting this error when trying to visit a URL with a specific query string:

`Uncaught Error: The Url /login?login_token=1_ is invalid
Cannot read property 'convertFrom' of undefined`

![screenshot_20171011_120921](https://user-images.githubusercontent.com/452823/31434590-0b88fdd6-ae7d-11e7-9afe-e4e067dad031.png)

I have been playing around with some combinations. These URLs work:

`http://localhost:4001/#/login?login_token=1a_`
`http://localhost:4001/#/login?login_token=a_`
`http://localhost:4001/#/login?login_token=a`
`http://localhost:4001/#/login?login_token=_____`
`http://localhost:4001/#/login?login_token=2_`

These don't work:

`http://localhost:4001/#/login?login_token=1_`
`http://localhost:4001/#/login?login_token=a1_`
`http://localhost:4001/#/login?login_token=a1_z`
`http://localhost:4001/#/login?login_token=1_____`
`http://localhost:4001/#/login?login_token=21_`

So, it looks like the combination of **1_** (number one, followed by underscore), is the culprit.

I have tracked the error down to a converterKey being an empty string, but I'm not sure how to continue to fix it:

![screenshot_20171011_122144](https://user-images.githubusercontent.com/452823/31435118-d9a02f68-ae7e-11e7-9054-1691af442fba.png)

Thanks!

**Comment by grahammendick** [comment]
Hey Ignacio, great to hear from you and thanks for including so much detail.

To explain the problem, I’ll try to generate your URL using the Navigation router:
```
var link = stateNavigator.getNavigationLink('login', { login_token: '1_' });
```
You’d expect this to generate `/login?login_token=1_`, but it actually generates `/login?login_token=10_` instead!

So where is that annoying `0` coming from and how can we get rid of it?

The `_` character is reserved by the Navigation router. It uses it to separate URL parameter values from their data types. So the Navigation router’s default behaviour is to escape the `_` by prefixing it with a `0`. You can turn this behviour off by setting `trackTypes` to false on your `State`:

```
{key: 'login', route: 'login', trackTypes: false}
```
By setting `trackTypes` to false on your `State` the Navigation router won’t add the `0` and it won’t throw an error with your URL, `/login?login_token=1_`.

You can read more about [tidying up URLs](http://grahammendick.github.io/navigation/documentation/routes.html). Let me know how you get on.

**Comment by iox** [comment]
Thanks so much @grahammendick !

It worked like a charm. Thanks for pointing me to that documentation page, I should have read it more carefully :).

**Comment by grahammendick** [comment]
Always happy to help 😄
