### ISSUE TITLE
Navigating back if trackCrumbTrail is set to false

### ISSUE THREAD

**Issue by GordanRatkovic** [grahammendick/navigation#152]
Is it possible to navigate back using the `<NavigationBackLink>` if `trackCrumbTrail` is set to `false`?

If not, what would be a recommended approach for navigating back? Would a simple `window.history.back()` work?

**Comment by grahammendick** [comment]
No, `NavigationBackLink` only works if `trackCrumbTrail` is set to `true`.

Yes, `history.back` works, but be careful not to take the user back out of your domain. They might've bookmarked directly to your page, in which case `history.back` would take them away from your site!

I hope that helps and thanks for the question.

**Comment by GordanRatkovic** [comment]
All clear!
Thanks for the quick response.
