### ISSUE TITLE
How to redirect?

### ISSUE THREAD

**Issue by GordanRatkovic** [grahammendick/navigation#156]
How could I redirect users under certain conditions?
An example would be redirecting a user trying to access something like /myprofile to the /login page?

Is there a way I could do that before the 'myprofile' component is even rendered?
What's the earliest point in time I could catch that?

**Comment by grahammendick** [comment]
Welcome back.

I’ve put together a [jsfiddle that shows how you can redirect](https://jsfiddle.net/1ym8rm59/6/) from 'profile' to 'login'. It starts on the home page with links to 'login' and 'profile'. If you click on the 'Profile' link, it redirects you to 'login' before the profile is rendered. Click the 'Log In' button and it'll log you in and redirect you to 'profile'.

The redirect from 'profile' to 'login' happens inside a `navigating` function attached to the 'profile' `State`. The Navigation router calls this function before navigating to 'profile'. If you’re not logged in yet then it'll navigate you to 'login'. If you are logged in then it calls the `navigate` parameter which continues with the navigation and takes you to 'profile'.
```javascript
stateNavigator.states.profile.navigating = (data, url, navigate) => {
  if (!loggedIn)
    stateNavigator.navigate('login');
  else
    navigate();
}
```
Any questions, let me know

**Comment by GordanRatkovic** [comment]
Wow, thanks for the fast and extensive response!

Your solution did the trick, I missed the part in the documentation about the `navigating` method which is used for interception.

Thanks again!
