### ISSUE TITLE
HTML5 history issue with hard navigation

### ISSUE THREAD

**Issue by GordanRatkovic** [grahammendick/navigation#158]
Hello again!

I have my routes set up in the following way, with HTML5 history enabled:

```
var stateNavigator = new Navigation.StateNavigator([
    {
        key: 'main',
        route: '',
        trackCrumbnail: false
    },
    {
        key: 'about',
        route: 'about',
        trackCrumbnail: false
    },
    {
        key: 'account',
        route: 'account',
        trackCrumbnail: false
    }
], new Navigation.HTML5HistoryManager());
```

I have the local server running on 0.0.0.0:4001

When I navigate to http://0.0.0.0:4001, everything looks good, I land on the main page and I can navigate to the `account` route and the `about` route normally via links. The url changes also accordingly to http://0.0.0.0:4001/account and http://0.0.0.0:4001/about

But if I try to do a hard browser navigate from the address bar to http://0.0.0.0:4001/about I get `Cannot GET /account`.

**Comment by grahammendick** [comment]
Hi!

That error is returned from the server not the client. When you use HTML5 history, you need to configure your server to handle the Urls. You could just add a fallback handler on the server that returns the home page.

Also, did you know you could simplify your configuration? I've removed `trackCrumbTrail` because it defaults to `false` and destructured `StateNavigator` and `HTML5HistoryManager`.
```javascript
var { StateNavigator, HTML5HistoryManager } = Navigation;

var stateNavigator = new StateNavigator([
    {
        key: 'main',
        route: '',
    },
    {
        key: 'about',
        route: 'about',
    },
    {
        key: 'account',
        route: 'account',
    }
], new HTML5HistoryManager());
```

**Comment by GordanRatkovic** [comment]
Thanks, will look into that.

On a related note, is there a way to define a default page to render, even when I try to access a route that's not defined?

Right now I get an error stating: `Uncaught Error: The Url /anything is invalid No match found`. Is there any way to catch this in order to redirect the user somewhere else?
I tried the `stateNavigator.onNavigate` method, but the error happens before the method gets fired.

Thanks!

**Comment by grahammendick** [comment]
That's a great question! There are a couple of different ways you could display a default page. Let me know which you prefer.

1. Wrap `stateNavigator.start()` inside a `try/catch` block
```javascript
try {
  stateNavigator.start()
} catch {
  ReactDOM.render(<Default />,...);
}
```
2. Configure a catch-all `State` as the **_last_** `State` in your array
```javascript
var stateNavigator = new StateNavigator([
  ....,
  { key: 'default', route: '{*x}', defaultTypes: {x: 'stringarray'}, trackTypes: false }
]);

stateNavigator.states.default.navigated = () => {
  ReactDOM.render(<Default />,...);
}
```

**Comment by GordanRatkovic** [comment]
Hey,

Well the first one is pretty obvious when you think about it, however the 2nd option seems like the proper way of handling this.
It didn't occur to me that the matching happens in the order the states are defined. Great solution for my problem.

Thanks again Graham!
