### ISSUE TITLE
Can't navigate back to first scene on RN Android

### ISSUE THREAD

**Issue by SatyaFariz** [grahammendick/navigation#236]
I'm developing RN app on Android. I've looked at the examples but can't figure out why I can't navigate back to the first scene (the scene when the app opens) after pushing the second scene. I can only go back after navigating away from the second scene, however pressing back button just closes the app, not navigating back to the default scene. This is a very weird behavior.

RN version: 0.59.5

```
import React from 'react'
import { StateNavigator } from 'navigation'
import { NavigationHandler } from 'navigation-react'
import { addNavigateHandlers, Scene } from 'navigation-react-native'

import HomeScreen from './screens/home/HomeScreen'
import SignUpScreen from './screens/sign-up/SignUpScreen'
import SignInScreen from './screens/sign-in/SignInScreen'
import ForgotPasswordScreen from './screens/forgot-password/ForgotPasswordScreen'

var stateNavigator = new StateNavigator([
  { key: 'home', title: 'Home', trackCrumbTrail: true },
  { key: 'signUp', title: 'SignUp', trackCrumbTrail: true },
  { key: 'signIn', title: 'SignIn', trackCrumbTrail: true },
  { key: 'forgotPassword', title: 'ForgotPassword', trackCrumbTrail: true }
])

const { home, signUp, signIn, forgotPassword } = stateNavigator.states

home.renderScene = () => <HomeScreen/>
signUp.renderScene = () => <SignUpScreen/>
signIn.renderScene = () => <SignInScreen/>
forgotPassword.renderScene = () => <ForgotPasswordScreen/>

stateNavigator.navigate('home')
addNavigateHandlers(stateNavigator)

export default ({crumb}) => (
  <NavigationHandler stateNavigator={stateNavigator}>
    <Scene crumb={crumb} />
  </NavigationHandler>
)
```

**Comment by grahammendick** [comment]
Thanks for giving the Navigation router a try. I think you forgot to add a `launchMode` of `singleTop` to the `MainActivity`. See the [Android section of the setup guide](https://grahammendick.github.io/navigation/documentation/native/setup.html)

**Comment by SatyaFariz** [comment]
My bad. I misplaced the ```launchMode``` of ```singleTop``` in ```MainApplication``` instead of ```MainActivity```. It's working now. Thanks.
