### ISSUE TITLE
How to reset Navigation states ?

### ISSUE THREAD

**Issue by SatyaFariz** [grahammendick/navigation#239]
I want to mimic ```ReactNavigation switch navigator``` behavior that resets the routes to the default states after navigating away from it (for example after the user logs in/out). How can I do that ?

**Comment by grahammendick** [comment]
Your configuration probably looks like this
```js
var stateNavigator = new StateNavigator([
  { key: 'signUp', title: 'SignUp' },
  { key: 'home', title: 'Home', trackCrumbTrail: true },
])
```
When you navigate from 'signUp' to 'home' it produces the stack 
```
signUp → home
```
But you don’t want the user to be able to navigate back to ‘signUp’ after they’ve logged in. You can clear the stack by setting `trackCrumbTrail` to false (the default) on the 'home' `State`
```js
var stateNavigator = new StateNavigator([
  { key: 'signUp', title: 'SignUp' },
  { key: 'home', title: 'Home' },
])
```
This time when you navigate from 'signUp' to 'home' it produces the stack 
```
home
```

**Comment by SatyaFariz** [comment]
Can I configure the ```trackCrumbTrail``` property on the fly while I'm navigating through the scenes ? Sometimes I want to redirect the user to a specific screen after logging in.

**Comment by grahammendick** [comment]
You can change the crumb trail (stack) on the fly. Let’s say you sometimes want to show the 'profile' screen after a login. You can’t set `trackCrumbTrail` to false because other times you want to preserve the stack when showing the ‘profile’ screen.
```js
var stateNavigator = new StateNavigator([
  { key: 'signUp', title: 'SignUp' },
  { key: 'profile', title: 'Home', trackCrumbTrail: true },
])
```
Before you navigate to the 'profile' screen the Navigation router calls the `truncateCrumbTrail` attached to the `State`. It passes in the current crumb trail. Here you can check if it’s coming from the 'signUp' screen. If it is you clear the stack otherwise you return the existing stack.
```js
const { signUp, profile } = stateNavigator.states;
profile.truncateCrumbTrail = (state, data, crumbs) => (
  crumbs.slice(-1).state = signUp ? [] : crumbs
);
```

**Comment by SatyaFariz** [comment]
The problem with this solution and with using ```trackCrumbTrail: true``` is that, if the screen is already mounted, it has a going-back behavior. Meaning all the screen states remain the same. So I have to do extra manual work of refetching the whole data to update props and states and navigate to a specific tab (if I have a tab-navigation) in my screen, which is not an ideal solution in my opinion.

I am using ```Relay``` for state management. With ```React Navigation``` all I need to do is use the ```switch navigator``` and and reset the ```Relay Environment``` after the user logs in so that all the cache and navigation states is reset to the default states. I expect the same behavior to work with this library. But I can't figure out how to do it in an elegant and simple way.

**Comment by grahammendick** [comment]
It doesn’t sound like you implemented the `truncateCrumbTrail` function. This function gives you full control over the stack. For example, if you always return an empty array, then it will behave the same as a `switch navigator`. Every time you navigate to the profile screen the Navigation router will clear the stack. 

```js
const stateNavigator = new StateNavigator([
  { key: 'signUp', title: 'SignUp' },
  { key: 'profile', title: 'Home', trackCrumbTrail: true },
])

const { profile } = stateNavigator.states;
profile.truncateCrumbTrail = (state, data, crumbs) => [];
```

Please add the `truncateCrumbTrail` function to the 'profile' `State` and let me know how you get on.

**Comment by SatyaFariz** [comment]
I did implement the ```truncateCrumbTrail``` function and it did clear the stack just like you mentioned. But like I said it has a going-back behavior rather than pushing a new screen onto the stack.

```
var stateNavigator = new StateNavigator([
  { key: 'main', title: 'Main', trackCrumbTrail: true  },
  { key: 'signUp', title: 'SignUp', trackCrumbTrail: true },
  { key: 'signIn', title: 'SignIn', trackCrumbTrail: true }
])

const { 
  main, 
  signUp, 
  signIn 
} = stateNavigator.states

main.renderScene = () => <MainScreen/>
signUp.renderScene = () => <SignUpScreen/>
signIn.renderScene = () => <SignInScreen/>

main.truncateCrumbTrail = (state, data, crumbs) => []

stateNavigator.navigate('main')
addNavigateHandlers(stateNavigator)
```

The default screen is ```main``` (the user doesn't need to be signed in to see a list of book listing in main screen). Then the user goes to 'signIn' screen. After the sign in process finished the user is redirected back to the 'main' screen.  But instead of pushing a new ```main``` screen and clearing the stack, it goes back to ```main``` screen and clears the stack, so the screen states are preserved. Also I have a tab-navigation in ```main``` screen, so if the user was in the second tab, he will stay in the second tab (first tab is the default) with the same data after redirect. So I have to manually refetch the whole data and navigate to the first tab to update the view. This is not what I expected.

**Comment by grahammendick** [comment]
Ahh, thanks for providing a more detailed explanation. I understand exactly what you mean now.

I suggest you add a React `key prop` to your `MainScreen` component. If React detects that the `key` has changed then it will clear all the state from the component tree, for example, the selected tab.
```js
main.renderScene = ({clear = false}) => <MainScreen key={clear ? '1' : '0'}/>
```
After the sign in process is finished, when you navigate to the `MainScreen` pass a different `clear` value to reset the `MainScreen`
```js
stateNavigator.navigate('main', {clear: true});
```

**Comment by SatyaFariz** [comment]
It works! I'll close this for now. Thanks for the quick reply!!!
