### ISSUE TITLE
How to disable animation when trackCrumbTrail is true ?

### ISSUE THREAD

**Issue by SatyaFariz** [grahammendick/navigation#242]
I want to disable animation in some screens on Android. How can I do that ?

**Comment by grahammendick** [comment]
You can [customise the animation on Android](https://grahammendick.github.io/navigation/documentation/native/custom-animation.html) for a screen by adding `getUnmountStyle` and `getCrumbStyle` functions to the corresponding `State`. The value you return points at an Android animation resource file. If you don’t want to animate a screen then return a non-existent file name from these functions. I’ve chosen 'none' but any name would do as long as there isn’t a matching Android animation resource
```js
const { profile } = stateNavigator.states;
profile.getCrumbStyle = () => 'none';
profile.getUnmountStyle = () => 'none';
```

**Comment by grahammendick** [comment]
Have you had a chance to try it out? Are you happy to close this?

**Comment by SatyaFariz** [comment]
Hi sorry for the slow response.

I had try it and it worked. However the back navigation transition is rather awkward because the previous screen is animating.

**Comment by grahammendick** [comment]
No problem, glad you're still there.

Sounds like you want to disable the animation of the previous screen, too. If 'home' is the previous screen then you can disable that in the same way.
```js
const { home } = stateNavigator.states;
home.getCrumbStyle = () => 'none';
home.getUnmountStyle = () => 'none';
```

**Comment by SatyaFariz** [comment]
What if I want to disable the animation of the previous screen (home screen) only if the current screen is profile screen. Is that possible ?

**Comment by grahammendick** [comment]
Yep. The `getCrumbStyle` gets passed in the `nextState`
```js
const { home } = stateNavigator.states;
home.getCrumbStyle = (from, state, data, crumbs, nextState) => (
  nextState.key === 'profile' ? 'none' : null
)
```

**Comment by SatyaFariz** [comment]
I mean when navigating back. The animation becomes awkward again

**Comment by grahammendick** [comment]
Have you debugged it and made sure it returns 'none' when you want?

**Comment by SatyaFariz** [comment]
Are you sure ```home.getCrumbStyle = (from, state, data, crumbs, nextState) => (
  nextState.key === 'profile' ? 'none' : null
)``` is the correct arguments ?

Both ```state``` and ```nextState``` are empty objects. I made it work using ```crumbs.key```

**Comment by grahammendick** [comment]
You're right, I got the parameters wrong! Sorry, it should be
```js
const { home } = stateNavigator.states;
home.getCrumbStyle = (from, data, crumbs, nextState) => (
  nextState.key === 'profile' ? 'none' : null
)
```

**Comment by SatyaFariz** [comment]
> You can [customise the animation on Android](https://grahammendick.github.io/navigation/documentation/native/custom-animation.html) for a screen by adding `getUnmountStyle` and `getCrumbStyle` functions to the corresponding `State`. The value you return points at an Android animation resource file. If you don’t want to animate a screen then return a non-existent file name from these functions. I’ve chosen 'none' but any name would do as long as there isn’t a matching Android animation resource
> 
> ```js
> const { profile } = stateNavigator.states;
> profile.getCrumbStyle = () => 'none';
> profile.getUnmountStyle = () => 'none';
> ```

This no longer works with the latest version of this library and react native.

**Comment by grahammendick** [comment]
Take a look at the [updated documentation](https://grahammendick.github.io/navigation/documentation/native/custom-animation.html). It's all done with `props` now.
```jsx
<NavigationHandler stateNavigator={stateNavigator}>
  <NavigationStack
    crumbStyle={() => 'none'}}
    unmountStyle={() => 'none'}} />
</NavigationHandler>
```
You can keep your existing `getCrumbStyle` functions and call into them from the props
```jsx
<NavigationStack
  crumbStyle={(from, state, data, crumbs, nextState) => (
    state.getCrumbStlye ? state.getCrumbStlye(from, data, crumbs, nextState) : null
  )} />
```
