### ISSUE TITLE
iOS Large Titles Cause incorrect screen area for render 

### ISSUE THREAD

**Issue by mpiannucci** [grahammendick/navigation#265]
When large titles are enabled and wrapped in a `ScrollView` or a `FlatList` everything seems to scroll as it should, but the content window is cropped incorrectly. 

![screen-crop](https://user-images.githubusercontent.com/1832671/61192283-43ccd480-a681-11e9-89fe-4624559788c0.gif)

**Comment by mpiannucci** [comment]
JSX to match: 

```tsx
	return (
		<FlatList
			style={{flex: 1}}
			refreshing={stationsState.isLoading}
			data={matchedStations}
			renderItem={(info) => (
				<StationSearchItem station={info.item} />
			)}
			ListHeaderComponent={
				<NavigationBarIOS largeTitle={true} title={'Search'}>
					<SearchBarIOS onChangeText={(newSearch) => {
						setSearchQuery(newSearch)
					}} />
				</NavigationBarIOS> 
			}
		/>
	);
```

**Comment by grahammendick** [comment]
It’s great to see you using the search bar with large titles. They’re such beautiful iOS features.

You must wrap your scene content in a `SafeAreaView` component or a `ScrollView` component with `contentInsetAdjustmentBehavior` set to 'automatic' to prevent the cropping. I added a note about this at the bottom of the [push navigation documentation](https://grahammendick.github.io/navigation/documentation/native/push-navigation.html).

You can check out the  [zoom sample](https://github.com/grahammendick/navigation/tree/master/NavigationReactNative/sample/zoom) to see the search bar with large titles in action.

**Comment by mpiannucci** [comment]
So I adjusted the code a bit, but was not able to fix it. A `FlatList` is a subclass of `ScrollView` so I assumed this would work but it gives the same behavior. Its the same thing whether or not I wrap the whole thing in a `SafeAreaView`

```tsx
	return (
		<SafeAreaView style={{ flex: 1 }}>
			<FlatList
				contentInsetAdjustmentBehavior={'automatic'}
				style={{ flex: 1 }}
				refreshing={stationsState.isLoading}
				data={matchedStations}
				renderItem={(info) => (
					<StationSearchItem station={info.item} />
				)}
				ListHeaderComponent={
					<NavigationBarIOS largeTitle={true} title={'Search'}>
						<SearchBarIOS onChangeText={(newSearch) => {
							setSearchQuery(newSearch)
						}} obscureBackground={false} />
					</NavigationBarIOS>
				}
			/>
		</SafeAreaView>
	);
```

**Comment by mpiannucci** [comment]
Also, obviously none if this is made to be urgent or a knock on the lib, just wanted to report behavior I found while playing around with it!

**Comment by grahammendick** [comment]
No worries, I appreciate the feedback. Keep it coming.

I don't think a `FlatList` is a sublclass of `ScrollView`. Can you try changing to a `ScrollView` with `contentInsetAdjustmentBehavior` set to "automatic", please?

**Comment by mpiannucci** [comment]
Thanks, I tried that example and everything seemed fine. Then I tried my code like below. I still get the same problems showing up and I have no idea why haha. I wonder if RN version 0.60 is doing it, since the colors example is using 0.59 

```tsx
	return (
		<ScrollView contentInsetAdjustmentBehavior={'automatic'}>
			<NavigationBarIOS largeTitle={true} title={'Search'}>
				<SearchBarIOS onChangeText={(newSearch) => {
					setSearchQuery(newSearch)
				}} obscureBackground={false}>
				</SearchBarIOS>
			</NavigationBarIOS>
			{
				stations.map((station) => (<StationSearchItem station={station}/>))
			}
		</ScrollView>
	);
```

**Comment by mpiannucci** [comment]
I am goin g to try more to debug it tomorrow, so no worries, I just wanted to post my progress. It could totally be something I am doing wrong

**Comment by grahammendick** [comment]
Thanks for the update. Why not try your code in 0.59 and see what happens?
