### ISSUE TITLE
Error when trying to switch components in a scene[Android]

### ISSUE THREAD

**Issue by arunmenon1975** [grahammendick/navigation#270]
_Note: Looks like i seem to have the most issues opened here and i am not terribly keen on that title but this one has me stumped. I re-read the docs and searched the issue list and SO but just couldn't find a resolution for my latest issue. An Android-only issue again._

I am getting the following (red screen)error when i attempt to switch components in my main entry file:

```
Trying to remove a view index above child count 0
view tag:33 
detail: View tag: 33
children(0):[],
indicesToRemove(1):[0,],
tagsToDelete(1):[29,]
...
...
```

My `App.js` does the initial registering etc and i navigate to my `Welcome` scene as the default entry for the app. Here i expect to start with some initial background API calls etc while presenting an intermediary `Loader` component to the user. If all goes well i then present the welcome screen to the user. I may use `redux` or `context` but for simplicity i now simulate it via a simple `setTimer` and in-component `state`. Everything works fine on IoS(in fact i can even auto redirect/navigate to another scene in IoS) but on Android i get the error i listed above. This error only happens when the timer completes and the switch is attempted i.e I get the loader component displayed as expected for 5 seconds and then the error shows up.

My App.js

```
import React from 'react';
import {Alert, BackHandler} from 'react-native';
import { StateNavigator } from 'navigation';
import {NavigationHandler} from 'navigation-react';
import {NavigationStack} from 'navigation-react-native';
import {MenuProvider} from 'react-native-popup-menu';

import {Provider} from 'react-redux';
import store from './src/redux/store';

import Menu from './src/scenes/Menu/Menu';
import Welcome from './src/scenes/Welcome/Welcome';

const stateNavigator = new StateNavigator([
  {
    key: 'welcome',
    trackCrumbTrail: true
  }, {
    key: 'menu',
    trackCrumbTrail: true
  }
])
const {welcome, menu} = stateNavigator.states;

welcome.renderScene = () => <Welcome/>;
menu.renderScene = () => <Menu/>;

stateNavigator.navigate('welcome');

class App extends React.Component {
  componentDidMount() {
    BackHandler.addEventListener("hardwareBackPress", this._handleHardwareBackPress);
  }
  componentWillUnmount() {
    BackHandler.removeEventListener("hardwareBackPress", this._handleHardwareBackPress)
  }
  _handleHardwareBackPress = (args) => {
    if (!stateNavigator.canNavigateBack(1)) {
      Alert.alert("Show a prompt with OK/CANCEL")
      return true
    }
  }
  render() {
    return (
      <MenuProvider>
        <Provider store={store}>
          <NavigationHandler stateNavigator={stateNavigator}>
            <NavigationStack/>
          </NavigationHandler>
        </Provider>
      </MenuProvider>
    );
  }
}
export default App;
```

My Welcome.js

```
import { NavigationContext } from 'navigation-react';
import React, { Component } from 'react';
import { StyleSheet } from 'react-native';
import AppLoaderCmp from '../../components/AppLoader/AppLoader';
import WelcomeCmp from '../../components/Welcome/Welcome';

class Welcome extends Component {
    state={
        loaded: false
    }
  componentDidMount(){
    setTimeout(()=>this.setState({loaded:true}),5000)
  }

  render() {
      return (
      <NavigationContext.Consumer>
        {({stateNavigator}) => {
            return this.state.loaded
            ?<WelcomeCmp stateNavigator={stateNavigator} />
           :  <AppLoaderCmp stateNavigator={stateNavigator} />
        }
    }
      </NavigationContext.Consumer>
    );
  }
}
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#E91E63'
  },
});

export default Welcome;

```

My Welcome component

```
import React from 'react';
import {Button, SafeAreaView, StyleSheet, Text} from 'react-native';
//import {gotoScreen, routesKeys} from '../../routes';

const WelcomeCmp = (props) => <SafeAreaView style={styles.container}>
    <Text>
        Welcome
    </Text>
    <Button
        title="To Menu Screen"
       // onPress={() => gotoScreen(routesKeys.MENU, stateNavigator)}
       onPress={() => console.log('Pressed the Menu button')}
       />
    <Button
        title="To Admin Screen"
        //onPress={() => gotoScreen(routesKeys.ADMIN, stateNavigator)}
        onPress={() => console.log('Pressed the Admin button')}
        />
    <Button title="Open SideDrawer" 
        //onPress={this._openDrawer}
        onPress={() => console.log('Pressed the SideDrawer button')}

        />
</SafeAreaView>

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#E91E63'
    }
});

export default WelcomeCmp;
```

My AppLoader component:

```
import React from 'react';
import {SafeAreaView, StyleSheet, Text} from 'react-native';

const AppLoaderCmp = (props) => <SafeAreaView style={styles.container}>
    <Text>
       App Loader
    </Text>
</SafeAreaView>
const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#E91E63'
    }
});

export default AppLoaderCmp;
```

I am using the latest version ` Navigation React Native` since i did an unlink/remove and re-added the libraries:

```
...
    "navigation": "^5.2.0",
    "navigation-react": "^4.1.1",
    "navigation-react-native": "^5.4.0",
...
```

I initially had a slightly more 'twisted' setup. I only did a `renderScene()` for my entry scene, and wanted to dynamically render the scene on demand where required. It does work though i am not sure if it is optimal. Ive reverted back to a simple example to check if the issue can be reproduced. It can. I also tried via checks in `componentDidUpdate` but get the same error. All my attempts of course work perfectly fine in IoS.

**Comment by grahammendick** [comment]
Never feel guilty about opening an issue. Thank you for using the Navigation router and for working with me to make it better.

Here's a workaround so that you're not stuck until I provide a fix. Move the `SafeAreaView` into the `Welcome` component, instead of having it in both the `AppLoader` and `WelcomeCmp`:
```jsx
<SafeAreaView style={styles.container}>
    <NavigationContext.Consumer>
        {({stateNavigator}) => {
            return this.state.loaded
                ? <WelcomeCmp stateNavigator={stateNavigator} />
                : <AppLoaderCmp stateNavigator={stateNavigator} />
        }}
    </NavigationContext.Consumer>
</SafeAreaView>
```

**Comment by arunmenon1975** [comment]
Ive also made a couple of gifs(for each OS) to help clarify the issue:

### IoS

![ios_capture](https://user-images.githubusercontent.com/2016484/61857638-26e69b80-aee2-11e9-9ba4-6eeed08bc6e2.gif)

### Android

![android_capture_1](https://user-images.githubusercontent.com/2016484/61862246-34ecea00-aeeb-11e9-8591-b7b777bcbb45.gif)

**Comment by arunmenon1975** [comment]
> Never feel guilty about opening an issue. Thank you for using the Navigation router and for working with me to make it better.
> 
> Here's a workaround so that you're not stuck until I provide a fix. Move the `SafeAreaView` into the `Welcome` component, instead of having it in both the `AppLoader` and `WelcomeCmp`:
> 
> ```js-jsx
> <SafeAreaView style={styles.container}>
>     <NavigationContext.Consumer>
>         {({stateNavigator}) => {
>             return this.state.loaded
>                 ? <WelcomeCmp stateNavigator={stateNavigator} />
>                 : <AppLoaderCmp stateNavigator={stateNavigator} />
>         }}
>     </NavigationContext.Consumer>
> </SafeAreaView>
> ```

I just saw this message now. I will make the change and update here if there is any change to the outcome.

**Comment by arunmenon1975** [comment]
> > Never feel guilty about opening an issue. Thank you for using the Navigation router and for working with me to make it better.
> > Here's a workaround so that you're not stuck until I provide a fix. Move the `SafeAreaView` into the `Welcome` component, instead of having it in both the `AppLoader` and `WelcomeCmp`:
> > ```
> > <SafeAreaView style={styles.container}>
> >     <NavigationContext.Consumer>
> >         {({stateNavigator}) => {
> >             return this.state.loaded
> >                 ? <WelcomeCmp stateNavigator={stateNavigator} />
> >                 : <AppLoaderCmp stateNavigator={stateNavigator} />
> >         }}
> >     </NavigationContext.Consumer>
> > </SafeAreaView>
> > ```
> 
> I just saw this message now. I will make the change and update here if there is any change to the outcome.

The issue is fixed with the change you had suggested! 

It does not seem like a `Navigation` library issue at all.  The 'cryptic' error message did mean something after all and seems more likely a user dev bug (or perhaps maybe even a OS feature, depending on how its looked at), or thats what i gather from some research (Eg [at SO](https://stackoverflow.com/questions/41819759/trying-to-remove-a-view-index-above-child-count-error)).

In my case i guess there is a brief period between when the state condition is being evaluated and `React` continuing with its rendering when there is no default `View`  to render. Perhaps even returning a `null` in a condition checked immediately after `render()` should work, if my understanding is right. I have the `SafeAreaView` as the root enclosing everything including the navigation context consumer as my fix for now.

I am closing the issue since it is fixed. Thanks for spending the time and the suggestion.

**Comment by grahammendick** [comment]
It is caused by the Navigation router. The Navigation router doesn’t like it when you change the first child of a Scene. I won’t reopen this though because I think it’s fair to assume the first child won’t change

**Comment by arunmenon1975** [comment]
Looks like i've stumbled across another issue, again Android-only. Not opening a new issue since i think it may be related to what you mentioned in the earlier comment:

> The Navigation router doesn’t like it when you change the first child of a Scene. I won’t reopen this though because I think it’s fair to assume the first child won’t change

I intend(ed) to use a `Popover` across both the OSs at certain strategic areas in my app. Unfortunately my attempt at integrating an off-the-shelf solution doesn't seem to work on Android.

`Android` does have a native (not documented much however) popover which can be integrated via `React Native` but getting a similar `IoS` experience is certainly a hurdle. So I decided to go with a `JS` solution and integrated [`React Native Popup Menu`](https://github.com/instea/react-native-popup-menu)(RNPM). Since ive used it before (and found it stable and quite versatile: it also has a `BottomSheet` equivalent) i didn't test its presence much but kept relevant placeholders during my early efforts(can be noticed in the `App.js` file that i added in one of my earlier comments). The popover menu seems to go a `context` route and needs a root `Provider`.  A simple stripped down (from the exact same setup as in the relevant comments above) example that does not work:

```
import {StateNavigator} from 'navigation';
import {NavigationHandler} from 'navigation-react';
import {NavigationStack} from 'navigation-react-native';
import React from 'react';
import {Text, View} from 'react-native';
import {MenuProvider} from 'react-native-popup-menu';
import {Menu, MenuOptions, MenuOption, MenuTrigger, renderers} from 'react-native-popup-menu';
const Welcome = props => (<View style={{flex:1}}> 
  <Menu
  renderer={renderers.SlideInMenu}
  onSelect={value => alert(`Selected number: ${value}`)}>
  <MenuTrigger text='Select option'/>
    <MenuOptions>
      <MenuOption value={1} text='One'/>
      <MenuOption value={2}>
        <Text style={{ color: 'red'}}> 
          Two
        </Text>
      </MenuOption>
      <MenuOption value={3} disabled={true} text='Three'/>
    </MenuOptions>
</Menu> 
</View>);
const stateNavigator = new StateNavigator([{key: 'welcome',trackCrumbTrail: true}]);
const {welcome} = stateNavigator.states;
welcome.renderScene = () => <Welcome/>
stateNavigator.navigate('welcome');

class App extends React.Component {
  render() {
    return (
      <MenuProvider>
        <NavigationHandler stateNavigator={stateNavigator}>
          <NavigationStack/>
        </NavigationHandler>
      </MenuProvider>
    );
  }
}
export default App;

```

It works fine on IoS however. If i replace the render method with this snippet, the popup works as expected (ruling out any issues with corrupted files or similar local dev issues):

```
...
render() {
    return (
      <View style={{flex:1}}> 
        <Menu
          renderer={renderers.Popover}
          onSelect={value => alert(`Selected number: ${value}`)}>
          <MenuTrigger text='Select option'/>
            <MenuOptions>
              <MenuOption value={1} text='One'/>
              <MenuOption value={2}>
                <Text style={{ color: 'red'}}> 
                  Two
                </Text>
              </MenuOption>
              <MenuOption value={3} disabled={true} text='Three'/>
            </MenuOptions>
        </Menu> 
      </View>
    );
  }
...
```

Again please do not that this issue is not a showstopper. I can possible attempt other JS solutions, or use native methods where available. There is in fact another RN library that bridges 2 separate native  libraries which exposes native popovers(though i may not get a Bottom sheet i think). Or in fact can even do away with Popovers and use alternatives like `modals` or such-like.

**Comment by grahammendick** [comment]
You must move the `MenuProvider` inside your scene.  Its name is confusing. It isn't like a `ReduxProvider` because it [renders UI elements](https://github.com/instea/react-native-popup-menu/blob/56bf1f0430add3609c9079e5356c7a813df7e760/src/MenuProvider.js#L218). 

```jsx
const Welcome = props => (<View style={{flex:1}}> 
<MenuProvider
  <Menu
    renderer={renderers.SlideInMenu}
    onSelect={value => alert(`Selected number: ${value}`)}>
    <MenuTrigger text='Select option'/>
    <MenuOptions>
      <MenuOption value={1} text='One'/>
      <MenuOption value={2}>
        <Text style={{ color: 'red'}}> 
          Two
        </Text>
      </MenuOption>
      <MenuOption value={3} disabled={true} text='Three'/>
    </MenuOptions>
  </Menu> 
</MenuProvider
</View>);
```

**Comment by arunmenon1975** [comment]
Thank you for the suggestion. Yes, indeed it works fine when i move it to the scene. Incidentally in my actual app i do have wrapper components but i use them mostly just to start off on some initialisations(wrap `Intl` provider after getting updated locale info from the `redux` store, send actions that returns required information like themes or device data etc), very similar to the linked implementation as a concept.

All of my major usecases/checks for using the `Navigation` router for a mobile app is done and i will be proceeding on as i foresee no immediate issues that may need attention. 

I did evaluate a few popular navigation/routing solutions for my app to get an actual feel of how they could fit in in my current app as well as, importantly, any future apps i may start out with. So. heres a quick short summary on why i didn't abandon ship despite some hurdles(for eg opening issues when i reached unexpected roadblocks at a basic level, with some being non-issues eventually or not having 'in-built' UI components like a `Sidedrawer` ready for integration):

- `React Navigation` ticked most if not all of the boxes but is an all-JS solution and i was keen on something more native for something as critical as navigation, if possible
- `React Native Navigation` is also quite good but it does take over and ends up owning the app, sort of, and has an imperative setup. I wondered if i might face compatibility issues later on with either other 3rd party solutions or anything i may come up with myself
- `Navigation` router seemed simple, performant and intuitive when i gave it a try. And it leant towards the native side of things while allowing for Javascript based usage, which is not the case, AFAIK, with `React Router's` native solution where it goes all-JS all over
-  the setup was straightforward and didn't try to 'takeover'
- Another clincher was that i could use the library and its unique approach across mediums. My current app, though simple, envisages a traditional web app for some heavy'ish work, and maybe a PWA  thrown into the mix as well. Or perhaps just a PWA where i could target a larger device range. I could basically use Navigation router across all my proposed/planned mediums.
- the core principles seem to suggest that there will be no unnecessary bloating, instead relying on concentrating on its core advertised features like basic routing and letting native implementations be the preferred approach versus providing for bridged solutions

**Comment by grahammendick** [comment]
That’s great to hear! 

The React Router doesn’t even have stack navigation so you did well to avoid it. Nobody should go near it.

Thanks for working with me throughout your investigation. Best of luck with your app. If you find any issues or have any suggestions of improvements, then please let me know.

**Comment by grahammendick** [comment]
I've just released navigation-react-native v5.5.0. You can now replace the first child of a scene without any problem! Thanks for raising the issue

**Comment by arunmenon1975** [comment]
> You must move the `MenuProvider` inside your scene. Its name is confusing. It isn't like a `ReduxProvider` because it [renders UI elements](https://github.com/instea/react-native-popup-menu/blob/56bf1f0430add3609c9079e5356c7a813df7e760/src/MenuProvider.js#L218).
> 
> ```js-jsx
> const Welcome = props => (<View style={{flex:1}}> 
> <MenuProvider
>   <Menu
>     renderer={renderers.SlideInMenu}
>     onSelect={value => alert(`Selected number: ${value}`)}>
>     <MenuTrigger text='Select option'/>
>     <MenuOptions>
>       <MenuOption value={1} text='One'/>
>       <MenuOption value={2}>
>         <Text style={{ color: 'red'}}> 
>           Two
>         </Text>
>       </MenuOption>
>       <MenuOption value={3} disabled={true} text='Three'/>
>     </MenuOptions>
>   </Menu> 
> </MenuProvider
> </View>);
> ```

And now with [v6](https://github.com/grahammendick/navigation/releases/tag/v6.0.0-NavigationReactNative) - and perhaps even from v5.5.0, which i missed - i can now have a single `MenuProvider`  instead of wrapping each scenes with it. Earlier i had to hive of the addition of the provider for `IoS`(which worked without any issues using a single provider wrapper) and `Android` (wrap each unique scene with a provider).

Thanks for the updates.

**Comment by grahammendick** [comment]
Well remembered. That's definitely worth trying again. Let me know the outcome

**Comment by arunmenon1975** [comment]
I did try again. Works perfectly well without needing to have multiple providers for each scene on Android. So basically there is no longer any need for any platform-specific changes.

**Comment by grahammendick** [comment]
That's great!
You hinted a while back that you had some ideas about how to make the Navigation router better. Please send them my way when you have the spare time

**Comment by arunmenon1975** [comment]
I definitely will. Currently i am re-architecting my (rather verbose/code-heavy)app to use `React Hooks` - first attempt at it - and `Typescript`(first official attempt).  This is after attempting to change the structure to [`re-ducks`](https://medium.com/better-programming/scaling-your-redux-app-with-ducks-6115955638be), an enhanced `duck` pattern. Using hooks may sort of nullify the need for adhering to a strict duck pattern, and i am still figuring out an optimal approach.  

There are a few expected and unexpected stumbling blocks and am currently prioritising fixing these issues. Including the current urgent need to to integrate `Crashlytics` and/or `Flipper` since the app crashes inexplicably at odd times and so far haven't found the reason why. My current guess is that its inefficient use of one or more `useEffect` hooks. And the all important reason why `auth` requests to Firebase isn't just completing as it did just a few days ago.

Will send PRs/ideas for consideration as soon as the big issues are done with. As of now i suspect it may be Android-only but with some more thought, maybe cross-platform. 

[Incidentally, the inspiration to move to hooks and typescript came courtesy reading the Navigation Router source and examples]
