### ISSUE TITLE
Can't navigate to the third screen.

### ISSUE THREAD

**Issue by SatyaFariz** [grahammendick/navigation#275]
I'm stuck in second screen. For example from Screen A -> Screen B -> Screen C, I can only reach Screen B. Once in Screen B the navigation won't work anymore.

I can't even push the same screen to the stack. for example from Screen A -> Screen B -> Screen B.

**Comment by grahammendick** [comment]
Make sure you set `trackCrumbTrail` to true on Screens B **and** C
```js
var stateNavigator = new StateNavigator([
  {key: 'ScreenA'},
  {key: 'ScreenB', trackCrumbTrail: true},
  {key: 'ScreenC', trackCrumbTrail: true}
]);
```
The [Twitter Example](https://github.com/grahammendick/navigation/tree/master/NavigationReactNative/sample/twitter) is a good one to look at. You can navigate from Home to Timeline to Tweet, for example.

**Comment by SatyaFariz** [comment]
I have. I'm sure everything is correct. But I'm confused why it's not working. I can only ```stateNavigator.navigateBack(1)``` from Screen B. I can't navigate anywhere else. It's super weird.

**Comment by grahammendick** [comment]
Have you debugged it? Do you get an error? I need more info to help you

**Comment by SatyaFariz** [comment]
I have debugged it. It doesn't even produce any errors which makes it even harder to debug it. 

this is my navigate function
```javascript
const navigate = () => {
  
  stateNavigator.navigate('screenC') // nothing happens as if the code is not executed.

  // if the line above is replaced with the line below everything is working fine (but I need to 
  // press the button twice which is super weird)
  // stateNavigator.navigateBack(1)
    
  // this line everything is ok
  console.log(stateNavigator)
}
```

**Comment by grahammendick** [comment]
Have you put a breakpoint in ScreenC render method?

**Comment by SatyaFariz** [comment]
Screen C is actually ok because if I go from Screen A to Screen C everything is working fine.
For example in my App from Home (Screen A) -> Product Detail (Screen C)
```javascript
  const navigate = () => {
  // assuming we are from Home -> Search (Screen B) -> Product Detail with product id = 2
  const { productID } = props.product
  stateNavigator.navigate('productDetail', { productID: productID }) // nothing happens

  //but if we go directly from Home -> Product Detail with the same product id 
  //which in this case is 2,
  //everything is working fine.

  console.log(productID) // 2
}
```

**Comment by grahammendick** [comment]
You should put a breakpoint in ScreenC.
If it doesn't reach your breakpoint then maybe you're not passing a product id?

**Comment by SatyaFariz** [comment]
If that's the case why navigating to a screen that doesn't need parameters doesn't work either?

**Comment by grahammendick** [comment]
Did it hit your breakpoint in ScreenC?

**Comment by SatyaFariz** [comment]
I still don't have any experience debugging with breakpoint with VS Code. I just use console.log

**Comment by grahammendick** [comment]
You can [debug React Native with Chrome Developer Tools](https://facebook.github.io/react-native/docs/debugging#chrome-developer-tools)

**Comment by SatyaFariz** [comment]
Ok I'll check that out later.
But even when Screen C (test screen) is as simple as 
```
test.renderScene = () => (
  <View>
    <Text>TEST</Text>
  </View>
)```

I can't navigate to that screen if it's not from home screen (Screen A). I don't know why.

**Comment by SatyaFariz** [comment]
I have put a breakpoint in render method of Screen C and that doesn't pause the script.

**Comment by grahammendick** [comment]
Add a navigation listener with a breakpoint and see if it hits the listener
```js
stateNavigator.onNavigate((_, state) => {
  console.log(state);
})
```

**Comment by SatyaFariz** [comment]
Yes, it hits the listener.

**Comment by grahammendick** [comment]
Ok, what's the value of `state.key`?
```js
stateNavigator.onNavigate((_, state) => {
  console.log(state.key);
})
```

**Comment by SatyaFariz** [comment]
The value of ```state.key``` is ```productDetail``` which is Product Detail Screen but the app stays in ```search``` screen

**Comment by grahammendick** [comment]
Can you show me the code with your `renderScene` functions (App.js)?

**Comment by SatyaFariz** [comment]
<img width="474" alt="Capture" src="https://user-images.githubusercontent.com/25284201/62427136-a2352200-b718-11e9-8b40-36f811987009.PNG">

<img width="509" alt="Capture2" src="https://user-images.githubusercontent.com/25284201/62427159-f213e900-b718-11e9-9662-d454e6ed98c7.PNG">

**Comment by grahammendick** [comment]
My bad! Thanks for working through this with me. I introduced the problem in navigation-react-native v5.4.0. I hope to have a fix out shortly. In the meantime you can go back to v5.3.1.

**Comment by SatyaFariz** [comment]
Are you sure the problem is only in v5.4.0 ?
As far as I remember I encountered this bug in v5.3.1. But upgrading to the latest version and then downgrading to v5.0.0 doesn't fix the problem.

**Comment by grahammendick** [comment]
I'm very sure. Make sure you terminate the running app and re-run 'react-native run-android'

**Comment by grahammendick** [comment]
New navigation-react-native v.5.4.1 is out. Thanks again for raising the issue

**Comment by SatyaFariz** [comment]
Hey I just uninstalled the app and then upgraded to v5.4.1 and reinstalled the app again but the problem still persists.

**Comment by grahammendick** [comment]
What do you mean by 'uninstalled the app'?

**Comment by SatyaFariz** [comment]
I uninstall the app just to make sure I use the latest build. And the problem still persists

**Comment by grahammendick** [comment]
If you change the `renderScene` as follows then does it log out 'hello'?
```jsx
productDetail.renderScene = (variables) => (
  console.log('hello') || <ProductDetailScreen {...variables} />
)
```

**Comment by SatyaFariz** [comment]
Yes it prints 'hello' on the console but screen stays in search screen

**Comment by grahammendick** [comment]
I'm confident that 5.4.1 fixes the issue. Can you make sure you kill the Metro Bundler process - find the terminal window and type ctrl+c (you should see "Process completed" printed in the terminal window)

**Comment by SatyaFariz** [comment]
Do you mean I should type ```ctrl + c``` in here ? I can't kill the process using ```ctrl + c``` in here.

<img width="465" alt="Capture3" src="https://user-images.githubusercontent.com/25284201/62428258-c77e5c00-b729-11e9-8c6d-e09b478d3262.PNG">

If I'm using windows terminal to run ```react-native start``` typing ```ctrl + c``` will terminate the process and I don't see 'Process completed'

<img width="556" alt="Capture4" src="https://user-images.githubusercontent.com/25284201/62428329-aec27600-b72a-11e9-9ba7-e20899ecae04.PNG">

**Comment by grahammendick** [comment]
Not sure about windows. Close the command window to make sure and then open a new one and run 'react-native run-android'

**Comment by SatyaFariz** [comment]
The problem's still there.

**Comment by grahammendick** [comment]
We're going to have to do some android debugging. Can you open up the android project in Visual Studio and debug it from within there. Are you comfortable doing that? I'll tell you where to put the breakpoints

**Comment by SatyaFariz** [comment]
Ok but maybe tomorrow because it's already 3 am in the morning here and I have to go to sleep.

**Comment by grahammendick** [comment]
No worries. Tomorrow is good. You get some sleep

**Comment by grahammendick** [comment]
Open the android project in Android Studio. After it's built you should see the navigation-react-native project folder on the left. Expand this and the java and com.navigation.reactnative folders within. Open the NaivgationStackManager file and put a breakpoint in the empty setUrl method. Is this breakpoint hit? It should be hit each time you navigate

![image](https://user-images.githubusercontent.com/1761227/62428681-0f868a00-b6fc-11e9-95f7-fe7bfe1d622c.png)

**Comment by SatyaFariz** [comment]
Hey the bug's gone after I restarted my computer.

**Comment by grahammendick** [comment]
That's good news. I was convinced that v5.4.1 fixed the problem
