### ISSUE TITLE
Additional features to TabBarIOS/TabBarItemIOS

### ISSUE THREAD

**Issue by arunmenon1975** [grahammendick/navigation#281]
The app that i am developing has Tabs as the primary navigation artefact. I am using 
 `TabBarIOS` and `TabBarItemIOS` from the `Navigation React Native` router. Everything works fine from the tab functionality perspective but for two issues, one of which is UX related and the other is more of a project convenience than a requirement.
 
1) How do i add badges to the tab items (a big UX plus and also present in my wireframes). In addition, and it just struck me now, how do i style the tabitems/tabbar? The style prop doesn't seem to work.
2) Use of vector icons in place of images for the icons 
 
While definitely not a showstopper since functionally everything works fine, I decided to roll-up my sleeves and try and modify the sources to see if i could to get at least the badge going(AFAIK even React Native Navigation uses images and/or i may need to go the `getImageSource` route) . I have to dip my toes at some point and this seemed a good enough usecase.

For issue 1, I made the following changes but i seem to be missing something since it just doesn't seem to work (there are no errors, however):

My tab file:

```
<TabBarItemIOS  badgeColor="red" badge="123" title="Menu">
       ......
</TabBarItemIOS>
```

In 'navigation.react.native.d.ts':
   ```
...
    badge?: string;
    badgeColor?: string;
...
```

In 'navigation.react.native.js':
 ```
 ...
    var title = _a.title, badge=_a.badge, badgeColor=_a.badgeColor, image = _a.image, systemItem = _a.systemItem, onPress = _a.onPress, children = _a.children;
    console.log({ title: title, image: image, badge: badge, badgeColor: badgeColor, systemItem: systemItem,}) // everything except title and onPress is undefined
    return (React.createElement(NVTabBarItem, { title: title, image: image, badge: badge, badgeColor: badgeColor, systemItem: systemItem, onPress: function (event) {
            event.stopPropagation();
            if (onPress)
                onPress(event);
        } }, children));
...
```

In 'NVTabBarItemManager.m':
 ```
 ...
    RCT_EXPORT_VIEW_PROPERTY(badge, NSString)
    RCT_EXPORT_VIEW_PROPERTY(badgeValue, UIColor)
...
```

In 'NVTabBarItemView.m':
 ```
 ...
- (void)setBadge:(NSString *)badge
{
    self.tab.badgeValue = badge;
}
- (void)setBadgeColor:(UIColor *)badgeColor
{
    self.tab.badgeColor = badgeColor;
}
...
``` 

I am not sure what i am missing since everything looks straightforward.

**Comment by grahammendick** [comment]
Great to see you’re adding a badge to the `TabBarItems`. Thanks!

Looks like you’re on the right track. You shouldn’t directly edit ‘navigation.react.native.js’ because that’s a build artefact. Instead you edit the [TabBarItemIOS](https://github.com/grahammendick/navigation/blob/master/NavigationReactNative/src/TabBarItemIOS.tsx) component file in the project. Then run `npm run package` from the top level project folder. This generates a ‘navigation-react-native’ package in the `build/npm` folder. Copy this into your ‘node_modules’ folder and re-run `react-native run-ios` to see how it looks.

I just merged a [PR from mpiannucci that styles the TabBarIOS component](https://github.com/grahammendick/navigation/pull/263/files) so that should help you (ignore the `NavigationBarIOS` component changes)

**Comment by arunmenon1975** [comment]
Ok, thanks for the suggestions. Let me have a go at it and I will update back here.

**Comment by arunmenon1975** [comment]
I got it to work! 
 
I see the default badge appear and am able to change the styling via the already available `TabBarIOS` props:
```
<TabBarIOS selectedTintColor="orange" unselectedTintColor="yellow" barTintColor="blue">
       <TabBarItemIOS onPress={()=>this.setState({title:"Menu"})} badge="123" badgeColor="red"  title="Menu" ...> 
....
```
Thanks for the pointers. I think i can now dip a little more than the toes, at least for basic changes. 

For issue 2, i think i just might have to use `getImageSource` and preload the image assets for iOS. I am trying to cut down on the final app size so didn't want to attach a ton of images (there are some scenarios where the user can choose from a preset set of icons for an admin-related functionality) and thus preferred the vector icon approach. Since the tab functions and icons are more or less final and wont be changing much, i may just need to load up around 5-10 images and possibly just for iOS.

**Comment by grahammendick** [comment]
Great! Are you planning on opening a PR? I'd like to merge your badge changes in.

**Comment by arunmenon1975** [comment]
> Great! Are you planning on opening a PR? I'd like to merge your badge changes in.

I will submit the PR later this evening. 

_[Btw, sorry for the issue title changes that happened earlier today. I never thought i might actually have a situation where a cat actually ran over the keyboard - managing to hit the Edit button, typing in random values AND Submit . Have at times used this as an analogy/context in UX discussions and the need for additional user validation in form-related design]_
