### ISSUE TITLE
Android keyboard events not working

### ISSUE THREAD

**Issue by SatyaFariz** [grahammendick/navigation#293]
I'm not sure if it's a problem with this library but when I replace ```App.js``` to not use this library the keyboard event is working again.

**Comment by grahammendick** [comment]
Thanks for reporting. It looks like a Navigation router bug.

**Comment by grahammendick** [comment]
The plan is to copy over the [`GlobalLayoutListener`](https://github.com/facebook/react-native/blob/8e04a1485f377e2d7d744fe74fc26e1dd0c056fc/ReactAndroid/src/main/java/com/facebook/react/ReactRootView.java#L628) from `ReactRootView` into `SceneView`.  Initial results look promising but I've got more testing to do before I can be confident it works
