### ISSUE TITLE
Gestures with react-native-gesture-handler not working

### ISSUE THREAD

**Issue by SatyaFariz** [grahammendick/navigation#299]
I have react-native-tab-view and react-native-reanimated-bottom-sheet in my project. The swipe gestures in both libraries does not work.

**Comment by SatyaFariz** [comment]
Ah I see.

**Comment by grahammendick** [comment]
I'm making the Navigation router work with fragments in the [fragment-stack branch](https://github.com/grahammendick/navigation/tree/fragment-stack)

**Comment by SatyaFariz** [comment]
For the time being, I created a custom native BottomSheetBehavior with the code taken from [here](https://github.com/cesardeazevedo/react-native-bottom-sheet-behavior). The components work well however I can't press any buttons inside the bottom sheet if used with this lib. Is there any specific rules that I have to follow in order to create custom native components that works well with this library ?


![bottom_sheet](https://user-images.githubusercontent.com/25284201/65015188-fe5fa880-d94a-11e9-867a-dda654806146.gif)

**Comment by grahammendick** [comment]
Can you debug to find out why they're not clickable, please? Is there a Java Exception when you click them?

**Comment by SatyaFariz** [comment]
I have not worked with Java very often. I don't know how to debug java, especially in React Native.
There are no Java Exception when I click them. When I ```console.log``` the message doesn't show up in Chrome debugger. Nothing happened as if there's no buttons or other clickable components.

**Comment by grahammendick** [comment]
Does your BottomSheet code work outside of the Navigation router (in a clean react native project)?

**Comment by SatyaFariz** [comment]
Yes It works outside of the navigation router. 
The only thing that's clickable inside the navigation router is the FAB. Is it related to Java Activity or something?


![bottom_sheet_pink](https://user-images.githubusercontent.com/25284201/65023502-26580780-d95d-11e9-99f8-837611102b21.gif)

**Comment by grahammendick** [comment]
Some components expect to be loaded inside React Native's MainActivity. The Navigation router starts each scene in a new Activity. It could be that?

**Comment by SatyaFariz** [comment]
Yeah I thought so. But since I'm not very experienced with Java I just copy paste the code and don't know where the problem is.

**Comment by grahammendick** [comment]
To debug your React Native project in Android Studio:

1. Open the android folder of your React Native project in Android Studio
2. Run `react-native start`
3. Press debug from within Android Studio.

**Comment by grahammendick** [comment]
I’m happy with `fragment-stack` branch. Could you test it out and see if it fixes the swipe gesture problem you started out with. To test it you need to be using React Native v0.60 or later and follow these steps

1. Clone the project
2. Switch to the `fragment-stack` branch
3. Run `npm install` at the top level navigation folder
4. Run `npm run package`
5. Copy the `navigation-react-native` folder from the `build/npm` folder into the `node_modules` folder of your app

It should also fix your status bar issue #300, too

**Comment by SatyaFariz** [comment]
The StatusBar and ```react-native-gesture-handler``` bug is fixed but as you can see the ```navigate``` function is not fired inside of the bottom sheet if the button is not pressed long enough. Also the animation is janky and weird when the ```fragmentMode``` is true.

As for my custom native bottom sheet, I tried it in a different screen from the previous one, it's actually working. I can click any buttons inside the content of the bottom sheet (even when the ```fragmentMode``` is false). I don't know why it was not working, maybe because of how the views were structured.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25284201/65132177-badc6b80-da2a-11e9-914f-da7e31571499.gif)

**Comment by grahammendick** [comment]
Thanks for testing it. I'm going to close this and the #300 when I merge the `fragment-stack` branch. 

Regarding the janky animation. That's probably due to your custom animations. You need to make sure that when you animates a scene out, you start it from the right place when you animate it back in. Have a look at the [animations in the medley sample](https://github.com/grahammendick/navigation/tree/master/NavigationReactNative/sample/medley).  Fragments are a bit fussier than Activities

**Comment by SatyaFariz** [comment]
What do you mean by custom animations? I don't create any custom animations. I just use the default animations.

**Comment by grahammendick** [comment]
Aren't you using the `mountStyle` (and `crumbStyle`) props on the `NavigationStack`?

**Comment by SatyaFariz** [comment]
No. I don't pass any of those props to ```NavigationStack```. The animations are janky when ```fragmentMode``` is true on the ```NavigationStack``` and become smooth again when I pass fragmentMode=false to ```NavigationStack```

**Comment by grahammendick** [comment]
Could you run the redux sample in the fragment-stack branch and see what the animations look like, please? You'll have to copy the navigation-react-native folder from build/nom into node_modules after you nom install

**Comment by grahammendick** [comment]
Don't worry. I see the problem. I got my  [enter and exit the wrong way round](https://github.com/grahammendick/navigation/blob/609f9068404639fa763cb38c205d40a0d215aa39/NavigationReactNative/src/android/app/src/main/java/com/navigation/reactnative/FragmentNavigator.java#L42). Thanks for flagging the issue

**Comment by grahammendick** [comment]
Can you retest with the latest fragment-stack branch and let me know if the animations are working fine, please?

**Comment by grahammendick** [comment]
I released navigation-react-native v6.0.0. Please upgrade and let me know how you get on. Thanks for your help testing it
