### ISSUE TITLE
Questions regarding nested NavigationStack

### ISSUE THREAD

**Issue by SatyaFariz** [grahammendick/navigation#303]
v6.0.0 release comes with nested ```NavigationStack``` components support. I'm wondering if it can be used to create tab based navigation because I'm not happy with ```BottomNavigation``` from ```react-native-paper``` because it is rather slow on Android and has flickering issue. Can you provide a sample app on how to use it, please?

**Comment by grahammendick** [comment]
If you’re looking for an alternative to `BottomNavigation` why not try [ViewPagerAnroid](https://facebook.github.io/react-native/docs/viewpagerandroid)?

Yes, nested `NavigationStacks` does make it possible to create an Android `TabBar` component. I plan to implement it by using the [FragmentPagerAdapter](https://developer.android.com/reference/android/support/v4/app/FragmentPagerAdapter).

**Comment by SatyaFariz** [comment]
I've tried using ```ViewPagerAndroid``` but it has a slight delay when I used ```setPageWithoutAnimation``` when the destination page index is quite distant from the current page index.

Would be so great if you open source a native version of ```BottomNavigation```.

**Comment by grahammendick** [comment]
The Navigation router currently has a `TabBarIOS` component. My plan is to change this to a `TabBar` component that works on both platforms. On iOS, it uses the native `UITabBarController` API under the covers. On Android, it will use the native `FragmentPageAdapter` API so it will adopt the UX of a ViewPager. 

If this sounds like something you'd like to implement then let me know.

**Comment by SatyaFariz** [comment]
Yes, I can't wait until this functionality can be implemented on Android.

**Comment by grahammendick** [comment]
Cool. Do you want to build it?

**Comment by SatyaFariz** [comment]
Currently I have no idea how to implement it and also I have my own start up project that I have to finish.

**Comment by grahammendick** [comment]
No problem, If you change your mind then let me know. I'll provide plenty of guidance so don't worry about that at all

**Comment by SatyaFariz** [comment]
Do you have a plan to build it yourself any time soon?

**Comment by grahammendick** [comment]
Not very soon, but soonish

**Comment by SatyaFariz** [comment]
Ah I see. No problem. I'll stick with the current ```BottomNavigation``` from ```react-native-paper``` for the moment.

**Comment by grahammendick** [comment]
I did it sooner than I thought! I've just released a new `TabBar` component that works on Android and iOS. It uses the `ViewPager` on Android and the `UITabBarController` on iOS. You can try it out in `navigation-react-native` v6.1.0
