### ISSUE TITLE
Working locally documentation?

### ISSUE THREAD

**Issue by drewhamlett** [grahammendick/navigation#305]
I'd like to put in a few PR's, just wondering the best way to iterate locally with one of the sample projects and the local repo code?

**Comment by grahammendick** [comment]
PR’s makes me happy!  Run `npm install` from the top level project folder to install the build dependencies. After making your code changes, run `npm run package`. This generates a `navigation-react-native` folder inside the `build/npm` folder. Copy this `navigation-react-native` folder into the `node_modules` of any of the [samples](https://github.com/grahammendick/navigation/tree/master/NavigationReactNative/sample) and you’re good to go.

**Comment by grahammendick** [comment]
@drewhamlett Are you happy with the instructions?

**Comment by drewhamlett** [comment]
Yes thank you so much!
