### ISSUE TITLE
Fragment Navigator is slow when there is autoFocus TextInput in the destination screen.

### ISSUE THREAD

**Issue by SatyaFariz** [grahammendick/navigation#310]
When I navigate from screen A -> B and there is ```autoFocus``` TextInput (appearing keyboard) in screen B, the animation is janky. If I remove the ```autoFocus``` then the animation becomes smooth again. This is not happening with Activity Navigator.

**Comment by grahammendick** [comment]
I just [set autofocus to true in the redux sample](https://github.com/grahammendick/navigation/commit/7d78c28980614ec3197a3a3451dcc5a02e52e079). The navigation seems to work fine. Can you try out the redux sample and see if it works ok for you, please?

**Comment by SatyaFariz** [comment]
Ok I'll try that later. I guess it's phone-specific. I'm using a rather old Android phone. The difference is very noticeable on my phone.

**Comment by SatyaFariz** [comment]
Is Fragment Navigation inherently slower than Activity Navigation? Because I found out that if I have a ```CameraView``` from [react-native-camera](https://github.com/react-native-community/react-native-camera) in Screen B, the animation becomes very laggy that it doesn't even have transition. While if I set ```fragmentMode``` to false (Activity Navigation) the animation is still very smooth.

**Comment by grahammendick** [comment]
Are you saying it's nothing to do with the autoFocus prop? Could you show me what your screen B looks like, please?

**Comment by SatyaFariz** [comment]
Looks like it has nothing to do with autoFocus prop. I also notice frame drops when I have a very heavy, complex layout in my screen.
This is actually the code that I'm testing with ```react-native-camera```. Very simple layout but enough to cause the animation to drop (not happening if I set fragmentMode to false). The difference between Fragment Navigation and Activity Navigation is very obvious in terms of smoothness, at least on my phone.

```javascript
import React, { useRef } from 'react'
import { View, StyleSheet } from 'react-native'
import { RNCamera } from 'react-native-camera'

const Component = props => {
  const cameraRef = useRef()

  const barcodeRecognized = ({ barcodes }) => {
    barcodes.forEach(barcode => console.warn(barcode.data))
  }

  return (
    <View style={s.container}>
      <RNCamera
        ref={cameraRef}
        style={s.camera}
        captureAudio={false}
        onGoogleVisionBarcodesDetected={barcodeRecognized}
      >
      </RNCamera>
    </View>
  )
}

const s = StyleSheet.create({
  container: {
    flex: 1
  },
  camera: {
    flex: 1,
    width: '100%'
  }
})

export default Component
```

**Comment by grahammendick** [comment]
Thanks for posting the code. Can you explain your use-case in more detail. Why do you want to navigate to the camera scene? Why not show the camera using a button click or slide in the camera using a  [ViewPager](https://github.com/react-native-community/react-native-viewpager), for example?

**Comment by SatyaFariz** [comment]
I want to navigate to camera scene because I have QR code scan functionality. Of course I can use ViewPager for this use case but the problem is I also have several other screens with slow navigation animation, especially those with autoFocus prop.

**Comment by grahammendick** [comment]
> Looks like it has nothing to do with autoFocus prop.

I'm confused. Are you now saying that the autoFocus prop is a problem? Did you try the redux sample like I asked? This has an autoFocus prop and the navigation works fine

**Comment by SatyaFariz** [comment]
I'm not sure, I think it (the appearing keyboard) might be one of the things that causes the problem. 

I haven't tried the redux sample yet. I will report to you once I have tried it.

**Comment by grahammendick** [comment]
I'm going to close this because it's too vague at the moment. I'm not convinced that navigating to a new camera screen is a valid use-case and the autofocus works in the redux sample. I'm happy to reopen it if you provide more information.
