### ISSUE TITLE
Question: How to navigate in nested navigators?

### ISSUE THREAD

**Issue by melkayam92** [grahammendick/navigation#313]
For example, I have this config:

```
const secondNavigator = new StateNavigator([
  { key: 'ScreenOne', trackCrumbTrail: true },
  { key: 'ScreenTwo', trackCrumbTrail: true },
]);

const { ScreenOne, ScreenTwo } = secondNavigator.states;

ScreenOne.renderScene = () => <ScreenOneComp />;
ScreenTwo.renderScene = () => <ScreenTwoComp />;


const stateNavigator = new StateNavigator([
  { key: 'MainApp', trackCrumbTrail: true },
  { key: 'nestedApp', trackCrumbTrail: true },
]);

const { MainApp, nestedApp } = stateNavigator.states;

MainApp.renderScene = () => <MainAppComp />;
nestedApp.renderScene = () => (
 <NavigationHandler stateNavigator={secondNavigator}>
    <NavigationStack />
  </NavigationHandler>
);


export default () => (
<NavigationHandler stateNavigator={stateNavigator}>
    <NavigationStack />
  </NavigationHandler>
);

```

When I navigate to the nested navigator and press back - I get an error that there is nowhere to return to, because in the new navigator the state is empty (and it doesn't have access to the main navigator?)

I guess I don't completely understand how the navigator works that why it happens. 

Thanks!

**Comment by grahammendick** [comment]
Thanks for your PR by the way. I really appreciate it!

Could you explain your use-case, please, because I don't think you need to nest navigators. I think almost all navigation patterns can be handled with just a single navigator.

**Comment by melkayam92** [comment]
Sure no problem!

For example, I need some screens with animations and some without. 

So I thought to create the main navigator for the 'BIG' screens that I don't want to animate, and for the rest, I will create an inner navigator with animation included. (slide up/down).

There is another way to achieve that?

**Comment by grahammendick** [comment]
Yes, you can do that with a single navigator. Take a look at the [custom animation doc](https://grahammendick.github.io/navigation/documentation/native/custom-animation.html). You decide how screens animate using the `unmountStyle` and `crumbStyle` props.

If you want to see it in action then take a look at the medley sample where each screen has a [different animation](https://github.com/grahammendick/navigation/blob/7d78c28980614ec3197a3a3451dcc5a02e52e079/NavigationReactNative/sample/medley/App.js#L20).

**Comment by melkayam92** [comment]
That's great!

Thanks for this amazing library!

If you need any help in implementing staff I will gladly help.

**Comment by melkayam92** [comment]
@grahammendick Another question:

On android I don't get the  "free" header, I don't mind creating it React - that's the way to do it?

The other PR I see there with the ToolBarAndroid that's the header for android?

**Comment by grahammendick** [comment]
I'm really glad you like the Navigation router and thanks for you generous offer of help. I'm sure i'll take you up on that!

Yes, that PR is adding the header on Android.

**Comment by grahammendick** [comment]
Just so that I know, what kind of stuff do you like working on? Android, iOS or React or all three?

**Comment by melkayam92** [comment]
Android and React better, ios less.
