### ISSUE TITLE
How to track screen focus ?

### ISSUE THREAD

**Issue by SatyaFariz** [grahammendick/navigation#318]
When navigating from screen A -> B, screen A is not unmounted. But the focus changes from screen A to screen B. When we go back to screen A from screen B, screen B is unmounted and the focus changes from screen B to screen A. In my use case I need to track screen focus and save it in a state. With [react-navigation](https://reactnavigation.org/docs/en/function-after-focusing-screen.html), I can use the ```didFocus``` event. How to do this in navigation router?

**Comment by grahammendick** [comment]
You can track when a screen is active by listening to navigation events. This code doesn't even need to be inside a component. You can add it just after you create the `stateNavigator`
```js
stateNavigator.onNavigate((oldState, state, data) => {
  //Logs out the current active state
  console.log(state.key);
});
```

**Comment by SatyaFariz** [comment]
If I use it inside ```componentDidMount```, how do I unsubscribe from it?

**Comment by grahammendick** [comment]
Pass your handler into ```stateNavigation.offNavigate``` in `componentWillUnmount`

**Comment by SatyaFariz** [comment]
like this ?

```javascript
componentDidMount() {
    const { stateNavigator } = this.context
    this.screenFocusListener = stateNavigator.onNavigate((oldState, state, data) => {
      //Logs out the current active state
      console.warn(state.key)
    })
}

componentWillUnmount() {
    const { stateNavigator } = this.context
    stateNavigator.offNavigate(this.screenFocusListener)
}
```

**Comment by grahammendick** [comment]
Nope, like this
```js
screenFocusListener(oldState, state, data) {
    //Logs out the current active state
    console.warn(state.key)
}
componentDidMount() {
    const { stateNavigator } = this.context
    stateNavigator.onNavigate(this.screenFocusListener)
}

componentWillUnmount() {
    const { stateNavigator } = this.context
    stateNavigator.offNavigate(this.screenFocusListener)
}
```

**Comment by SatyaFariz** [comment]
Ah I see. thanks.
