### ISSUE TITLE
Set Back Button Text on iOS

### ISSUE THREAD

**Issue by mpiannucci** [grahammendick/navigation#326]
Is there a way to set the back button text for the navbar? A lot of times I dont want the title of the last screen, EG: 
<img width="410" alt="Screen Shot 2019-11-10 at 8 03 44 PM" src="https://user-images.githubusercontent.com/1832671/68554248-363c1700-03f5-11ea-8b52-eec84af0692a.png">

**Comment by grahammendick** [comment]
Not at the moment but I'd welcome a PR if you're interested?

**Comment by mpiannucci** [comment]
Yeah I played with it and theres a few different ways for the API to look. In iOS the back button uses title of the previous view by default. In order to change it the easiest way is to change the title text to your desired back button text just before navigating. You can also set the back button in the same place instead of changing the title. Changing the back button in destination view does not work.  

Where the API choice comes in is that in my mind it makes sense to have the back button text as a prop for the destination view. But that makes things tricky becasue we would have to reach down through the NVSceneController to get to it right? The alternative is to have backButton as a prop in the presenting controller instead> I dont care either way but I wanted to know if you had a preference.

**Comment by grahammendick** [comment]
We can change the back button title in the destination view by setting the backBarButtonItem in the **previous** navigation item:
```objective-c
UINavigationItem *prevItem = [self.reactViewController.navigationController.viewControllers objectAtIndex:crumb - 1].navigationItem; 
prevItem.backBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:backTitle];
```

**Comment by mpiannucci** [comment]
Oh yeah thats much cleaner haha Glad I asked for your input.
