### ISSUE TITLE
Bar Button Tint on Android

### ISSUE THREAD

**Issue by mpiannucci** [grahammendick/navigation#329]
The tint prop of the navbar is not applied to items in the Native Android toolbar component.

**Comment by grahammendick** [comment]
We did [discuss the tintColor](https://github.com/grahammendick/navigation/pull/311#issuecomment-544257001) in the "Navigation Bar on Android" PR. The problem is that we couldn't find a way to programmatically change the background color of the overflow menu. So what's the point of changing the color of the menu items via a tintColor prop if you can't change the background color with a prop, too? 

The only way to change the background color of the menu is via the styles.xml file. So we thought it made sense to change the menu item color there too. I'm happy to revisit this decision so please let me know what you think.

**Comment by mpiannucci** [comment]
Yeah my thought was using styles.xml too cuz I use ui appearance on iOS. But I couldn’t get the me to apply to the toolbar from the navigation router. Any tips there? Otherwise I’ll just keep messing with it until I figure it out lol

**Comment by grahammendick** [comment]
I'm not convinced of the benefit of using props to style the `NavigationBar`. Is that why you decided to use ui appearance on iOS? Perhaps the new navigation bar styling in iOS 13 could help?

Here's a menu with a red background and white text.
```xml
<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="android:textColor">#000000</item>
    <item name="android:itemTextAppearance">@style/myCustomMenuTextAppearance</item>
    <item name="android:itemBackground">#f00</item>
</style>
<style name="myCustomMenuTextAppearance" parent="@android:style/TextAppearance.Widget.IconMenu.Item">
    <item name="android:textColor">#fff</item>
</style>
```

**Comment by grahammendick** [comment]
You can also change the color of the menu items on the toolbar (not on the overflow menu)
```xml
<item name="android:actionMenuTextColor">#f00</item>
```

**Comment by mpiannucci** [comment]
Thanks, I tried a few different variables so I will give those a try. 

As for the props being useful, for me they are. My workflow is basically that I theme the app using uiappearance in the AppDelegate then use the props to override the theme on a per screen basiswhen I want to draw attention to something. I dont think the props being available hurts anything, and it provides a quick way to override things as needed.

**Comment by mpiannucci** [comment]
After testing I can change text colors no problem but toolbar icon color cannot be changed. 

So the problem I have is that I am supplying an icon for the Navigation Bar. It is a white icon from the Material Design icon set. Both Android and iOS now allow for dark themes. On iOS this is easy because we just use UIAppearance with the tintColor and the navbar icon colors are updated automatically for dark mode and light mode. On Android with the Navigation Router there is basically no way for me to dynamically change the color of the action icons. 

Its not the end of the world because I can just supply multiple icons in different colors but its far from ideal.

**Comment by grahammendick** [comment]
How does dark theming work on the Android (without React Native)?
Can you describe in more detail what you're doing on iOS to get dark theming to work?

**Comment by mpiannucci** [comment]
iOS is easy. the iOS SDK defines semantic colors that automatically adapt to the current theme, whether it is dark or light. You can also define adaptive colors as assets and use them by name. For example this is what I currently do in my `AppDelegate.m`, where systemBackgroundColor is built into iOS and is black when dark mode is selected and white when not. tintColor is my own color asset. 

```Objc
  [[UINavigationBar appearance] setBarTintColor:[UIColor systemBackgroundColor]];
  [[UINavigationBar appearance] setTintColor:[UIColor colorNamed:@"tintColor"]];
  [[UIBarButtonItem appearance] setTintColor:[UIColor colorNamed:@"tintColor"]];
```

For [android](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme), you just have to make the app theme inherit from `Theme.AppCompat.DayNight`. In my app I have to following because the toolbar is defined using the navigation router. This automatically changes the color of the toolbar background and foreground elements without having to define colors to do so. 

```xml
<style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
...
</style>
```

As far as I know tinting Icons on Android can be done through the theme that is defined in the toolbar XML. You would normally inherit from the light theme or dark theme base and it would take care of the rest I think. But because React Native does not define the toolbar with XML I am actually totally unsure of how it should be done to be honest.

**Comment by grahammendick** [comment]
Sounds like the user can choose the light or dark them on iOS but not on Android. Have I understood that right? How does the user switch between light and dark theme on Android?

**Comment by mpiannucci** [comment]
It is a system option in Android 10. You can just change it in settings, same as iOS.

 I think it is probably a limitation of react native, because normally you could create adaptive icons in Android Studio but here we are injecting the images from javascript. I will just work around the issue for now. 

Sorry for posting so much, really trying to get all the native functionality I would normally have out of this library ahah.

**Comment by grahammendick** [comment]
Thanks for posting. I really appreciate all your questions and suggestions.

**Comment by grahammendick** [comment]
How are you handling other images outside of the navigation bar? Don't you have to load two versions on both iOS and Android?

**Comment by mpiannucci** [comment]
Other images are easy because I can use the `tintColor` prop on `Image` components and do it all from javascript. 

https://facebook.github.io/react-native/docs/image#style

**Comment by grahammendick** [comment]
So should we get the tintColor to work on the NavigationBar images in the same way that it does on the built in image components?

**Comment by mpiannucci** [comment]
Thats probably the best solution

**Comment by grahammendick** [comment]
How do you set the tintColor prop to match up with the dark/light theme the user selects?

**Comment by mpiannucci** [comment]
I have a custom useTheme() hook that uses the useDarkMode() hook from [react-native-dark-mode](https://www.npmjs.com/package/react-native-dark-mode) and returns the colors to use in the app depending on the current dark mode. I then set the tintColor prop using the colors from useTheme()

For native components i try to theme them natively where possible though using the built in methods.
