### ISSUE TITLE
FlatList inside ScrollView Container in order to support large title

### ISSUE THREAD

**Issue by salockhart** [grahammendick/navigation#333]
This is mostly an iOS issue.

I've been using the Grid component in the zoom sample project as an example.

I have a FlatList that I want to render inside a screen that has:
* a big title
* a search bar

To achieve that, I have it wrapped in a ScrollView per the example.

The first thing I receive is a warning:

`VirtualizedLists should never be nested inside plain ScrollViews with the same orientation - use another VirtualizedList-backed container instead`

Replacing the ScrollView container with a FlatList was a no-go, but admittedly I haven't tried much else.

Back to the ScrollView: When I pull to refresh the FlatList, the wrapping ScrollView moves instead, and the refresh is never triggered.

If I attempt to attach the RefreshControl to the container ScrollView, I get some undefined behaviour.

Here's a snippet of what I'm trying out (this is a replacement for the Colors component):

```
const Colors = ({colors, children, filter}) => {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setTimeout(() => setLoading(false), 2000);
  }, [loading]);

  const suffix = filter != null ? '_search' : '';
  const matchedColors = colors.filter(
    color => !filter || color.indexOf(filter.toLowerCase()) !== -1,
  );
  return (
    <NavigationContext.Consumer>
      {({stateNavigator}) => (
        <FlatList
          contentInsetAdjustmentBehavior="automatic"
          data={matchedColors}
          renderItem={({item: color}) => (
            <TouchableHighlight
              key={color}
              style={styles.color}
              underlayColor={color}
              onPress={() => {
                stateNavigator.navigate('detail', {
                  color,
                  name: color + suffix,
                  filter,
                  search: filter != null,
                });
              }}>
              <SharedElement name={color + suffix} style={{flex: 1}}>
                <View style={{backgroundColor: color, flex: 1}} />
              </SharedElement>
            </TouchableHighlight>
          )}
          keyExtractor={item => item}
          onRefresh={() => setLoading(true)}
          refreshing={loading}
        />
      )}
    </NavigationContext.Consumer>
  );
};
```

Is it possible to get the behaviour that I am after?

**Comment by salockhart** [comment]
Looking for a couple of examples, the best case scenario would be to achieve something similar to what can be found in the default iOS Mail app. When viewing an inbox, you can pull to refresh, and the refresh control appears in the navigation bar above the title.

<img width="150" alt="20191118_100244626_iOS" src="https://user-images.githubusercontent.com/6651364/69043376-d6440280-09ea-11ea-821f-de25db69d19c.png">

This may not be feasible, and that's alright. But this is the behaviour I am attempting to emulate.

**Comment by grahammendick** [comment]
Hey, thanks for the interesting question!
On iOS there are two `ScrollViews`. You should attach a [RefreshControl](https://facebook.github.io/react-native/docs/refreshcontrol) to the outer ScrollView.
```jsx
<Container
  style={styles.scene}
  collapsable={false}
  contentInsetAdjustmentBehavior="automatic"
  refreshControl={
    <RefreshControl
      refreshing={loading}
      onRefresh={() => setLoading(true)} />
  }>
  <NavigationBar
    largeTitle={true}
    title="Colors"
    barTintColor={Platform.OS === 'android' ? '#fff' : null}>
```

**Comment by salockhart** [comment]
Neat, I'll give that a try then later. Thanks!

Do you have any thoughts on how to get around the warning above? I want to keep the `FlatList` but continuing to embed it in a `ScrollView` isn't ideal

**Comment by mpiannucci** [comment]
Have you tried adding the NavigationBar as the FlatList header component? I think I used that in the past and it worked. IDK for sure if it still does though.

**Comment by salockhart** [comment]
I gave adding the RefreshControl to the container ScrollView a shot, and while it kinda works it still behaves kind of weird.

![refreshcontrol](https://user-images.githubusercontent.com/6651364/69069851-1a50fa80-0a1f-11ea-9008-b31cf705512c.gif)

However.. looking deeper into this, I wonder if it is a side effect of how RN handles RefreshControl in ScrollView.

https://github.com/facebook/react-native/blob/0f8ad3174592ba3dde08a62d5ef0b58d1a6d5de4/Libraries/Components/ScrollView/ScrollView.js#L1168 shows the RefreshControl being passed as a subview (best guess). In order to get the behaviour I want, I think it would need to be set on the `refreshControl` property directly, instead. See https://stackoverflow.com/a/45359087

All that, and I would still have the issue with the FlatList inside the ScrollView. I also tried adding the NavigationBar to the FlatList as the header component, but no dice.

**Comment by grahammendick** [comment]
Yes, React Native shouldn't add [the refresh control as a subview](https://github.com/facebook/react-native/blob/ca3c8b7a7d6b9056de3585b52c4adcbf8ae1f085/React/Views/ScrollView/RCTScrollView.m#L233). The [iOS documentation covers the scenario you're after](https://developer.apple.com/documentation/uikit/uirefreshcontrol?language=objc). It shows a large title with a search bar and the refresh appears above the title. The code sample attaches the refresh control to the scroll view's `refreshControl` property.

Why not write your own custom native `RefreshControl` component? Add it as a child of the ScrollView but make it take up no space (position absolute with zero height and width) because you don't want it to render anything.  On the native side, inside the `didMoveToWindow` find the ancestor `UIScrollView` by climbing up the view hierarchy. Then create a `UIRefreshControl` and assign it to the `refreshControl` property.

**Comment by salockhart** [comment]
Ah, that's a much better link. I was hoping to avoid writing new native modules for now.. but no time like the present.

Thank you for your help!

**Comment by grahammendick** [comment]
No worries. Let me know if you need any help

**Comment by grahammendick** [comment]
@salockhart did you give this a go? I'm keen to know how it worked out

**Comment by salockhart** [comment]
Hey @grahammendick, I haven't had a chance yet, but I should be able to in the next week or two. I'll let you know how it goes

**Comment by yangm97** [comment]
I guess this is still relevant, could we re-open this issue?

**Comment by grahammendick** [comment]
Looks like [React Native fixed their `RefreshControl`](https://github.com/facebook/react-native/commit/1b0fb9bead4d158d14df5a994423d06716b5e377). They changed their [`ScrollView` to set its `refreshControl` property instead of adding a subview](https://github.com/facebook/react-native/blob/1b0fb9bead4d158d14df5a994423d06716b5e377/React/Views/ScrollView/RCTScrollView.m#L227). It should be working fine now
