### ISSUE TITLE
Setting custom view to BarButton

### ISSUE THREAD

**Issue by emerson233** [grahammendick/navigation#335]
This is easy on iOS by calling `[UIBarButtonItem setCustomView:]`. On Android, it can be done by calling `setActionView` on menu item.
I think it would be helpful to add this feature.
What do you think?

**Comment by grahammendick** [comment]
That's an interesting idea! Can you give me an example use-case and how it would behave on both Android and iOS, please?

**Comment by emerson233** [comment]
Hi, sorry for getting back to you so late. I've been busy these days. Will try to post a demo for this feature some time later.

**Comment by grahammendick** [comment]
I'll close this for now. But don't worry, we can always reopen it and start the discussion around an example use-case
