### ISSUE TITLE
Wrapped BarButton components on Android do not appear

### ISSUE THREAD

**Issue by salockhart** [grahammendick/navigation#338]
I have a search button in the NavigationBar on Android. Because this button displays an image, I want to wrap the BarButton component so that it can handle fetching its own image, and the parent component can just display the button.

Here's the component:
```
import {BarButton} from 'navigation-react-native';
import React, {useEffect, useState} from 'react';
import FontAwesome5 from 'react-native-vector-icons/FontAwesome5';

const SearchBarButton = () => {
  const [image, setImage] = useState(null);

  useEffect(() => {
    FontAwesome5.getImageSource('search', 20).then(setImage);
  }, []);

  return <BarButton title="Search" show="always" search={true} image={image} />;
};

SearchBarButton.prototype = BarButton;

export default SearchBarButton;
```

However, when I attempt to render it:
```
<RightBar>
    <SearchBarButton />
</RightBar>
```
a blank menu appears in the Android nav bar.

The button works just fine if I remove the layer of abstraction:
```
<RightBar>
    <BarButton title="Search" show="always" search={true} image={image} />
</RightBar>
```
---

I have a feeling this is due to how the Android navigation bar works - it doesn't ever render the `BarButton`, it just grabs the props off of it and passes them along:

https://github.com/grahammendick/navigation/blob/033034ddaa6fe6f7d101d1dbe19bfe924bf7fce9/NavigationReactNative/src/NavigationBar.tsx#L13-L24

Since my abstracted component doesn't have any props, nothing gets displayed.

Any tips? The workaround for now of course is to just remove the layer of abstraction, but I would love to be able to wrap BarButtons

**Comment by grahammendick** [comment]
Thanks for the interesting question. I can’t think of a reliable way to accept wrapped `BarButtons` because Android Menus are a bit weird. But a custom React hook works just as well.

```jsx
useFontAwesome5 = name => {
  const [image, setImage] = useState(null);
  useEffect(() => {
    FontAwesome5.getImageSource(name, 20).then(setImage);
  }, []);
  return image;
}

const searchImage = useFontAwesome5('search');
const editImage = useFontAwesome5('edit');
return (
  <RightBar>
    <BarButton show="always" search={true} image={searchImage} />;
    <BarButton show="always" image={editImage} />;
  </RightBar>
);
```

**Comment by salockhart** [comment]
Neat, I figured that would be the case. Thanks for the tip
