### ISSUE TITLE
Several android crashes

### ISSUE THREAD

**Issue by gabrielbull** [grahammendick/navigation#348]
Hey, thanks for the work on this lib. I'm having these crashes when implementing this library on my app.

One of these crashes [(The specified child already has a parent...)](#crash3) is when pressing the back button rapidly after navigating to a new screen.

If you can point me in the right direction, or work with me, I'd be happy to try and fix or help fixing them.

Thanks

### java.lang.IllegalArgumentExceptionFragmentManagerImpl.java:875
No view found for id 0x395 (unknown) for fragment ScreenFragment{502b3b9 (b395f12c-1845-424d-99a9-5f9098274544) id=0x395}

```
java.lang.IllegalArgumentException No view found for id 0x395 (unknown) for fragment ScreenFragment{502b3b9 (b395f12c-1845-424d-99a9-5f9098274544) id=0x395} 
    FragmentManagerImpl.java:875 androidx.fragment.app.FragmentManagerImpl.moveToState
    FragmentManagerImpl.java:2100 androidx.fragment.app.FragmentManagerImpl.addAddedFragments
    FragmentManagerImpl.java:1874 androidx.fragment.app.FragmentManagerImpl.executeOpsTogether
    FragmentManagerImpl.java:1830 androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute
    FragmentManagerImpl.java:1727 androidx.fragment.app.FragmentManagerImpl.execPendingActions
    FragmentManagerImpl.java:150 androidx.fragment.app.FragmentManagerImpl$2.run
    Handler.java:883 android.os.Handler.handleCallback
    Handler.java:100 android.os.Handler.dispatchMessage
    Looper.java:214 android.os.Looper.loop
    ActivityThread.java:7356 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    RuntimeInit.java:492 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
    ZygoteInit.java:930 com.android.internal.os.ZygoteInit.main
```

### ErrorMainActivity
The distance parameter must be greater than zero and less than or equal to the number of Crumbs (0)

```
Error The distance parameter must be greater than zero and less than or equal to the number of Crumbs (0) 
    index.android.bundle:728:20307 getNavigationBackLink
    index.android.bundle:728:20190 navigateBack
    index.android.bundle:727:1408 
    index.android.bundle:461:1047 b
    index.android.bundle:461:477 C
    index.android.bundle:461:825 E
    index.android.bundle:461:1239 goBack
    index.android.bundle:3143:595 
    index.android.bundle:214:2263 touchableHandlePress
    [native code] touchableHandlePress
    index.android.bundle:205:9675 _performSideEffectsForTransition
    [native code] _performSideEffectsForTransition
    index.android.bundle:205:8357 _receiveSignal
    [native code] _receiveSignal
    index.android.bundle:205:5645 touchableHandleResponderRelease
    [native code] touchableHandleResponderRelease
    index.android.bundle:89:1197 b
    index.android.bundle:89:1340 k
    index.android.bundle:89:1394 C
    index.android.bundle:89:1692 N
    index.android.bundle:89:2482 A
    [native code] forEach
    index.android.bundle:89:2282 z
    index.android.bundle:89:13914 
    index.android.bundle:89:88659 _e
    index.android.bundle:89:13582 Ne
    index.android.bundle:89:13755 Ue
    index.android.bundle:89:14547 receiveTouches
    index.android.bundle:25:3685 value
    index.android.bundle:25:841 
    index.android.bundle:25:2939 value
    index.android.bundle:25:813 value
    [native code] value
```

<a name="crash3"/>

### java.lang.IllegalStateExceptionViewGroup.java:5106
The specified child already has a parent. You must call removeView() on the child's parent first.

```
java.lang.IllegalStateException The specified child already has a parent. You must call removeView() on the child's parent first. 
    ViewGroup.java:5106 android.view.ViewGroup.addViewInner
    ViewGroup.java:4935 android.view.ViewGroup.addView
    ViewGroup.java:4875 android.view.ViewGroup.addView
    ViewGroup.java:4848 android.view.ViewGroup.addView
    FragmentManagerImpl.java:887 androidx.fragment.app.FragmentManagerImpl.moveToState
    FragmentManagerImpl.java:2100 androidx.fragment.app.FragmentManagerImpl.addAddedFragments
    FragmentManagerImpl.java:1874 androidx.fragment.app.FragmentManagerImpl.executeOpsTogether
    FragmentManagerImpl.java:1830 androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute
    FragmentManagerImpl.java:1727 androidx.fragment.app.FragmentManagerImpl.execPendingActions
    FragmentManagerImpl.java:150 androidx.fragment.app.FragmentManagerImpl$2.run
    Handler.java:883 android.os.Handler.handleCallback
    Handler.java:100 android.os.Handler.dispatchMessage
    Looper.java:214 android.os.Looper.loop
    ActivityThread.java:7356 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    RuntimeInit.java:492 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
    ZygoteInit.java:930 com.android.internal.os.ZygoteInit.main
```

**Comment by grahammendick** [comment]
Hey, thanks for getting in touch. I tried to recreate the issue in the Twitter example. I [changed the duration of the slide in animation](https://github.com/grahammendick/navigation/blob/master/NavigationReactNative/sample/twitter/android/app/src/main/res/anim/slide_in.xml) to 3000 so that I had time to press the Android back button while the screen was still animating. But it worked fine without any error. Could you try it and see if it works for you, please?

**Comment by gabrielbull** [comment]
It sure crashes on the Twitter example as well. But you have to be ninja fast, which apparently my users are in great numbers. To reproduce in emulator, you have to use the shortcut because by mouse it takes too long. So press **⌘+⌫** right after navigating to a new screen and it will crash the app.

![Enregistrement d’écran, le 2020-01-17 à 09 19 57 2020-01-17 09_22_01](https://user-images.githubusercontent.com/671923/72619225-d6894d00-390a-11ea-9b3b-cb5496a36638.gif)

**Comment by grahammendick** [comment]
I tried it. You really do have to be ninja fast! That isn’t a real world scenario though, because even a ninja can’t be that fast with their fingers. Are you running an automated test suite without a realistic pause, for example?

**Comment by gabrielbull** [comment]
No, it's issue from live users, and it's reported thousands of times so it is affecting a lot of people on my app. Android devices have a physical back button which could explain how they do it this fast.

**Comment by grahammendick** [comment]
You can do it fast enough on your physical device?

**Comment by gabrielbull** [comment]
Yes, easily.

**Comment by grahammendick** [comment]
Do you only see the error in the logs for older devices?

**Comment by gabrielbull** [comment]
Newest device I can see seems to be a Samsung S9, which should be plenty fast.

**Comment by grahammendick** [comment]
Ok, can you try this fix out, please? Add the following to the [FragmentContainerView](https://github.com/grahammendick/navigation/blob/master/NavigationReactNative/src/android/app/src/main/java/com/navigation/reactnative/FragmentContainerView.java)
```java
@Override
public void removeView(View view) {
    endViewTransition(view);
    super.removeView(view);
}
```

**Comment by grahammendick** [comment]
Here’s what’s happening. When we go from A to B Android starts animating A out and B in. Android removes A from the FragmentContainer because it only holds the current scene. But Android can’t set A’s parent View to null until the animation completes. However, before the animation completes we press back. Now Android wants to add A back into the container because it’s now the current scene again. But it didn’t clear it’s parent View so when it adds it back we get the error that says it already has a parent.

Now I know the problem, I realise that I slowed the wrong animation down when I tried to recreate it at first. I should’ve slowed down the “scale_out” not the “slide_in” because that’s scene A’s exit animation. After changing the scale_out duration to 3000 the error happens all the time!

If you want a quick fix then you can turn off the scene exit animation. That way scene A’s parent is cleared when the view is removed because there’s no animation running.
```js
<NavigationStack crumbStyle={() => 'none'} />
```

The fix in the [previous comment](https://github.com/grahammendick/navigation/issues/348#issuecomment-575749083) ensures that the View’s parent is instantly cleared so that it can be safely added again.

**Comment by gabrielbull** [comment]
The fix stops the crashing but brings out a ton of new issue on the screen A. Like images and shadows are no longer visible. `crumbStyle={() => 'none'}` still crashes.

**Comment by grahammendick** [comment]
Thanks for testing it. The idea is right but I put it in the wrong place (too early). Can you try this fix out, please? Change the [onCreateView method of SceneFragment](https://github.com/grahammendick/navigation/blob/22b84f310c700dd659dc91714aa3d63a5111a37a/NavigationReactNative/src/android/app/src/main/java/com/navigation/reactnative/SceneFragment.java#L29) to:
```java
@Nullable
@Override
public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
    if (scene.getParent() != null)
        ((ViewGroup) scene.getParent()).endViewTransition(scene);
    if (scene.transitioner != null)
        postponeEnterTransition();
    return scene;
}
```

**Comment by gabrielbull** [comment]
👍🏻 Looks good to me. I'll make a release early next week and use my users as ginea pigs.

**Comment by grahammendick** [comment]
Great. If all goes well will you make a PR please?

**Comment by grahammendick** [comment]
One error dow, two to go.

I think I know what’s going wrong with “The distance parameter must be greater than zero and less than or equal to the number of Crumbs (0)”

Looks like you’re passing the stateNavigator in as a prop instead of using the stateNavigator from React context. They are not the same.

To see the problem, let’s say you navigate from your home scene to scene A. You have a button on scene A that goes back to the home scene by calling `stateNavigator.navigateBack(1)`. If the user double taps this button then, If you’re not using the stateNavigator from React context, the Navigation router will throw the error. That’s because scene A tries to navigate back twice and this isn’t possible because there’s only the home scene in the stack.

If you use the stateNavigator from React context then you don’t get the error. That’s because scene A has its own stateNavigator. When the user taps the back button the first time then scene A navigates back to the home scene. But, scene A’s stateNavigator doesn’t change because it’s immutable. To scene A, the stack still contains both the home scene and scene A. So when the user taps the back button again, scene A navigates harmlessly back to the home scene again.

**Comment by emerson233** [comment]
We are also suffering from first crash mentioned above recently. (No view found for id 0x395 (unknown) for fragment ScreenFragment)
It occurred when user clicked on a button to log out. The navigation route basically looked like "Tabs Page" -> "Setting Page" (contains a logout button) -> "Sign In Page".
```javascript
// App.js
export class App extends React.Component {
  render() {
      // this.state.currentPage can be "tabs" or "sign in"
      navigator.navigate(this.state.currentPage)
      return (
        <NavigationHandler  stateNavigator={navigator}>
          <NavigationStack />
        </NavigationHandler>
  }
}
```
Note that we are sending an event to `App.js` to re-render a new view hierarchy.

**Comment by grahammendick** [comment]
@emerson233 Thanks for the extra details. Much appreciated. 

It isn’t safe to call `navigate` inside the render method. Behind the scenes, navigate calls `setState` and React doesn’t allow side-effects like `setState` inside render. 

Also, it’s better to use the `stateNavigator` in React context than to send events to the App component. [The stateNavigator in App.js is not the same as the one in React context](https://github.com/grahammendick/navigation/issues/348#issuecomment-575893659).

**Comment by emerson233** [comment]
```javascript
// App.js
export class App extends React.Component {
  static getDerivedStateFromProps(props: Props, state: State) {
    // create new navigator
    const navigator = new StateNavigator(stateNavigator)
    navigator.navigate(props.currentPage)
    return {
      navigator
    }
  }
  render() {
      // this.state.currentPage can be "tabs" or "sign in"
      return (
        <NavigationHandler  stateNavigator={this.state.navigator}>
          <NavigationStack />
        </NavigationHandler>
  }
}
```
What about creating a new `stateNavigator` in `getDerivedStateFromProps`? Is it safe?

**Comment by grahammendick** [comment]
You're trying to reset the stack, right? You should do this by setting `trackCrumbTrail` to false.

**Comment by emerson233** [comment]
```javascript
var stateNavigator = new StateNavigator([
  {key: 'tabs'},
  {key: 'settings', trackCrumbTrail: true},
  {key: 'signin', trackCrumbTrail: false},
]);
```
Setting `trackCrumbTrail` here?

**Comment by grahammendick** [comment]
That looks good. So why are you creating a new StateNavigator?

**Comment by emerson233** [comment]
There are huge differences in view hierarchy between these two scenes (with/without signing in). So we want to reset the stack when user is doing a sign in/out.

**Comment by grahammendick** [comment]
You don't need a new StateNavigator for that. Put all your states in the one StateNavigator and set trackCrumbTrail to false when you want to reset the stack.

**Comment by emerson233** [comment]
Cool. I will give it a try. By the way, is `trackCrumbTrail ` working on iOS too?

**Comment by grahammendick** [comment]
Yes. You can even dynamically control the crumb trail. See the [popping when pushing](https://grahammendick.github.io/navigation/documentation/native/pop-navigation.html) documentation

**Comment by gabrielbull** [comment]
I too am trying to reset the stack. I'll try your suggestions as well.

**Comment by grahammendick** [comment]
Great, that sounds promising. Thanks @gabrielbull and @emerson233 for all your help so far

**Comment by gabrielbull** [comment]
Closing in favour of PR and other issues.
