### ISSUE TITLE
Questions wrt Navigation React Mobile

### ISSUE THREAD

**Issue by arunmenon1975** [grahammendick/navigation#357]
This question is in relation to the use of the Navigation router on a PWA i.e `navigation-react-mobile` module

A TLDR;

- are nested `StateNavigator`'s a possibility in `Navigation React Mobile`? 
- The `Refresh` functionality works fine but when used in conjunction with a non-router feature (transform animation in CSS for example)  the screen seems to visually re-render since the animation restarts from the beginning as the component is re-rendered when the URL changes.

The companion native app(being built using `navigation-react-native`) is going to be primarily consumer-focussed and i am moving most admin functions to a PWA (except for a a couple of core admin actions). 

I have a simple layout since again a mobile form-factor may come into play.

```

===================================
1) App Name                          =(_menu_)
===================================
2) < (_Arrow_)      Screen title
===================================






3) content 






===================================
4) Static bottom tabs
===================================

```
A normal native-ish layout. Everything works great. 

All the above are embedded within the `NavigationHandler`
`1)` and `4)` are outside the `NavigationMotion` component

In certain screens inside `3)` i.e. the main content area, i have a tab set (a ‘top tab’) that would display appropriate content for the chosen tab. This would replicate the Android functionality and only update the content area on click. Clicking on a tab will also update the URL based on `NavigationData`. (eg http://localhost/something?tab=1 to http://localhost/something?tab=2)

The broad outline:

```
===================================
1) App Name                      =(_menu_)
===================================
2) < (_Arrow_)      Screen title
===================================
3) Top tabs here
===================================





4) content (for the tab) 





===================================
5) Static bottom tabs
===================================

```

The issue i have is that since all of the content resides inside of the `NavigationMotion` component, a change to the URL seems to tigger the animation for `2)`, `3)` and `4)` before the content is displayed, while i am expecting only `4)` to change. My tab header (standalone, i.e separate from the tab content it will display) has the Android-like slide-to animation (using CSS transforms on a separate div below the tabs) but this animation restarts from the beginning on click since the URL changes. I tried the `Refresh` hyperlink component  but get the same result.

I tried several option but none seems to work reliably so far (including `react portals`, a context-driven portal system that clones a component and injects it outside the the `NavigationHandler`, etc) or has elements of being  ‘hackish’ attempts.

One method did almost work, but I’m not sure if this is a supported feature. I got the idea from the native implementations where each tab can have its own `StateNavigator`. So i created a new `StateNavigator` and open this out (in a react portal driven modal so that i can get more screen real-estate). My tabs work fine including the animation. The primary issue - possibly the only issue - is with the back button. Clicking the Back button seems to change the URL to a root URL ie. instead of http://localhost/something?tab=1 it somehow seems to go to a URL that reads http://localhost?tab=1.  A subsequent back click corrects this to the expected URL but of course the flow is broken and so is the UI. I am not sure but perhaps this has something to do with the interim URL that the Router generates as part of its core functioning.

Some options i am considering, besides any sudden ideas i get:

- have the tab(and the header) sit outside the `NavigationMotion` component. I may need have some sort of conditions to display them at the appropriate screen. A reasonable option but ill need to work out the conditions and how to have them in optimally.
- don't update the URL on tapping the tab. I only lose out on taking the user to the exact tab. I can always take the user to the first tab. This is a reasonable option since the tab functionality is dependent on some guards (finish this step on this tab to go to that step on that tab etc)
- dont worry about the animation of a minor component like a tab. Maybe get rid of the `slide-to` animation and make them normal tabs with appropriate markings. Having tabheaders separate from content isnt terribly `Accessible` without additional work
-

**Comment by grahammendick** [comment]
The `navigation-react-mobile` package gives you stack navigation on the web. Stack navigation is standard on a native app but is rare to find it on the web, even if you’re building a PWA. If you don’t need stack navigation then you can use the Navigation router on the web without the `navigation-react-mobile` package. One day, I think stack navigation will be a standard feature of PWAs. I’m going to assume you want stack navigation and I’ll try to answer you question; 

You should take a look at the [Web Zoom sample](https://github.com/grahammendick/navigation/tree/master/NavigationReactNative/sample/web). It’s a single code base that runs on three platforms (Android, iOS and the Web) and it solves the problem you’re having with the tabs. When you tap one of the three different color buttons on the Details page then it changes the Url without any scene animation. The trick is that it navigates to the same `State` without increasing the stack size. In that case, the Url changes but the animation doesn’t run. You prevent the stack size increasing by [truncating the crumb trail](https://github.com/grahammendick/navigation/blob/master/NavigationReactNative/sample/web/createStateNavigator.js#L21).

Let me know if I’ve understood you correctly, then we can chat about it in more detail.

**Comment by arunmenon1975** [comment]
Thanks for the pointers. Very interesting. I have usecases similar to the Web Zoom sample. My web layout is purposefully simple and tries to model itself along the native layout lines.

Nothing really quite like having a single code-base for all the targeted platforms especially when the app is not overly complex. I will try this out  and port over to my needs. This might take a short while as i ready things from my existing app but i will respond back here with inputs on how it went.

Regarding truncating thumbnails i ~~have~~ had this in place:

```
stateNavigator.states[mainNavigatorKeys.ADMIN_MENU_WINGS].truncateCrumbTrail = function(state, data, crumbs) {
  var latestCrumb = crumbs[crumbs.length - 1];
  console.log(state, data, crumbs)
  console.log(latestCrumb, latestCrumb.state.key === mainNavigatorKeys.ADMIN_MENU_WINGS)
  //return latestCrumb.state.key === mainNavigatorKeys.ADMIN_MENU_WINGS ? crumbs : crumbs.slice(0, -1); 
  return crumbs; 
};

```
[I just noticed that i am returning `crumbs` and had commented out the actual required functionality at some point. Looks like it all might just work  if i correct this. In all my debugging attempts i seemed to have skipped reading inside of this declaration as i guess my assumption was that the codeblock, by its very presence, meant it actually returned a new slice. In my defence, it was a long file as i hadn't moved things around into separate files yet].

**Comment by grahammendick** [comment]
I'm gonna close this because truncating the crumb trail solves your animation problem. Please let me know how you get on with your PWA

**Comment by arunmenon1975** [comment]
I actually wanted to close it yesterday but got busy and forgot. Yes, the `truncateTrumbnail` solves the issue i had. Thanks for the solution. It was plain oversight from my side.

I am currently on a slight rework off the app after your suggestion for utilising a single codebase, which made a lot of sense for my current requirements. I see potential in the future so had to take a decision and stick with it and thus the minor re-write to go with this approach.

It's rather strange to be actually spoilt for choice and be indecisive now that i know that my app can be built in various approaches, all with a single library. 

For now i am going the `monorepo` route with `react-native-web` for the web presence (off a re-wired `create-react-app`(CRA) initiated app) using  `react-native` code to build the app. Thus far its working great. Three core libraries have integrated well with this workflow: the `navigation` router, `gesture-handler` and `vector-icons`. Most of the rest are platform-agnostic so have had no issues thus far.

 It did take some time to get this going since this is my first ever `monorepo` (come to think of it,  my app now has a lot of 'firsts') solution and there were some minor early stumbling blocks mostly with orchestrating and ensuring that all the separate code written for both the apps (native/web) work well together from a single codebase. I chose this approach mainly for a hands-on experience(read 'for the CV') and always have the `Zoom` sample approach as the fallback. The only benefit  otherwise of going this route vs the Zoom sample approach is that i don't have to tweak the `webpack` config by hand and have it done automatically by the CRA in-built configs, which perhaps could do it better than my current knowledge of webpack and how to integrate it optimally with `React`.

And for anybody interested in the `monorepo` solution that is working for me, [this post ](https://dev.to/brunolemos/tutorial-100-code-sharing-between-ios-android--web-using-react-native-web-andmonorepo-4pej)got me going.

**Comment by grahammendick** [comment]
It’s great to hear your PWA is going well. In the Zoom example, Did you notice that I [call browser history back](https://github.com/grahammendick/navigation/blob/bfbc06052c49b23812fb318fe9d12319077746ae/NavigationReactNative/sample/web/Detail.js#L24) when the cancel button is tapped? If I didn’t do that then you’d end up with a browser history that looked like Grid → Details → Grid. Tapping the browser back would go from the Grid to the Details which would destroy the illusion of a stack of screens. Does that make sense?

**Comment by arunmenon1975** [comment]
I was puzzled for some time since i just could not replicate the issue locally. Thats when i checked the line numbers. `L24` on my local copy was different: it had different code. There was no mention of the browser back  method. I crosschecked with another copy of the repo that i had cloned in another separate directory. It looks like i had the wrong files all the while (all of last week)! I replaced them and now things fall in place. I get the issue, and the fix perfectly well now. Makes sense because that is expected behaviour from a user's perspective.  And requiring code-intervention to ensure that it meets user expectation.

Incidentally, the purged files dutifully logged all the history actions and played them back all the way exactly as you mentioned it would do, and shouldn't be doing. I wonder which version that set was. Maybe i pulled in an old version, not sure. In fact i built my typescript variant(to ensure that things work with TS as well before i gradually port over my early-effort code) based off that set and, besides the browser back button issue, everything worked well.

**Comment by grahammendick** [comment]
You might've also missed that I [prime the browser history on start up](https://github.com/grahammendick/navigation/blob/bfbc06052c49b23812fb318fe9d12319077746ae/NavigationReactNative/sample/web/index.web.js#L13). If I didn't do that then the cancel button wouldn't work if the user jumped straight to the details scene (maybe by bookmarking/sharing the url).

**Comment by arunmenon1975** [comment]
Yes, did miss that. Thanks for pointing that out.

`Fluent` navigation seems to be especially useful in deeply nested navigation - something i just might have in my current implementation where my workflow is purposefully over-simplified i.e individual routes for even simple tasks. I guess the second `boolean` parameter is crucial since the history entry would need to be replaced vs being added onto to short-circuit the flow of actions. 

Coherent back functionality is a critical component of any PWA/web app and gains even more importance since user assumption of an apps interactions and flow is more tuned to that of actual native apps on their device vs actual sequence of actions performed.

**Comment by arunmenon1975** [comment]
On further thought on another point of concern in my app, i can now have the best of both worlds now that i have a working `monorepo` going by removing the need of the CRA app altogether and just have a primary workspace package(sitting alongside the other packages) using the 'all-in-one' Zoom sample approach with my code.

The CRA app is redundant if i can ramp up my `webpack` knowledge (`splitChunks` and `cacheGroups` seems to be the key i think). I did experiment a little last week and find that i can get my initial bundle in the  350-400 kb size(below the 250kb or thereabouts that seems to be optimal upper limit), though this count is without the client-side `firebase` package which, in my app, is required upfront.

**Comment by grahammendick** [comment]
Seeing as you're looking into performance, did you know that you can [server render Navigation React Mobile](https://github.com/grahammendick/navigation/tree/master/NavigationReactMobile/sample/isomorphic)?

**Comment by arunmenon1975** [comment]
I was going through the examples across all the individual modules and did come across the `isomorphic` version just a couple of days ago. Was too focussed on the Twitter and Zoom samples to actually look deeper into the other options. Definitely interesting and ticks to everything i need except for the by now perennial issue: i have zero experience in building isomorphic apps. 

Performance (and SEO) are both right up there in the priority list. The initial bundle size is thus very important and can shape core app-related decisions. For instance i am now re-considering trading the convenience of coding in `react-native` to serve both the web and native apps and doubling back to individual solutions because i find that the final bundle size is going way beyond my own upper limits.  The plain `React` app helps me shave at least ~200 odd kb off my final bundle(s) size, a not insignificant number for my app and projected audience. I lose out on the fantastic dev convenience of a single codebase though. Decisions.

My final PWA app will be served off `Firebase Hosting` - or at least thats the planned residence. Firebase comes with `Cloud Functions` - a cloud  platform that does provide a lot of features right off the bat, besides the obvious convenience of having an accessible node instance available at the server end. I currently dont use cloud functions for anything critical - there is one planned to enable an online/offline observer(not on my priority list however) and another for generation of simple image thumbnails(now available as a built-in dashboard-ready extension incidentally, so no code required). 

Strangely, it didn't cross my mind - until now - that Cloud functions could be utilised for the server-related stuff on isomorphic apps.  This option does seem to be the best bet, all things considered. Well, actually almost all things since i will have to factor in my inexperience here. Thanks for the example though. It will be of immense help to get started out. Ive always been fascinated by the term `rehydrate` in a technical context, and isomorphic apps are there to help indulge in it :) 

Let me give it a try. Another first.  I think, from a long-term perspective, the solution could work regardless of the backend as long as it exposes a node driven instance at a minimum(`GCP`, `AWS`, `Azure` etc all do AFAIK). I have sufficient back-up options now in various states of progress and are all proven doable all though.

**Comment by arunmenon1975** [comment]
Having an issue getting started out with the isomorphic solution. Please let me know if you have any pointers.

Im trying to use the existing JSX and related files from the example and port it over to updated versions of the dependencies. The `build` is fine. 

 ```
Asset      Size  Chunks             Chunk Names
app.js  1.18 MiB    main  [emitted]  main
Entrypoint main = app.js
[./Data.js] 1.77 KiB {main} [built]
[./Isomorphic.js] 684 bytes {main} [built]
[./People.js] 1.04 KiB {main} [built]
[./Person.js] 826 bytes {main} [built]
[./getStateNavigator.js] 1.45 KiB {main} [built]
[./index.js] 503 bytes {main} [built]
    + 14 hidden modules
✨  Done in 4.82s.
✨  Done in 5.29s.
```

`app.js` is emitted but getting an error on `start`:

`SyntaxError: correct/file/path/server.js: Unexpected token (38:16)`
 
which points to:

` <NavigationHandler stateNavigator={stateNavigator}>`

It does look like the JSX isn't being parsed.

Ive got this in my `package.json`:

```
{
  "name": "menuappisomorphic",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "express": "^4.17.1",
    "navigation": "^5.2.0",
    "navigation-react": "^4.1.1",
    "navigation-react-mobile": "^3.1.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0"
  },
  "scripts": {
    "build": "webpack",
    "start": "babel-node server.js"
  },
  "devDependencies": {
    "@babel/cli": "^7.8.4",
    "@babel/core": "^7.8.4",
    "@babel/plugin-transform-react-jsx": "^7.8.3",
    "@babel/preset-env": "^7.8.4",
    "@babel/preset-react": "^7.8.3",
    "babel-loader": "^8.0.6",
    "webpack": "^4.41.6",
    "webpack-cli": "^3.3.11"
  }
}
```
and this in my `babel.config`:

```
module.exports = {
  presets: ['module:@babel/preset-react','module:@babel/preset-env'],
  "plugins": ["@babel/plugin-transform-react-jsx"]
};
```
the transform plugin was an afterthought addition. I get the same error with or without it.

**Comment by arunmenon1975** [comment]
Issue is fixed. Fix: had to install the `@babel/node` dependency as well. I can see the example app now

**Comment by grahammendick** [comment]
> The plain React app helps me shave at least ~200 odd kb off my final bundle(s) size, a not insignificant number

Make sure that you're measuring the compressed size because all JavaScript is compressed when it's sent over the wire.

**Comment by arunmenon1975** [comment]
Ok, and that was the default output from a `build`. My understanding is that this is the max possible size-compression via scripting. The browser would then gzip-compress, which also normally produces an even smaller size.  The `Navigation` router size is surprisingly small btw so absolutely no issues there.  

This is the `webpack` snippet:

```
...
mode: 'production',
...
cacheGroups: {
              reactVendor: {
                test: /[\\/]node_modules[\\/](react|react-dom)[\\/]/,
                name: "reactvendor"
              },
              reactNayiveWebVendor: {
                test: /[\\/]node_modules[\\/](react-native-web)[\\/]/,
                name: "reactnativewebvendor"
              },
              navigationVendor: {
                test: /[\\/]node_modules[\\/](navigation|navigation-react|navigation-react-native | navigation-react-mobile)[\\/]/,
                name: "navigationvendor"
              },
    
              vendor: {
                 test: /[\\/]node_modules[\\/](!react)(!react-dom)(!react-native-web)(!navigation)(!navigation-react)(!navigation-react-native)(!navigation-react-mobile)[\\/]/,
              name: "vendor"
            },
            }
...
```


I am currently on the Isomorphic/Universal/SSR integration and negotiating the learning curve so to speak, especially with integrating with my chosen backend. I will update here when its done. Hopefully i do not run into issues. Thanks for all the pointers thus far: it has saved me a lot of time and effort.

**Comment by grahammendick** [comment]
The gzip-compression should give you about 70% saving. Paste your JavaScript into this [online compressor](https://closure-compiler.appspot.com/home) to get an idea of the saving you'll get.

**Comment by grahammendick** [comment]
You [don’t need to prime the browser history on start up anymore](https://github.com/grahammendick/navigation/blob/8f9ec99e1b45d0ea3929499df9d40b6e9fc95461/NavigationReactNative/sample/web/zoom/index.web.js#L12). The Navigation router does it automatically if you update to `navigation v5.3.0` and `navigation-react-mobile v3.2.0`
