### ISSUE TITLE
NavigationBar and TabBar border

### ISSUE THREAD

**Issue by 10centmedia** [grahammendick/navigation#360]
First of all, great work on this library, very promising!

Is there a way we can hide NavigationBar and TabBar border?

**Comment by grahammendick** [comment]
Hey there, thanks for getting in touch. If you make the Navigation Bar transparent or part-transparent then [the Navigation router hides the border](https://github.com/grahammendick/navigation/blob/cbcccfa15ac41379e7967f00d30885a7d1690553/NavigationReactNative/src/android/app/src/main/java/com/navigation/reactnative/NavigationBarManager.java#L38). 
```jsx
<NavigationBar barTintColor="rgba(255, 255, 255, 0.5)" />
```
I’m open to a PR that adds an outline/elevation prop to the Navigation and Tab Bar components. Let me know if you’re interested.

**Comment by grahammendick** [comment]
Actually, I don't think there is a border on the Tab Bar when it renders as a `BottomNavigationView`
```jsx
<TabBar bottomTabs={true} swipeable={false}>
```

**Comment by 10centmedia** [comment]
> Hey there, thanks for getting in touch. If you make the Navigation Bar transparent or part-transparent then [the Navigation router hides the border](https://github.com/grahammendick/navigation/blob/cbcccfa15ac41379e7967f00d30885a7d1690553/NavigationReactNative/src/android/app/src/main/java/com/navigation/reactnative/NavigationBarManager.java#L38).
> 
> ```js-jsx
> <NavigationBar barTintColor="rgba(255, 255, 255, 0.5)" />
> ```
> 
> I’m open to a PR that adds an outline/elevation prop to the Navigation and Tab Bar components. Let me know if you’re interested.

Very interested! Would love to help but implementing it in native is way out of my scope. Thanks so much for this! I really appreciate your work!

**Comment by grahammendick** [comment]
Thanks, I’m really glad you like the Navigation router. Here’s what the notifications screen of [the twitter sample](https://github.com/grahammendick/navigation/tree/master/NavigationReactNative/sample/twitter) looks like after I made the navigation bar transparent.

![Screenshot 2020-02-17 at 10 03 49](https://user-images.githubusercontent.com/1761227/74644059-9ae1dd00-516d-11ea-9692-0a477a2a61e5.png)

There’s no borders in sight! So I don’t think we need a new prop after all. Does this work for you?

**Comment by 10centmedia** [comment]
Works perfect! Thanks so much. Will close this.
