### ISSUE TITLE
Icons do not appear on menu items in overflow menu

### ISSUE THREAD

**Issue by salockhart** [grahammendick/navigation#374]
On Android, when I declare a `BarButton` with an icon and a `show` value of `never`, the icon does not appear in the overflow menu.

Here's an example, using a modified Detail component from the zoom sample. Feel free to check out my branch: https://github.com/salockhart/navigation/tree/overflow-menu-icon-example

```
...
            <RightBar>
              <BarButton
                title="cancel"
                show="always"
                systemItem="cancel"
                image={image}
                onPress={() => {
                  stateNavigator.navigateBack(1);
                }}
              />
              <BarButton
                title="Cancel"
                show="never"
                systemItem="cancel"
                image={image}
                onPress={() => {
                  stateNavigator.navigateBack(1);
                }}
              />
              <BarButton
                title="Cancel"
                show="never"
                systemItem="cancel"
                image={image}
                onPress={() => {
                  stateNavigator.navigateBack(1);
                }}
              />
            </RightBar>
...
```

<img src="https://user-images.githubusercontent.com/6651364/79480910-ad11b780-8006-11ea-971d-7fbd5d1cfbd9.gif" width="200">

It would be nice if the `image` prop on the `never` items still appeared in the overflow menu.

I understand that this is kind of tricky, though - https://stackoverflow.com/questions/18374183/how-to-show-icons-in-overflow-menu-in-actionbar seems to show it not really being part of the public API. I am not sure if there is a better way, or if this is something that we are even interested in doing here.

If this is something worth tackling, I am more than happy to help with the work. I'll just need a point in the right direction.

Thanks!

**Comment by grahammendick** [comment]
Thanks for the question.  Like you say, it isn't part of the public api so it isn't something we should add to the Navigation router

**Comment by salockhart** [comment]
I understand - thanks!
