### ISSUE TITLE
React Native NavigationBar is empty on Android

### ISSUE THREAD

**Issue by salockhart** [grahammendick/navigation#383]
After updating from 6.4.0 to >=6.7.1 (I haven't tried anything lower) I started seeing that when I opened the app, the navigation bar was blank where I was expecting a title and menu items.

I am not sure what the steps to reproduce this are. I haven't seen it in Release mode at all. Debug mode appears to be intermittent, but if it happens it happens for all screens until it magically starts working again, after which it will work until it magically stops working. I'm not sure if it had any impact, but after wiping my node_modules and android build folder, and re-installing everything from scratch, it seems to be working again.

My hunch is that this may be a race condition somewhere. When I was experiencing the issue and attached the Android Studio debugger to see if `setTitle` in ToolbarManager was actually getting called, the problem went away.

I think I will be fine for now, but I wanted to write this up in case anyone else experiences this issue. If I nail down any specific reproduction criteria, I will update here.

**Comment by salockhart** [comment]
Side note: since I was mucking around with node_modules and stuff in fixing https://github.com/grahammendick/navigation/pull/382 it's entirely possible that I just borked my dependencies and now it's working after everything has settled. I've just updated again from 6.10.0 to 6.10.1 and it seems to still be working fine.

**Comment by grahammendick** [comment]
Ok, I'll leave this open for a few days to see if anyone else has seen it. If all is good for you and we don't hear anything from anyone else then I'll close it down. Sound fair?

**Comment by salockhart** [comment]
Sounds fair to me!

**Comment by grahammendick** [comment]
Not heard anything so closing [as agreed](https://github.com/grahammendick/navigation/issues/383#issuecomment-618935826)
