### ISSUE TITLE
Content within SearchBar not tappable when rendered in a Modal on iOS

### ISSUE THREAD

**Issue by mpiannucci** [grahammendick/navigation#386]
It works fine when its not in a modal, and taps are detected from content in the modal that isn't the search content. 

### Modal
![search-modal-tap](https://user-images.githubusercontent.com/1832671/80534322-0960c980-896d-11ea-8de5-f3ab4ae19fb5.gif)

### Non Modal (Expected the alert to show like here)
![search-non-modal-tap](https://user-images.githubusercontent.com/1832671/80534313-06fe6f80-896d-11ea-8482-306eafc9d78b.gif)

**Comment by mpiannucci** [comment]
FWIW I get around this by just not having anything render in the search container but long term it would be cool for the taps to work in both

**Comment by grahammendick** [comment]
Thanks for the interesting bug.
By the way, how's your app going? Have you launched the iOS version yet?

**Comment by mpiannucci** [comment]
Yes!! If ya wanna see some screenshots heres the app store link https://apps.apple.com/us/app/hopewaves/id945847570?mt=8&ign-mpt=uo%3D4

**Comment by grahammendick** [comment]
Your app looks so good, congrats! How many users do you have?
Best of luck with the new one, too!

**Comment by mpiannucci** [comment]
Thanks! It was a native app I had for like 5 years before rewriting it in RN. It’s pretty niche but I have around 1000 or so installs and everyone likes the new version better than the native one I had haha

**Comment by grahammendick** [comment]
Lol that's too good
