### ISSUE TITLE
Split Views

### ISSUE THREAD

**Issue by 10centmedialabs** [grahammendick/navigation#391]
Just wondering if the current library (NavigationReactNative) have the support for this?
https://developer.apple.com/design/human-interface-guidelines/ios/views/split-views/

**Comment by grahammendick** [comment]
Hey there. Could you give me an example use case, please?

**Comment by 10centmedialabs** [comment]
I think I'm off topic with this, in regards to navigation. Basically I'm trying to implement a master-detail view (which I think has nothing to do with navigation). Sorry, going to close this.
