### ISSUE TITLE
NavigationBar tintColor doesn't apply to BarButton nor SearchBar on Android

### ISSUE THREAD

**Issue by salockhart** [grahammendick/navigation#396]
I am trying to theme my app, and I want to set the navigation header tint. This works fine with `barTintColor` and `titleColor`, but when it comes to the BarButton and SearchBar components, they remain un-themed.

Here's an example branch, check out the zoom sample: https://github.com/salockhart/navigation/tree/bar-tint-example

The gist of it is:

```
<NavigationBar
  largeTitle={true}
  title="Colors"
  barTintColor="#f00"
  tintColor="#fff"
  titleColor="#fff">
```

results in:

<img width="300" alt="Screenshot 2020-05-14 at 16 02 18" src="https://user-images.githubusercontent.com/6651364/81950886-6b236380-95fc-11ea-8b0a-c23fd1456cd2.png">
<img width="300" alt="Screenshot 2020-05-14 at 16 02 26" src="https://user-images.githubusercontent.com/6651364/81950892-6c549080-95fc-11ea-98ba-f2ba426882ef.png">

Is there a different prop that I should be using to style these?

**Comment by grahammendick** [comment]
We did [discuss the tintColor](https://github.com/grahammendick/navigation/pull/311#issuecomment-544257001) in the "Navigation Bar on Android" PR. The problem is that we couldn't find a way to programmatically change the background color of the overflow menu. So what's the point of changing the color of the menu items via a tintColor prop if you can't change the background color with a prop, too? 

The only way to change the background color of the menu is via the styles.xml file. So we thought it made sense to change the menu item color there too. Here's a menu with a red background and white text.
```xml
<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
  <item name="android:textColor">#000000</item>
  <item name="android:itemTextAppearance">@style/myCustomMenuTextAppearance</item>. 
  <item name="android:itemBackground">#f00</item>
  <item name="android:actionMenuTextColor">#fff</item>
</style>
<style name="myCustomMenuTextAppearance">
  <item name="android:textColor">#fff</item>
</style>
```
Please let me know If you know of a way to change the background color of the overlfow menu.

**Comment by salockhart** [comment]
An okay, I understand.

For my needs, I didn't need to change the overflow menu, just the visible action buttons. 

```
<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:textColor">#000000</item>
        <item name="android:actionMenuTextColor">#fff</item>
</style>
```

was sufficient for me.

Thanks for your help!

**Comment by salockhart** [comment]
Actually, sorry - that didn't solve the search field in the nav header. That remains the dark grey color. I'll investigate if there is a theme change I can make for that.

**Comment by grahammendick** [comment]
Here's an example of how to change the background color of the search view.
```xml
<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
  <item name="android:textColor">#000000</item>
  <item name="searchViewStyle">@style/mySearchViewStyle</item>
</style>
<style name="mySearchViewStyle" parent="Widget.AppCompat.SearchView">
  <item name="queryBackground">@android:color/white</item>
</style>
```
 We might be able to add props to the `SearchBar` component and style it programmatically. Let me know if you're interested on working on a PR to try this idea out.

**Comment by salockhart** [comment]
Okay, thanks! That was very helpful.

I did find a way to set it programmatically, inside SearchBarView.java:

```
SearchView.SearchAutoComplete searchAutoComplete = searchView.findViewById(androidx.appcompat.R.id.search_src_text);
searchAutoComplete.setBackgroundColor(Color.WHITE);
```

I'm sure we could wire this up to props quite easily.

I also found that setting

```
<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="android:textColor">#000000</item>
    <item name="android:actionMenuTextColor">#fff</item>
    <item name="searchViewStyle">@style/Widget.AppCompat.SearchView.ActionBar</item>
</style>
```

helped quite a bit:

<img width="300" alt="Screenshot 2020-05-15 at 11 15 49" src="https://user-images.githubusercontent.com/6651364/82039957-aa55c100-969d-11ea-9768-dd3f0174e35a.png">

My final sticking point is that "back" button. Is that something we control? I'll do some digging.

I'd be happy to help put up a PR for all this once I've figured it out

**Comment by salockhart** [comment]
Got it:

```
<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="android:textColor">#000000</item>
    <item name="android:actionMenuTextColor">#fff</item>
    <item name="searchViewStyle">@style/Widget.AppCompat.SearchView.ActionBar</item>
    <item name="colorControlNormal">#fff</item>
</style>
```

There might be a way to set that programmatically, but that's sufficient for my needs right now

**Comment by salockhart** [comment]
I should have a PR up for some of this shortly.

**Comment by grahammendick** [comment]
I've been thinking a bit more about this one. We should treat the visible menu buttons separately to the overflow menu. Like you said, you were only talking about the visible menu buttons. 

If you'd used an icon for the search menu button then the `tintColor` would've applied. So we should tint the text for the visible menu buttons too. We can loop through the [toolbar children looking for the ActionMenuItemViews and then set their text color](https://stackoverflow.com/a/42329013/1310468).

I don't think people would expect the overflow menu to take on the `barTintColor` and `tintColor` of the navigation bar. The overflow menu is more like a context menu. I don't see people wanting to change the style of the overflow menu, for example, Whatsapp changes the navigation bar colors but leaves the default colors for the overflow. But if they do they'll have to do that with the styles.xml.

Do you think this sounds good? If you do, I'm happy to work on this part

**Comment by salockhart** [comment]
I think that makes a lot of sense, and tracks with what my expectations are for how `tintColor` should behave
