### ISSUE TITLE
Tapping on a selected tab bar item on iOS does not scroll to the top

### ISSUE THREAD

**Issue by gabrielbull** [grahammendick/navigation#413]
On iOS, tapping on a selected tab bar item should go back one in the navigation stack and scroll the scrollview to the top if it is back to the first screen.

**Comment by grahammendick** [comment]
Yes, this isn't pat of the iOS platform but it\s so ubiquitous that we should add it, We should put it behind a prop though because it isn't part of the platform and for backward compatibility. Let me know if you want to work on it

**Comment by grahammendick** [comment]
I’ve got a rough idea of how to do this on iOS.

Inside the `didSelectViewController` method of the `NVTabBarView` we can check if it’s reselecting the tab  by comparing the selected index with the `_selectedTab` property.

```objective-c
bool reselected = 
  [_tabBarController.viewControllers indexOfObject:viewController] == _selectedTab;
```

Then we can get the first scene’s view controller
```objective-c
UIViewController *sceneController = 
  ((UINavigationController *) viewController).viewControllers[0];
```

Next, we find the nearest scroll view within that scene and scroll to the top. The `topLayoutGuide` allows for the navigation and status bars.
```objective-c
[scrollView 
  setContentOffset:CGPointMake(0, -sceneController.topLayoutGuide.length)
  animated:YES];
```

Although it's considered an iOS feature we should make it work on Android, too.

**Comment by grahammendick** [comment]
I'll work on this. Just let me know if you want to pick it up instead

**Comment by grahammendick** [comment]
Just to let you know, I'm working on this in [the tab-top branch](https://github.com/grahammendick/navigation/tree/tab-top)

**Comment by grahammendick** [comment]
@gabrielbull I’ve implemented this in the [twitter sample in the tab-top branch](https://github.com/grahammendick/navigation/tree/tab-top/NavigationReactNative/sample/twitter). Can you take a look please and see if it works as you’d expect on iOS and Android?

You need to run `npm run package` at the top level folder to generate the latest `navigation-react-native` package in the `build/npm` folder. Then copy the package into the `node_modules` of the twitter sample.

**Comment by grahammendick** [comment]
@gabrielbull No need to check it. I made some adjustments and I'm happy with it now. I'm going to turn it on by default, too
