### ISSUE TITLE
When creating the tab bar on iOS on a view that is transformed, the safe area inset does not get applied

### ISSUE THREAD

**Issue by gabrielbull** [grahammendick/navigation#414]
I have an instance where my main view, the one containing the tab bar, is transformed (translateY + scale) when it is mounted. It is then animated back to full screen after the user has made an action.

In this instance, the tab bar does not get the safe area insets applied and when the view is animated back to full screen, it is still missing the offset. 

It works fine if the main view is full screen when mounting.

<img width="645" alt="Capture d’écran, le 2020-06-03 à 01 06 50" src="https://user-images.githubusercontent.com/671923/83598128-f5ddeb00-a536-11ea-927a-0343ff6f4849.png">

If you could point me where to look at to fix this issue I'd be happy to take a look.

**Comment by grahammendick** [comment]
That sounds interesting. Could you show me the animation code, please?

**Comment by gabrielbull** [comment]
No need for an animation actually, any translate, even 1px will prevent the safe area insets from being applied. This is also happening to the navigation bar at the top.

![Simulator Screen Shot - iPhone 11 - 2020-06-03 at 09 08 17](https://user-images.githubusercontent.com/671923/83640324-f8adff80-a579-11ea-85cb-b2977fafcb63.png)

Here is the code to reproduce:

```
import React, {useMemo, useState} from 'react';
import {StyleSheet, View, Text, TouchableOpacity} from 'react-native';
import {TabBar, TabBarItem, NavigationStack} from 'navigation-react-native';
import {NavigationHandler} from 'navigation-react';
import {StateNavigator} from 'navigation';

const App = () => {
  const [transformed, setTransformed] = useState(true);

  const stateNavigator = useMemo(() => {
    // eslint-disable-next-line no-shadow
    const stateNavigator = new StateNavigator([{key: 'first'}]);
    stateNavigator.states.first.renderScene = () => {
      return (
        <View style={styles.screen}>
          <TouchableOpacity onPress={() => setTransformed(false)}>
            <View style={styles.button}>
              <Text style={styles.buttonText}>Make full screen</Text>
            </View>
          </TouchableOpacity>
        </View>
      );
    };
    stateNavigator.navigate('first');
    return stateNavigator;
  }, []);

  return (
    <View style={transformed ? styles.transformed : styles.normal}>
      <TabBar primary={true}>
        <TabBarItem systemItem="favorites">
          <NavigationHandler stateNavigator={stateNavigator}>
            <NavigationStack />
          </NavigationHandler>
        </TabBarItem>
        <TabBarItem systemItem="downloads">
          <NavigationHandler stateNavigator={stateNavigator}>
            <NavigationStack />
          </NavigationHandler>
        </TabBarItem>
      </TabBar>
    </View>
  );
};

const styles = StyleSheet.create({
  normal: {
    flex: 1,
  },
  transformed: {
    flex: 1,
    transform: [{translateY: 1}],
  },
  screen: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  button: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: 'blue',
  },
  buttonText: {
    fontWeight: '600',
    color: 'white',
  },
});

export default App;
```

**Comment by grahammendick** [comment]
Thanks for the code example. Instead of  `translateY` I used position absolute and `top` and it worked fine. The scale didn't cause a problem. Is this workaround ok?
```jsx
transformed: {
  position: 'absolute',
  top: 1,
  left: 0, right: 0, bottom: 0
},
```

**Comment by gabrielbull** [comment]
It's odd that `top: 1` would work but `translateY: 1` would not. I suspect most animations, including mines, will use the `translateY` instead of the `top` properties, so it would be nice to fix it. I probably could switch my animation to use `top` instead of `translateY` but when this library will become popular, others will inevitably run into this issue.

**Comment by grahammendick** [comment]
Transforming the whole tab screen doesn't sound that common so I'm happy with the workaround if you are. We can always look at it again if it's re-raised

**Comment by gabrielbull** [comment]
Upon further investigation, it is not top/translateY that cause/fix the issue but the view needs to touch the bottom of the screen (tab bar) or top of the screen (navigation bar) for the safe area to be applied. Is there a way to reapply the safe area guides when moving a view?

**Comment by grahammendick** [comment]
I've got it working. The trick is to change from a `View` to a `SafeAreaView`
```jsx
<SafeAreaView style={transformed ? styles.transformed : styles.normal}>
  <TabBar primary={true}>
    ...
  </TabBar>
</SafeAreaView>
```

**Comment by gabrielbull** [comment]
That made things worst for me. It adds white bars to the top and bottom. But SafeAreaView might be a good place to start looking for a solution, to see how React updates the safe area when a view moves. I'll start looking here when I have some free time: https://github.com/facebook/react-native/blob/351a9f10476160eedc44e9d047f8841df12b86d5/React/Fabric/Mounting/ComponentViews/SafeAreaView/RCTSafeAreaViewComponentView.mm#L57

**Comment by grahammendick** [comment]
Like you say, it's happy if it first renders in the correct place. So I've got a workaround for you.

1. You start off with no transform so that the navigation bar and tab bar are sized correctly.
2. You immediately transform it to the start position of the animation. Do this is in a `setTimeout` of `0` so it runs after the first render.
3. Then you start the transform animation
```jsx
const transformAnim = useRef(new Animated.Value(0)).current 
useEffect(() => {
  setTimeout(() => {
    Animated.sequence([
      Animated.timing( transformAnim,
        { toValue: 100, duration: 0, useNativeDriver: true }
      ),
      Animated.timing( transformAnim,
        { toValue: 0, duration: 3000, useNativeDriver: true }
      )
    ]).start();
  }, 0)
}, [])

``` 
![Screen Recording 2020-06-08 at 10 27 57](https://user-images.githubusercontent.com/1761227/84014944-047f3480-a973-11ea-8c3c-fafa244a8903.gif)
