### ISSUE TITLE
RightBar BarButton ordering is opposite on iOS vs Android

### ISSUE THREAD

**Issue by salockhart** [grahammendick/navigation#442]
Hi,

When I create a `RightBar` with multiple `BarButton`s, the order is reversed on iOS compared to Android.

<img width="616" alt="Screenshot 2020-08-26 at 12 49 38" src="https://user-images.githubusercontent.com/6651364/91303198-9727b680-e79f-11ea-97f8-e2ef30dd7538.png">

This doesn't appear to impact `LeftBar`

<img width="600" alt="Screenshot 2020-08-26 at 12 50 48" src="https://user-images.githubusercontent.com/6651364/91303247-a3ac0f00-e79f-11ea-961c-0dee6ff53d3b.png">

Here's some sample code from those two screenshots, from the zoom sample:

```
<NavigationBar
  title="Color"
  barTintColor={Platform.OS === 'android' ? '#fff' : null}>
  <TitleBar style={styles.titleBar}>
    <Text style={styles.titleBarText}>Color</Text>
    <View style={{backgroundColor: color, width: 28, height: 28}}/>
  </TitleBar>
  <LeftBar>
    <BarButton title="cancel 1" show="always" onPress={() => {
      stateNavigator.navigateBack(1);
    }} />
    <BarButton title="cancel 2" show="always" onPress={() => {
      stateNavigator.navigateBack(1);
    }} />
  </LeftBar>
  <RightBar>
    <BarButton title="cancel 1" show="always" onPress={() => {
      stateNavigator.navigateBack(1);
    }} />
    <BarButton title="cancel 2" show="always" onPress={() => {
      stateNavigator.navigateBack(1);
    }} />
  </RightBar>
</NavigationBar>
```

You can see this on my branch, here: https://github.com/salockhart/navigation/tree/bar-button-order

Any thoughts? It's reasonably trivial for me to get around this, but it's a bit annoying to remember to do.

**Comment by grahammendick** [comment]
Yes, that’s how buttons behave on iOS. It surprised me too. If you add bar button’s A and B on the right then B appears before A. I think it’s because the buttons bar is one long row running from left to right and you’re just adding a new button on the end each time? 

I think I should’ve changed this default behaviour though? Inside `RightBar.ts` I could reverse the child `BarButtons` array on iOS. This didn’t occur to me at the time and now it would be a breaking change. I’m thinking of doing it for the next major release. What do you reckon?

**Comment by salockhart** [comment]
I think I'd go with making the breaking change and have the ordering be consistent across platforms. I think that fits more with the expectations of someone using React Native, for both platforms to be as close to each other as possible.

**Comment by grahammendick** [comment]
Cool, I agree. I don't plan on doing a major release for a while. So, for now, are you ok with reversing the right bar buttons in your code?

**Comment by salockhart** [comment]
Yep that's no issue at all. Thanks for your input!

**Comment by grahammendick** [comment]
Great, thanks. As always, you're welcome to do the PR if you want. But I won't be able to merge it until work for next major is underway

**Comment by salockhart** [comment]
More than happy to do the PR, but I'll likely wait so that it isn't sitting. Feel free to ping me here when work starts for the next major, and I'll gladly take on this issue.

**Comment by grahammendick** [comment]
Nice one, ta!

**Comment by grahammendick** [comment]
@salockhart I'm working towards the next major. Let me know if you're still interested in picking this up

**Comment by salockhart** [comment]
Hey @grahammendick, sure I would be happy to. Do you have a `next` branch I can target?

**Comment by grahammendick** [comment]
Great, thanks! It's all going into `master`
