### ISSUE TITLE
SEO-related question regarding dynamic routes in SSR apps

### ISSUE THREAD

**Issue by arunmenon1975** [grahammendick/navigation#444]
A new app that i am working on is planned to be SSR/Isomorphic by design, primarily for the obvious SEO gains. 

My app may be a simple implementation that has a homepage, an about, a contact and some additional pages like say, Subject 1, Subject 2 and Subject3 , all of them requiring unique URL addresses. I initially created separate scenes tied to the state key:

```
....
const stateNavigator = new StateNavigator([
         {key: 'home', route: '',},
         {key: 'subject1', route: 'subject1', trackCrumbTrail: true},
         {key: 'subject2', route: 'subject2', trackCrumbTrail: true},
         {key: 'subject3', route: 'subject3', trackCrumbTrail: true},
         {key: 'about', route: 'about', trackCrumbTrail: true},
         {key: 'contact', route: 'contact', trackCrumbTrail: true},
    ], new MobileHistoryManager(buildStartUrl, ''));
.....

    home.renderScene = () => <Home />;
    subject1.renderScene = () => <Subject1 />;
    subject2.renderScene = () => <Subject2 />;
    subject3.renderScene = () => <Subject3 />;
     about.renderScene = () => <About />;
     contact.renderScene = () => <Contact />;

```
I then had the idea to actually allow the user to create dynamic routes (through an Admin interface) for Subject1, Subject2 and Subject 3 and any other page via a single scene:

`    
          {key: 'page', route: '{pageSlug?}', trackCrumbTrail: true},
.....

         page.renderScene = (page) => {return <Page data={page} />};
`
So a link in the homepage for any of the subject(or other new pages) pages(defined as objects in the DB) may read:

```
....
                       {
                            pages.map(page => {
                                const key = Object.keys(page)[0]
                                return (
                                    <p key={key}>
                                         <NavigationLink
                                             stateKey="page"
                                             navigationData={{pageSlug: Object.values(page)[0].pageSlug}}>
                                {Object.values(page)[0].title}
                            </NavigationLink>
                                    </p>
                                )
                            })
                        }
....
```

This allows for getting the dynamic routes (/subject1, /subject2, /any-user-created-route etc etc}.

My question is will this dynamic-route approach adversely effect SEO optimisation when compared to the earlier approach of having individual routes that are rendered via `renderScene`? Ideally i prefer the dynamic route approach since i can now have an admin interface one level above and allow the user to create 'pages' (with a 'slug' property for defining the route name) not necessarily pre-defined.

**Comment by grahammendick** [comment]
I'm glad you've chosen the Navigation router for your new app. Does that mean the native app you were working on is live now?

Your approach will have no adverse impact on SEO. To a web crawler your app will look exactly the same in both approaches. The web crawler looks for Hyperlinks and isn’t concerned with how they’re built.

**Comment by arunmenon1975** [comment]
> Does that mean the native app you were working on is live now?

Actually there are two native apps. Both are in various stages of completion but still needs some more work. Ive shelved them for now since this particular SSR app is slightly urgent. I will be back on them as soon as i complete this, which should hopefully be within a couple of weeks. 

In fact i may even consider a native app, as a companion to the SSR app, that is purely admin-focussed and with just a few common admin workflows built in. This Android version may need to be side-loaded since the target users are very few, probably just one or two and thus needn't be published publicly.

> The web crawler looks for Hyperlinks and isn’t concerned with how they’re built.

That was my understanding as well. But just had a niggling doubt. Very obviously i guess will also have to resort to some SEO-specific techniques as well , probably even use `react-helmet` since it is SSR-ready as well.
