### ISSUE TITLE
can't use hooks inside of component. 

### ISSUE THREAD

**Issue by a-eid** [grahammendick/navigation#458]
I'm experimenting with the library ( Great effort by the way ).
however I'm somehow unable to use `React.useContext` inside of screen component. 

![Screen Shot 2020-10-25 at 1 51 50 PM](https://user-images.githubusercontent.com/19273413/97106277-3c400c00-16c9-11eb-87a0-1e7b048ba7be.png)

```js 
export const stateNavigator = new StateNavigator([
  {key: 'hello'},
  {key: 'world', trackCrumbTrail: true},
]);

const {states} = stateNavigator;

states.hello.renderScene = Hello;
states.world.renderScene = World;
```

```js

function Hello(){
  React.useContext(...)
  ///
}

```

**Comment by grahammendick** [comment]
Hey there, thanks for trying the Navigation router and for getting in touch. Change the `renderScene` as follows and you’re good to go
```jsx
states.hello.renderScene = () => <Hello />;
```

**Comment by a-eid** [comment]
@grahammendick thank you, what would be your suggestion to handle the structure of the navigation screens. 

because I think using 

``tsx
states.hello.renderScene = () => {
  const {stateNavigaton} = React.useContext(NavigationContext);

  return null; //
};
``

does not work either.

**Comment by grahammendick** [comment]
This is what you're after
```jsx
states.hello.renderScene = () => <Hello />;

function Hello() {
  const {stateNavigaton} = React.useContext(NavigationContext);

  return null;  //
};
```

**Comment by a-eid** [comment]
@grahammendick thank you.

**Comment by grahammendick** [comment]
No problem. Happy I could help
