### ISSUE TITLE
weird stack navigation transition on android. 

### ISSUE THREAD

**Issue by a-eid** [grahammendick/navigation#459]
I'm having this issue when trying out the example on android simulator

![Oct-25-2020 13-55-31](https://user-images.githubusercontent.com/19273413/97106369-c5efd980-16c9-11eb-89f8-d32cba523a2a.gif)

**Comment by grahammendick** [comment]
What you’re seeing is the default android animation. You can change this to whatever animation you want. For example, to slide the new screen in and out you set the `unmountStyle` prop on the stack. 
```js
<NavigationHandler stateNavigator={stateNavigator}>
  <NavigationStack unmountStyle={from => from ? 'slide_in' : 'slide_out'} />
</NavigationHandler>
```
You must create the 'slide_in' and 'slide_out' animation resources inside the android project. The 'slide_in' animation might look like
```xml
<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android">
  <translate
    android:duration="300"
    android:fromXDelta="100%"
    android:toXDelta="0" />
</set>
```
I’ve documented [how to add custom animation](https://grahammendick.github.io/navigation/documentation/native/custom-animation.html) or you can take a look at the [medley sample](https://github.com/grahammendick/navigation/tree/master/NavigationReactNative/sample/medley) that has a different animation for each screen in the stack. 

If you're not sure about any of the steps then please let me know.

**Comment by a-eid** [comment]
that's pretty cool, thank you. 

the parent screen translates up abit when navigating, is that normal ? 

also what is the max duration there is to the animation when I have a `1000ms` the parent screen seems to unmount. 

![Oct-25-2020 14-47-06](https://user-images.githubusercontent.com/19273413/97107596-056df400-16d1-11eb-8e67-d7efe642e983.gif)

**Comment by grahammendick** [comment]
You can customise the animation of the parent screen using the `crumbStyle` prop. It sounds like you want to turn off the default animation, so just return an empty string

```jsx
<NavigationHandler stateNavigator={stateNavigator}>
  <NavigationStack
    unmountStyle={from => from ? 'slide_in' : 'slide_out'}
    crumbStyle={() => ''}  />
</NavigationHandler>
```

**Comment by a-eid** [comment]
hmmm, I'm still getting the same black screen with that bit of top translation. on android. 

on IOS everything seems great so far. :tada:

**Comment by grahammendick** [comment]
Oops, I got that wrong.

The parent screen disappears as soon as its animation finishes. So if you want the parent screen to stay there without moving while the new screen animates in, then you need to create an empty animation that lasts for 1000ms in your case. For example, you create an animation resource called 'empty' that looks like
```xml
<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android">
    <alpha android:duration="1000"/>
</set>
```
And then you point it at from the `crumbStyle` prop
```jsx
<NavigationStack
  unmountStyle={from => from ? 'slide_in' : 'slide_out'}
  crumbStyle={from => from ? '' : 'empty'} />
```

**Comment by a-eid** [comment]
work great, I'm highly considering contributing to as well as using this library in future project.

great work thank you. :rocket:

**Comment by grahammendick** [comment]
That's great to hear!
