### ISSUE TITLE
Hidden NavigationBar not respected after selecting a search result in SearchBar

### ISSUE THREAD

**Issue by salockhart** [grahammendick/navigation#461]
I have a use case where after tapping on a result in a list, either regularly or as the result of a search, I need to navigate to a screen with no navigation bar.

Tapping on an item regularly works fine - the nav bar is hidden.

Tapping on an item that appears after search, though, fails to hide the nav bar.

Here is an example:

![search-hidden-nav-bar](https://user-images.githubusercontent.com/6651364/97862036-9a3da680-1cfc-11eb-8f5e-03387f13fc87.gif)

To reproduce, set `<NavigationBar hidden />` in the Detail file for the zoom example.

Any thoughts?

**Comment by grahammendick** [comment]
Thanks for raising this. I've fixed it in #463. Can you give it a test, please?

**Comment by salockhart** [comment]
Absolutely, thanks!

**Comment by salockhart** [comment]
@grahammendick works flawlessly, thanks for the fix!

**Comment by grahammendick** [comment]
Thanks, it was an interesting one!
