### ISSUE TITLE
[iOS] SearchBar improperly renders Child Component in Landscape Mode

### ISSUE THREAD

**Issue by ndco** [grahammendick/navigation#467]
Hi,
There is some weird display issue we are encountering while using `SearchBar` in iOS.
From `SearchBar` it re-renders child component and we noticed the child component is not displaying properly if the `View` or `SafeAreaView` component is added.

Here I took the sample app: `redux` and added following
- Added `SearchBar` in `People`
- Wrapped `FlatList` to `SafeAreaView`
- Added wrapped view component under `SearchBar` as child component

And here is how it's displayed in landscape mode:
![Simulator Screen Shot - iPhone 11 - 2020-11-16 at 14 16 46](https://user-images.githubusercontent.com/20120114/99297536-64c5ac80-2816-11eb-93bc-8d2c965234eb.png)

After tapping couple times of SearchBar, the view renders properly.  I have attached video as well.
[SampleVideo.mov.zip](https://github.com/grahammendick/navigation/files/5549146/SampleVideo.mov.zip)

Please let me know if you need any more information

**Comment by grahammendick** [comment]
Hey, thanks for getting in touch and for choosing the Navigation router.

Could you check that the [zoom example](https://github.com/grahammendick/navigation/tree/master/NavigationReactNative/sample/zoom) works ok for you, please? It renders a `SearchBar` component on the first scene.

You don’t need to wrap a `FlatList` in a `SafeAreaView`. You should set the `contentInsetAdjustmentBehavior` prop of the `FlatList` to "automatic" like I’ve done in the zoom example.

**Comment by ndco** [comment]
Hi - thank you for quick response! 
Yeah let me give that a try and will let you know shortly

**Comment by ndco** [comment]
Hi @grahammendick so I took the example from zoom and I noticed something differently.
So in zoom with landscape mode, I can see that the list of `Colors` showed little closer to the notch in iPhone 11 (which is the the issue that I am having) so that we wanted to set the boundary to the `SafeAreaView`.

You may not see this in screenshot but what essentially wanted to achieve is to set Grid aligned with SearchBar (right now this goes beyond)
![Simulator Screen Shot - iPhone 11 - 2020-11-16 at 15 28 00](https://user-images.githubusercontent.com/20120114/99305457-d0614700-2821-11eb-9814-ec0a6f12c0f8.png)

Now here was something interesting that it was different from mine.  For our project, we used `FlatList` that goes into `SearchBar` and here in example had regular `ScrollView` with individual color component View of `TouchableHighlight`.

When I updated this from `View` to `SafeAreaView` - I was able to achieve proper landscape display without any image breaking.

Do you think is this something to do with `FlatList` that might have caused some issue? FYI - I have same prop  `contentInsetAdjustmentBehavior` set to `true` but the issue still remained.

**Comment by grahammendick** [comment]
Thanks for testing that out and for your detailed response.

I know what you mean about the notch being a bit close. I found a react native issue about the [ScrollView in landscape not handling insets when contentInsetAdjustmentBehavior is on](https://github.com/facebook/react-native/issues/19984). Looks like they ended up doing the same as you and [embedded the SafeAreaView inside the ScrollView](https://github.com/facebook/react-native/issues/19984#issuecomment-425338781). They noticed it didn’t work for FlatList, too :)

**Comment by ndco** [comment]
Thank you @grahammendick for your findings and help! I noticed they have set `contentInsetAdjustmentBehavior` to `always` instead of `automatic`

That solved alignment only one leftside and then the bar goes beyond the screen to the right... :(
Think we will investigate more on this but it turned out that this isn't the issue from here :)

Thank you again for your help! Will close this issue

**Comment by grahammendick** [comment]
No problem, glad I could help
