### ISSUE TITLE
Adding native UIViewController / Fragment guidelines

### ISSUE THREAD

**Issue by iamyellow** [grahammendick/navigation#472]
Hey! thanx for this amazing library :)
Is there any way or approach in order to integrate an external UIViewController (ios) or Fragment (native) from another library. It's not uncommon to find native libs out there based where the first step is subclass their VC / Fragment. Obviously we need to do it somehow in native land (from a custom module).
Thanks!

**Comment by grahammendick** [comment]
Hey, thanks for the nice words. I'm so glad you're enjoying the Navigation router!

Could you give me an example use-case, please? I think it'll make it easier to start the chat around a specific feature you want to add to your app

**Comment by iamyellow** [comment]
hey! thanks for your fast answer :)
i'd like to integrate these Chat UI library:
https://github.com/stfalcon-studio/ChatKit (android)
https://github.com/little2s/NoChat (iOS)

the android counterpart it's easy since they're all pure views (no fragments, no activities), but let's suppose we have Fragments instead of View/ViewGroup. 
the iOS one exposes a UIViewController subclass with all the logic.

it'd be really nice having something like the external component thing in `react-native-navigation`: 
https://wix.github.io/react-native-navigation/docs/externalComponent/

**Comment by grahammendick** [comment]
How would you incorporate the Chat `UIViewController` using the external component from react native navigation? How would you send typed text back to React, for example?

**Comment by iamyellow** [comment]
I tried that (for another project) in the past. you can do something like this:
https://github.com/wix/react-native-navigation/blob/13f5953ffc73187a81bcf37ef275d65b04deda7a/website/versioned_docs/version-7.0.0/docs/docs-externalComponent.mdx
passing simple props (strings, numbers, etc.) from js to native land is straightforward, passing callbacks for events -something like `onMessageSent`, and if I recall correctly, was not that direct, I guess we managed it with some sort of event emitter approach.

**Comment by grahammendick** [comment]
So you modified the iOS Chat library source code?

**Comment by iamyellow** [comment]
no, the chat ui integration it's about to happen, we're not quite there yet, just exploring how we're going to do it.
what i did in the past, for another project, was use the RNN external component. 

anyway, the idea is to not modify external libs. let's make it simple... figure out that in the past you've developed a UIViewController and Fragment with some amazing whatever feature hard enough to be redone in vainilla RN. how would you do it? Even step by step: first using the VC/Fragment, then maybe pass a prop with the bg color and 3rd passing some more complex stuff like a callback for events, though it could be done with an event emitter approach.

**Comment by grahammendick** [comment]
Let's stay focused on the chat example. Can you tell me how you use the RNN external component without modifying the source code, please? It would be great if you could show me how you send the typed text back to React.

**Comment by iamyellow** [comment]
in ios i'd subclass the NoChatViewController as they do on the example:
https://github.com/little2s/NoChat/blob/master/Example/Example/SimpleChatViewController.swift

in RNN I'd register an external component wirh the previous VC subclass and passProps from js with a callback for onInputTextChange.

**Comment by grahammendick** [comment]
You can already add a [UIViewController to an existing UIViewController (scene)](https://stackoverflow.com/a/43151057/1310468). So you could create a `Chat` React component that maps to a `ChatView` (iOS `UIView`). The `ChatView` would create the `NoChatViewController` and its view as a subview
```obj-c
[self addSubview:noChatViewController.view];
```

**Comment by grahammendick** [comment]
@iamyellow are you happy with my suggestion?

**Comment by iamyellow** [comment]
hey! sorry for the delay... 
i used to be a pure native developer before move to rn and somehow it feels strange, but it's the way that fits better into rn in order to have the best of the both worlds.
thanks again!
