### ISSUE TITLE
Modal Navigation support. 

### ISSUE THREAD

**Issue by a-eid** [grahammendick/navigation#475]
thanks again for this great lib. 

I did ask you this on twitter and I believe you pointed out that RN builtin Modal could be used. 
I still believe that a navigation modal is well worth it to be included, 
please consider this 

![Nov-24-2020 07-10-14](https://user-images.githubusercontent.com/19273413/100051267-2a669b80-2e24-11eb-87f3-9647e4fc1706.gif)

do you think the lib could support this in the future ?

**Comment by grahammendick** [comment]
Hey, I remember you from Twitter. It's always good to hear from you.

The Navigation router already supports that by adding a `NavigationStack` as a child of a React Native `Modal`.
```jsx
<Modal>
  <NavigationHandler stateNavigator={navigator}>
    <NavigationStack />
  </NavigationHandler>
</Modal>
```
You can read me about this in the ['Navigating in a Modal'](https://grahammendick.github.io/navigation/documentation/native/modal.html) section of the Modal documentation. Or you can see it in action in [the medley sample](https://github.com/grahammendick/navigation/blob/194dd121c17816249efca1cd0365678e818024f9/NavigationReactNative/sample/medley/Direction.js#L61).

**Comment by a-eid** [comment]
@grahammendick good to hear from you as well,
I'm not sure how I missed this on the docs 🥴,
I'm gonna give it a try right now, 

thanks you.

**Comment by a-eid** [comment]
aha, I remember why I was having issues, it's because the RN `Modal` currently have few outstanding issues, hopefully they'll be resolved on the RN64, RC0 is already out.

**Comment by grahammendick** [comment]
Are you thinking of the 'swipe to dismiss' issue of RN `Modal` on iOS 13?

**Comment by a-eid** [comment]
yeah, that's one of the issues.

**Comment by grahammendick** [comment]
What are the others?

**Comment by a-eid** [comment]
I remember that there was an issue with the `onDismiss` prop not being fired after the modal is dismissed.

**Comment by grahammendick** [comment]
Can we close this? We'll keep our eyes on the Modal issues in the React Native repo

**Comment by a-eid** [comment]
@grahammendick 

also: 

I don't think it's yet possible to disable `gesture` on the Modal component from React native. 
while for example you can disable gestures on `react-native-screens/native-stack` formSheet Modal.
