### ISSUE TITLE
Feature Request: Add searchButtonPressed event

### ISSUE THREAD

**Issue by julian-baumann** [grahammendick/navigation#476]
An event for when the user presses the "enter"/"search"-key when using the search-bar.

<div align="center">
<p align="center">
<img src="https://user-images.githubusercontent.com/39265507/100233403-ffff0600-2f29-11eb-8405-551cc5fc68fa.jpg" width=200 />
</p>
</div>

**Comment by grahammendick** [comment]
Like the [onKeyPress of the TextInput](https://reactnative.dev/docs/textinput#onkeypress)? Can you give me an example of when you'd use this event instead of the `onChangeText` event, please?

**Comment by julian-baumann** [comment]
Yeah kinda like that. To recognize when the user is done typing and wants to search. So that I can start a web request for example.
Or is this also possible with the current implementation?

**Comment by grahammendick** [comment]
The current way is to search on type by listening to the `onChangeText` event. Can you give me an example of where you'd prefer the user to hit enter before initiating the search?

**Comment by julian-baumann** [comment]
As I said, when performing fetch requests for example. They can be very heavy.

**Comment by grahammendick** [comment]
I'm not against the idea but I a use-case helps me understand the feature better. I noticed from your screen shot that your search appears in a modal. Is that something to do with it? When they first open the modal, is the screen blank or are there search results?

**Comment by julian-baumann** [comment]
Sorry my example maybe leaked a bit.
No when the modal is opened there is an info box at first, explaining some stuff. My plan was to start a fetch request with the text from the searchbar, when the search-button is pressed, to get some results. 
My current approach is to detect when the user stopped typing by doing something like this:
```ts
let typingTimer: NodeJS.Timeout;

function onChangeTextHandler(text: string): void
{
    if (typingTimer)
    {
       // clear timeout, because a new character was typed
        clearTimeout(this._typingTimer);
    }
    
    typingTimer = setTimeout(async (): Promise<void> =>
    {
        // No new character since 800ms
        // Do a fetch request
        fetch("https://example.com");
    }, 800);
}
```

Since I don't want to fire a fetch-request from a server every time a character is typed. Because it is a bit unnecessary and I don't believe it would be very performant.

So I just thought it would be great to react to such an event when the user presses the "search" button. So that I can react right away and make one single fetch request.


This feature is really not a very hight priority or something, don't get me wrong. The way with Timeouts works too, and is maybe even a better approach. What do you think?

**Comment by grahammendick** [comment]
I think listening to the text changing and throttling with a timer is the expected way that search behaves on native. So in that way it's better. I've got an android phone and my apps behave like that.

Equally, the search typically appears on top of a screen that already displays the list. The search is used as an optional filter - the user could scroll through the list without searching. That's why I was asking about what the modal looked like when first opened. Perhaps if there are no results to start with then the expectations change?

**Comment by julian-baumann** [comment]
I think you are right. I'm closing this issue then. Thanks anyway and sorry for taking your time.

**Comment by grahammendick** [comment]
No problem at all. Happy to chat it over
