### ISSUE TITLE
[IOS] is it possible to disable swipe back gesture ?

### ISSUE THREAD

**Issue by a-eid** [grahammendick/navigation#481]

**Comment by grahammendick** [comment]
The only way currently is to add a left bar button.
```jsx
<LeftBar>
  <BarButton title="Cancel" />
</LeftBar>
```
 This removes the back button so the swipe back is disabled, too.

**Comment by grahammendick** [comment]
Can you tell me why you want to disable the swipe back, please? What is your use-case?

**Comment by a-eid** [comment]
Sometimes you wanna ask the user of they wanna leave the current screen, for example if they have filled a long form or something. And i wanna warn them that those changes will be lost.

**Comment by grahammendick** [comment]
How do you do this in a native iOS app?

**Comment by a-eid** [comment]
I am not actually sure, I'll look around and let u know.

**Comment by grahammendick** [comment]
Have you found out how to do this? Also, could you give me an example iPhone app that does this?

**Comment by a-eid** [comment]
sorry I have not checked this in details, usually using `react-navigation` I just disabled the gesture on that screen & prompt the user when they hit `back`.

**Comment by grahammendick** [comment]
You can achieve the same result by adding a custom back button in the `LeftBar`

**Comment by a-eid** [comment]
yeah, I think this could be handled with react state.

**Comment by grahammendick** [comment]
```jsx
const [edited, SetEdited] = useState(false);
<LeftBar>
  {edited && <BarButton title="Cancel" />}
</LeftBar>
```
