### ISSUE TITLE
[IOS] content is rendered behind the `NavigationBar` ? 

### ISSUE THREAD

**Issue by a-eid** [grahammendick/navigation#482]
```tsx
    <View style={{flex: 1}}>
      <NavigationBar
        barTintColor="transparent"
        title="title"
        titleColor="black"
        backTitle="Back" />

      <View style={{flex: 1, backgroundColor: 'red'}}>
        <Text style={{fontSize: 22}}>TEXT</Text>
      </View>
    </View>
```

![Screen Shot 2020-11-29 at 6 18 23 PM](https://user-images.githubusercontent.com/19273413/100547416-47113200-326f-11eb-99f0-c7758955a63f.png)

shouldn't the text 'TEXT' appear below the `NavigationBar` ? 

also what is the best way in your opinion to find out the height of the `NavigationBar` in case it has a large title & when it doesn't ?

**Comment by grahammendick** [comment]
You need to use the `SafeAreaView` component from React Native

**Comment by a-eid** [comment]
I find `react-native-safe-area-context` works better than the one exported in react native, I'll try that and let you know if it works.

**Comment by a-eid** [comment]
great, it seem to be working well, thank you.
