### ISSUE TITLE
[IOS] large title starts off hidden or in normal title state ?

### ISSUE THREAD

**Issue by a-eid** [grahammendick/navigation#484]
as if there is some `contentOffset` applied. 

![Nov-29-2020 19-18-01](https://user-images.githubusercontent.com/19273413/100548826-aecb7b00-3277-11eb-947e-db363f504ebf.gif)

**Comment by grahammendick** [comment]
This only happens in iOS 14. The large title starts off expanded in iOS <= 13.

I know how to fix it but it involves a change `RCTScrollContentView` class in React Native. Open your project in XCode and paste this code into `RCTScrollContentView` 

```obj-c
@implementation RCTScrollContentView

- (void)didMoveToWindow
{
    [super didMoveToWindow];
    RCTScrollView *scrollView = (RCTScrollView *)self.superview.superview;
    [scrollView updateContentOffsetIfNeeded];
}

- (void)reactSetFrame:(CGRect)frame
{
  [super reactSetFrame:frame];

  RCTScrollView *scrollView = (RCTScrollView *)self.superview.superview;

  if (!scrollView || !self.window) {
    return;
  }

  RCTAssert([scrollView isKindOfClass:[RCTScrollView class]], @"Unexpected view hierarchy of RCTScrollView component.");

  [scrollView updateContentOffsetIfNeeded];
}

@end
```
React Native Screens has the same issue and [I provided them with this same fix](https://github.com/software-mansion/react-native-screens/issues/649#issuecomment-712199895). You can see from the issue comments that it has worked for everybody that has tried it.

I don't plan on submitting a PR to React Native because they won't look at it. I find the process too frustrating to engage with. But if you want to submit a PR to React Native on behalf of the Navigation router then that would be great.

If the fix works for you then you could [use patch-package](https://github.com/software-mansion/react-native-screens/issues/649#issuecomment-727553714) to apply it?

**Comment by a-eid** [comment]
@grahammendick it kinda behaves strongly now. 

- it renders as a large title then it disappears and appears as a normal one.
- ( not sure if the is related ), you can see the barTintColor changes, kinda flickering when the large title is about to get hidden. 

![Nov-29-2020 19-50-59](https://user-images.githubusercontent.com/19273413/100549551-3adfa180-327c-11eb-98de-3e80e7ce65a9.gif)

**Comment by grahammendick** [comment]
Thanks, I didn't try it on the second screen. That's still only is iOS 14, right?

**Comment by a-eid** [comment]
yeah, I'll test on IOS 13 after I complete some other tests 👍 .

**Comment by grahammendick** [comment]
I just tried it in the zoom example and it works on both first and second screen with my fix in. (I changed the zoom sample to navigate from grid to grid so I could have large title on both screens). You should check that you've set your screen up to match the zoom sample
![Screen Recording 2020-11-29 at 17 59 14](https://user-images.githubusercontent.com/1761227/100549763-db2dca00-326c-11eb-962d-768d238fe084.gif)

**Comment by a-eid** [comment]
I see that you have 2 nested `ScrollView`s is that required ?

**Comment by grahammendick** [comment]
Yes

**Comment by a-eid** [comment]
- still doesn't work.
- `FlatLists` don't work correctly inside of a `ScrollView`, how do u suggest to resolve that ?

![Screen Shot 2020-11-29 at 8 18 49 PM](https://user-images.githubusercontent.com/19273413/100550079-1980b480-3280-11eb-9fcd-68dceb78a7a2.png)

**Comment by grahammendick** [comment]
Please try the zoom example with [my fix applied](https://github.com/grahammendick/navigation/issues/484#issuecomment-735428371).

**Comment by a-eid** [comment]
@grahammendick I will, how about the `barTintColor` flickering above, should I file an issue for that ?

**Comment by a-eid** [comment]
@grahammendick also how about the `FlatList`, 

I found out why it wasn't working for me, 

I'm using an absolutely positioned element outside the `ScrollView` which seem to be causing the issue somehow.

**Comment by grahammendick** [comment]
The [large title changed from translucent to transparent in iOS 13](https://sarunw.com/posts/uinavigationbar-changes-in-ios13/). So the barTint color change is expected

You can safely ignore the FlatList warning. The outer ScrollView doesn't really scroll so shouldn't impact the nested FlatList

**Comment by a-eid** [comment]
it's fine however a bit weird, it doesn't happen on the Settings app on IOS.

how would u go about positioning an element absolutely to the bottom of the screen, give the example above ?

**Comment by a-eid** [comment]
> The large title changed from translucent to transparent in iOS 13. So the barTint color change is expected

the flickering does happen even when there is no large title. 

![Uploading Nov-29-2020 21-05-57.gif…]()

**Comment by a-eid** [comment]
also it does seem to work without the outer,`ScrollView` is it safe to use it without it ?

**Comment by grahammendick** [comment]
The `scrollEdgeAppearance` is what changed from translucent to transparent. That takes effect when there's a search bar and/or large title.  It's possible to change the `scrollEdgeAppearance` in iOS but not yet in the Navigation router.

I don't think it does work without the outer `ScrollView`. Put a button at the bottom of the blue band in your example and check you can press it

**Comment by a-eid** [comment]
> I don't think it does work without the outer ScrollView. Put a button at the bottom of the blue band in your example and check you can press it

it does seem to work.

**Comment by grahammendick** [comment]
Can you update to navigation-react,-native version >= 7.2.0 and see how the barTint behaves, please?

**Comment by grahammendick** [comment]
Also, can you show me your layout without the outer ScrollView, please?

**Comment by a-eid** [comment]
> Can you update to navigation-react-native version >= 7.2.0 and see how the barTint behaves, please?

same behavior.

**Comment by a-eid** [comment]
> Also, can you show me your layout without the outer ScrollView, please?

```tsx
<View style={{flex: 1}}>
  <FlatList
    style={{flex: 1}}
    keyExtractor={(item) => item}
    contentInsetAdjustmentBehavior="automatic"
    nestedScrollEnabled
    ListHeaderComponent={
      <NavigationBar
        barTintColor="white"
        tintColor="#F4801A"
        title="Items"
        titleColor="black"
        largeTitle
        backTitle="Menu">
        <StatusBar tintStyle="dark" />
        <SearchBar hideWhenScrolling onChangeText={onSearchTextChange} />
        <RightBar>
          <BarButton
            title={editing ? 'Select' : 'Cancel'}
            onPress={handleEditPress}
          />
        </RightBar>
      </NavigationBar>
    }
    data={['red', 'green', 'blue', 'black', 'white', 'pink']}
    renderItem={renderItem}
  />
</View>;
```

**Comment by grahammendick** [comment]
The FlatList counts as an outer ScrollView (an outer UIScrollView)

**Comment by grahammendick** [comment]
> it's fine however a bit weird, it doesn't happen on the Settings app on IOS.

Can you show me the difference in behaviour of the barTint between the Navigation router and the Settings app, please?

**Comment by grahammendick** [comment]
Are you happy if we close this because the large title issue is working?
But please raise a separate issue for the barTint problem - include screenshots that shows the problem, please

**Comment by a-eid** [comment]
@grahammendick Sure, thanks you. 
I'll close it.

**Comment by grahammendick** [comment]
Don't forget to raise the barTint issue with screenshots, please?

**Comment by grahammendick** [comment]
@a-eid Does the flash still happen if you remove the `barTintColor` prop?

**Comment by a-eid** [comment]
@grahammendick really sorry, can't currently test it, I'll do another patch of testing on Friday night if you want. 

I'm actually trying to recreate an app that I've built with `react-navigation` & `react-native-screens/native-stack`.

**Comment by grahammendick** [comment]
No problem, whenever you have time.

> I'm actually trying to recreate an app that I've built with react-navigation & react-native-screens/native-stack.

That's interesting. Let me know how it goes

**Comment by fabOnReact** [comment]
This issue can be solved by creating your own implementation of ScrollView based on react-native APIs. https://github.com/fabOnReact/react-native-improved
