### ISSUE TITLE
[IOS] SearchBar triggers `onChangeText` when Input is focused or blurred ?

### ISSUE THREAD

**Issue by a-eid** [grahammendick/navigation#485]
```tsx
    <NavigationBar
      barTintColor="white"
      tintColor="#F4801A"
      title="Items"
      titleColor="#F4801A"
      largeTitle
      backTitle="Menu">
      <SearchBar hideWhenScrolling onChangeText={onSearchTextChange} />
    </NavigationBar>
```

`onSearchTextChange` is triggered whenever the searchBar is focused or blured.

I think it should only trigger when the text of the input changes, as suggested by the prop name.

**Comment by grahammendick** [comment]
Here's an example of how the search could work. The `useEffect` only fires when the search text changes.
```js
const [text, setText] = useState('');
useEffect(() => {
  // do search
}, [text]);
<SearchBar
  onChangeText={setText}>
```
It's called `onChangeText` to match the [similar event on the TextInput from React Native](https://reactnative.dev/docs/textinput#onchangetext). Although I agree they behave slightly differently.

If you're not happy with how it works can you please tell me what it it s you're trying to do and explain why it's not working.

**Comment by a-eid** [comment]
ideally it would be similar to the `TextInput` from react native to avoid confusion. 

there is a new props `onPressIn` & `onPressOut` props that recently added `63.4` or `64` I'm not sure.

![Screen Shot 2020-12-10 at 7 42 19 AM](https://user-images.githubusercontent.com/19273413/101726466-3d7f9980-3abb-11eb-8662-c674fec250a7.png)

**Comment by grahammendick** [comment]
I'm going to close this but we can always reopen if you can explain what bug is happening in your code because of the `SearchBar`. For example, you should phrase it something like "I'm trying to do x but I can't because of y in the `SearchBar` component". That way it gives me something concrete to investigate, thanks

**Comment by a-eid** [comment]
I mean `onChangeText` should only trigger when the text inside is changed, shouldn't it, same as the built in `TextInput`. 

but it's fine, we can always do this check in js.
