### ISSUE TITLE
[IOS] StatusBar doesn't seem to working correctly ?

### ISSUE THREAD

**Issue by a-eid** [grahammendick/navigation#486]
when rendering a `StatusBar` directly it doesn't work ( as in it doesn't change the `barStyle` at all.

neither does 

```ts
  useNavigated(() => {
    StatusBar.setBarStyle('dark-content');
  });
```

**Comment by grahammendick** [comment]
Are you talking about the `StatusBar` from the Navigation router or the one from React Native?

**Comment by a-eid** [comment]
nope, the one from `react-native`.

**Comment by grahammendick** [comment]
Use the `StatusBar` from the Navigation router instead. Render it inside the `NavigationBar` component
```jsx
<NavigationBar>
  <StatusBar tintBarStyle="dark" />
</NavigationBar>
```

**Comment by a-eid** [comment]
it works indeed, thank you.

```ts
<StatusBar tintStyle="dark" />
```

I would say this should be documented.

**Comment by grahammendick** [comment]
Agreed, didn't realise I'd impacted the React Native StatusBar. I'll keep this open until I've documented the Navigation router StatusBar
