### ISSUE TITLE
should `react-native-screen` `enableScreens` be used with this lib at all ?

### ISSUE THREAD

**Issue by a-eid** [grahammendick/navigation#487]
out of curiosity, does `enableScreen` have any impact when used with this lib ?

**Comment by grahammendick** [comment]
You want to use the Navigation Router and react-native-screens together?

**Comment by a-eid** [comment]
No, just 

```ts
import { enableScreens } from 'react-native-screens';
enableScreens();
```

I know it's recommended to use it with `react-navigation` & `wix/react-native-navigation`.

so I'm just asking if there is any benefit at when including it.

**Comment by grahammendick** [comment]
No, enableScreens isnt relevant
