### ISSUE TITLE
A NavigationBar that contains largeTitle or a SearchBar flashes a transparent black color while scrolling.

### ISSUE THREAD

**Issue by a-eid** [grahammendick/navigation#491]
![Dec-05-2020 08-34-22](https://user-images.githubusercontent.com/19273413/101235855-b904d380-36d4-11eb-81c2-a35c27e5369c.gif)

you can see this doesn't happen on the settings app for example.

![Dec-05-2020 08-36-50](https://user-images.githubusercontent.com/19273413/101235895-18fb7a00-36d5-11eb-8fb7-b68f41e84ad3.gif)

- I think whenever the navigation is scrollable this happens. 
- just noticed that it only happens on dark mode too.

code snippet. 

```tsx
    <NavigationBar
      barTintColor="white"
      tintColor="#F4801A"
      title="Items"
      titleColor="black"
      largeTitle
      backTitle="Menu">
      <StatusBar tintStyle="dark" />
      <SearchBar
        hideWhenScrolling
      />
      <RightBar>
        <BarButton
          title="Select"
          onPress={() => {}}
        />
      </RightBar>
    </NavigationBar>
```

**Comment by grahammendick** [comment]
Fixed this in #489 and released it navigation-react-native 7.2.0. I use an opaque background when the `barTintColor` is set
