### ISSUE TITLE
[IOS] large title does not work with a custom TitleBar component. 

### ISSUE THREAD

**Issue by a-eid** [grahammendick/navigation#493]
I'm not sure if this the way it should work or a bug, I just thought I'm mention it, I wanted to display an icon alongside the large title text.

when providing a `TitleBar` with largeTitle: 
- the large title doesn't show any thing. 
- the space for the large title seem to be preserved. 

it works great as normal title bar thou. 

```
    <NavigationBar tintColor="#F4801A" largeTitle backTitle="Menu">
      <StatusBar tintStyle={tintStyle} />
      <TitleBar>
        <View style={{flexDirection: 'row', alignItems: 'center'}}>
          <Image
            resizeMode="cover"
            style={{width: 25, height: 20}}
            source={require('./assets/logo.png')}
          />
          <Text style={{color: secondaryColor, paddingLeft: 8}}>Items</Text>
        </View>
      </TitleBar>
    </NavigationBar>
```

- if you provide a `title` to the `NavigationBar` it would would show, but the <TitleBar /> still would show the normal title.

**Comment by grahammendick** [comment]
Here's the zoom example with a `TitleBar` and large titles working together (I copied the TitleBar from the Detail scene and pasted it into the Grid scene).

![Screen Recording 2020-12-06 at 16 15 21](https://user-images.githubusercontent.com/1761227/101285684-6c0d2400-37de-11eb-8421-5d356a45df39.gif)

**Comment by a-eid** [comment]
I meant that the large title should not probably show with the normal bar title, one should animate out while the other animate in.

**Comment by grahammendick** [comment]
This is the standard iOS behaviour
