### ISSUE TITLE
[question] does it support RTL ? 

### ISSUE THREAD

**Issue by a-eid** [grahammendick/navigation#495]
I was wondering if this does or has any plans to support RTL languages in the future ?

**Comment by grahammendick** [comment]
The Navigation router already supports RTL languages

**Comment by a-eid** [comment]
is there any documentations that I can checkout ?

**Comment by grahammendick** [comment]
Follow the React Native documentation for [RTL layout support](https://reactnative.dev/blog/2016/08/19/right-to-left-support-for-react-native-apps). There' a nothing specific you need to do in the Navigstion router

**Comment by a-eid** [comment]
thank you.

**Comment by grahammendick** [comment]
No problem. Thanks for the question
