### ISSUE TITLE
Performance compared with RNN

### ISSUE THREAD

**Issue by aliraza-noon** [grahammendick/navigation#507]
Hey there, really interesting project wonder how does this compare with RNN in terms of performance do you have any numbers ? 

I briefly looked at the code I know its not much different from RNN but I see you mount single rootview where as RNN mounts rootview for each screen

my only concern with RNN is api I like declarative api even your library does not offer 100% declarative apis but still better than RNN IMO.

**Comment by grahammendick** [comment]
Thanks for getting in touch. It's great to hear from you.

You're right about a couple of the differences between the Navigation router and RNN. The Navigation router mounts a single root so you can share data between screens using React Context. The Navigation router provides components so you can build your screens declaratively, for example, the `TabBar` and `NavigationBar`. But there are lots of other differences, too.
1. There's no native setup. You [install the 3 navigation packages from npm](https://grahammendick.github.io/navigation/documentation/native/setup.html) and you’re good to go
2. The render happens in JavaScript before the navigation happens in native. This copies the behaviour of 'real' native apps
3. The stack of screens is available in JavaScript. So you can see which screens are already open, for example, and use this to decide whether to pop or push
4. It works with the built-in React Native `Modal` component. Having the `Modal` as a child means you can use React props to communicate back to the parent screen
5. All components render to the native primitive on both platforms. For example, the `TabBar` component renders to a [BottomNavigationView](https://developer.android.com/reference/com/google/android/material/bottomnavigation/BottomNavigationView) on Android
6. It uses `Fragments` for navigating on Android. This is the native navigation primitive so it can plug into the native animation that runs for the entering and exiting screens
7. It has fluent navigation so you build a stack as many screens deep as you want and only the top one renders. The others don't render until you pop to them. This comes in handy for deep linking, for example
8. It works on the web. The [twitter sample](https://github.com/grahammendick/navigation/tree/master/NavigationReactNative/sample/web/twitter) shows a single code-base running on Android, iOS and the web

**Comment by aliraza-noon** [comment]
I observed some of the things you mentioned while browsing the through code e.g. fragments, shallow screen stack, was wondering how is the performance did you ever get change to do some benchmarks ?

**Comment by grahammendick** [comment]
No benchmarks but hopefully you can see that most of the differences I listed relate to performance

**Comment by grahammendick** [comment]
Closing, but leave a comment if you want to know more
