### ISSUE TITLE
Navigation bar sticky content. 

### ISSUE THREAD

**Issue by caciobanita** [grahammendick/navigation#511]
Hello.

I have to questions about your navigation library. 
I what to have a navigation bar witch's hides on scroll, i have used coordinated layout and is working awesome (better then RNN).

1. The navigation bar is also hides on iOS?
2. I can i have a view who is sticky on navigatio bar, like tab bar. Is supported?

**Comment by grahammendick** [comment]
Really great to hear from you! I’m glad you like the `CoordinatorLayout`.

1. The Navigation router wraps the underlying native functionality on Android and iOS. If the functionality isn’t provided natively then the Navigation router doesn’t offer it. Android natively supports collapsing the navigation bar but iOS doesn’t. So the `CoordinatorLayout` component only works on Android.
2. You can make the `TabBar` sticky on Android by wrapping it in the `NavigationBar` inside a `CoordinatorLayout`. You can read about this in the [Scrolling the Navigation Bar section of the TabBar docs](https://grahammendick.github.io/navigation/documentation/native/tab-bar.html). You can see it in action in [the Notifications screen of the Twitter sample](https://github.com/grahammendick/navigation/blob/406a3fdeeded806aed90a24f5700fcd440a252cb/NavigationReactNative/sample/twitter/Notifications.js#L15). Or were you asking if you can make any other view sticky too?

**Comment by caciobanita** [comment]
> Really great to hear from you! I’m glad you like the `CoordinatorLayout`.
> 
> 1. The Navigation router wraps the underlying native functionality on Android and iOS. If the functionality isn’t provided natively then the Navigation router doesn’t offer it. Android natively supports collapsing the navigation bar but iOS doesn’t. So the `CoordinatorLayout` component only works on Android.
> 2. You can make the `TabBar` sticky on Android by wrapping it in the `NavigationBar` inside a `CoordinatorLayout`. You can read about this in the [Scrolling the Navigation Bar section of the TabBar docs](https://grahammendick.github.io/navigation/documentation/native/tab-bar.html). You can see it in action in [the Notifications screen of the Twitter sample](https://github.com/grahammendick/navigation/blob/406a3fdeeded806aed90a24f5700fcd440a252cb/NavigationReactNative/sample/twitter/Notifications.js#L15). Or were you asking if you can make any other view sticky too?

Yes, i what another view to be sticky.

**Comment by grahammendick** [comment]
The way I did it when I implemented it for the TabBar was to work out how to do it in native Android first - without React Native. I found a [tutorial that explained what properties I had to set](https://guides.codepath.com/android/handling-scrolls-with-coordinatorlayout). Then I translated that into React Native. For example, here’s where [I set the `ScrollingViewBehaviour`](https://github.com/grahammendick/navigation/blob/406a3fdeeded806aed90a24f5700fcd440a252cb/NavigationReactNative/src/android/src/main/java/com/navigation/reactnative/CoordinatorLayoutManager.java#L46) that the tutorial talks about.

So, I recommend you do the same. Work out how to get a sticky view in native Android. Then we can translate that into React Native. Have you got any experience with native Android?

**Comment by caciobanita** [comment]
Tanks, my experience with native Android is very low, but i will try your suggestions.

**Comment by grahammendick** [comment]
@caciobanita Do you want a floating action button anchored to the toolbar?

**Comment by grahammendick** [comment]
@caciobanita You should try putting your view inside the `CollapsingBar` component and setting it [CollapsingToolbarLayout mode to pin](https://tpom6oh.medium.com/managing-content-in-collapsingtoolbarlayout-e9afbc91be24). It only takes a bit of java to do this
```java
CollapsingToolbarLayout.LayoutParams params = new CollapsingToolbarLayout.LayoutParams(width, height);
params.setCollapseMode(CollapsingToolbarLayout.LayoutParams.COLLAPSE_MODE_PIN);
view.setLayoutParams(params);
```

**Comment by grahammendick** [comment]
Or, if you wanted to do it in React only then you could listen to the `onOffsetChanged` event of the `NavigationBar` and translate your View. I did something similar in this gist that [parallax scrolls an image as the navigation bar collapses](https://gist.github.com/grahammendick/dee882f52bfaca1085882950f05b84c3)

**Comment by caciobanita** [comment]
I solved this by using stickyHeaderIndices={[0]} and ListHeaderComponent from FlatList, but i cant change the elevation for toolbar. 

I have tried to change elevation in ToolbarView and NavigationBarView files but with no success. Any suggestions?

**Comment by grahammendick** [comment]
Why do you want to change the elevation? Can you show me an image of what you're trying to do?
