### ISSUE TITLE
Text in a custom TitleBar component does not truncate on iOS

### ISSUE THREAD

**Issue by salockhart** [grahammendick/navigation#515]
Hi there!

We are using the `TitleBar` component to build a custom title bar in our app. The main part of this title is a `Text` component, similar to what is in the `zoom` example.

However, for our use case, this text is dynamic/user-generated and can get quite long. When that happens, we cannot truncate the text properly on iOS. From the `zoom` example:

```
<TitleBar style={styles.titleBar}>
  <Text style={styles.titleBarText} numberOfLines={1}>
    Erat curabitur elit cursus est in feugiat gravida, habitant hac
    morbi urna eget per sapien, enim dictum maximus fringilla fames
    suscipit.
  </Text>
  <View style={{backgroundColor: color, width: 28, height: 28}} />
</TitleBar>
```

<img width="300" src="https://user-images.githubusercontent.com/6651364/116125165-11a52f00-a6bd-11eb-905e-5393a5633710.png" />

My expectation is that by setting `numberOfLines={1}` we should get truncated text, as per the docs: https://reactnative.dev/docs/text#numberoflines. This behaviour is present outside of the `TitleBar`.

---

My hunch is that this has something to do about the `TitleBar` not properly reporting its layout to RN. When I set a breakpoint in the `NVTitleBarView` I can see that the frame starts quite large and then shrinks to fit the available space. Maybe RN is not receiving the newly shrunken frame?

For instance, if I add a background to just the `TitleBar`, it doesn't appear to run off the page either:

<img width="300" src="https://user-images.githubusercontent.com/6651364/116125927-f8e94900-a6bd-11eb-8860-2acf9cf7df68.png" />

and the Layout Inspector seems to confirm that:

<img width="511" alt="Screenshot 2021-04-26 at 18 34 45" src="https://user-images.githubusercontent.com/6651364/116126033-13bbbd80-a6be-11eb-8ed0-975966258fbe.png">

As a way of hacking around it, I attempted to add an `onLayout` prop to the `TitleBar`. However, it only receives one event - and it's the original big frame, not the "shrunken frame".

---

I will dig into this some more, but please do let me know if you have any ideas!

**Comment by grahammendick** [comment]
Hey there, that's an interesting one! Thanks for all the detail and screenshots.

>> My hunch is that this has something to do about the TitleBar not properly reporting its layout to RN.

Your hunch makes a lot of sense to me. Could you tell RN to update the TitleBar layout when the frame changes by calling the [setSize method on the bridge](https://github.com/grahammendick/navigation/blob/ddce9b89cedf325d75a19b933e433d02759353e8/NavigationReactNative/src/ios/NVSearchBarView.m#L81)?

**Comment by salockhart** [comment]
Thanks for the tip! I knew what I wanted to do but didn't have a good example of how to do it.

I've added the `setSize` inside `layoutSubviews`, and it gets us mostly there:

<img width="300" src="https://user-images.githubusercontent.com/6651364/116225167-69897780-a749-11eb-8897-4d9e6b8a1564.png" />

It seems like the text gets laid out without consideration of the sibling views. If the only child of the `TitleBar` is the text, it works perfectly:

<img width="300" src="https://user-images.githubusercontent.com/6651364/116225393-ab1a2280-a749-11eb-9735-279c586179ab.png" />

It seems like the same sort of error where layouts aren't being communicated again. I took a stab at `setIntrinsicContentSize` but that panics immediately (not directly sure why). Using `setNeedsLayout` on the UIManager seems like it would have been a good call, but that appears to have no effect.

I also tried wrapping the contents of the `TitleBar` in another `View` thinking - maybe it's just a single child that has problems. But that appears to have the same issues.

The fix I have is enough for my immediate needs, but in the near-ish future I will need to solve this other issue too. Any more tips? I wonder if it could be something to do with how we have to do `flexDirection: 'row'` on the `TitleBar` - if it was `column` each child would get the same width and it would work, so maybe there's a "re layout after styles applied" or something we need to do. Seems weird that we need to do anything here, to be honest

**Comment by salockhart** [comment]
Another workaround that I just discovered is to give the `TitleBar` a `marginRight` equal to the width of the icon - that resolves the issue and causes it to render correctly. But it would not work very well if you had multiple children with dynamic widths

**Comment by grahammendick** [comment]
Thanks again for all the great info and the PR!

I don't think there is a problem with the siblings, the setSize is working. To check if there was a problem I copied the content of the TitleBar and put it inside the ScrollView. 
```jsx
<ScrollView contentInsetAdjustmentBehavior="automatic">
  <View style={styles.titleBar}>
    <Text style={styles.titleBarText} numberOfLines={1}>Erat curabitur elit cursus est in feugiat gravida, habitant hac
morbi urna eget per sapien, enim dictum maximus fringilla fames
suscipit.</Text>
    <View style={{backgroundColor: color, width: 28, height: 28}}/>
  </View>
```
And you can see it renders exactly the same as in the title bar. The red square is pushed off the screen.

![Screenshot 2021-04-27 at 18 01 26](https://user-images.githubusercontent.com/1761227/116282388-9908a600-a782-11eb-958b-79bb0a76f620.png)

I fixed the rendering by adding a `flex: 1` style to the `Text`
```jsx
titleBarText: {
  flex: 1,
  marginRight: 4,
  fontSize: Platform.OS === 'ios' ? 16 : 20,
},
```
And it now renders correctly in both the title bar and inside the scroll view. The red square is fully visible.
![Screenshot 2021-04-27 at 18 05 25](https://user-images.githubusercontent.com/1761227/116282834-28ae5480-a783-11eb-9ada-267a13b2ac5e.png)

Do you agree that it's behaving correctly?

Something else I noticed is that the title bar doesn't resize when the orientation changes from portrait to landscape. It does when going from landscape to portrait though. Do have any idea why?

**Comment by salockhart** [comment]
> Do you agree that it's behaving correctly?

That looks great, I'd say that's expected behaviour then.

> Something else I noticed is that the title bar doesn't resize when the orientation changes from portrait to landscape. It does when going from landscape to portrait though. Do have any idea why?

I'm seeing it too. I'm testing on Xcode 12.4, iOS 14.4, both simulator and device.

The weird thing is that when you go from portait -> landscape it's reporting the same size as it does in portrait mode. This doesn't appear to be an issue with our view, our view matches the width of its `_UITAMICAdaptorView` superview, which I think is private UIKit API. So.. I'm inclined to mark the landscape issue as "won't fix". It works okay, it just doesn't take up the whole width. What do you think?

**Comment by grahammendick** [comment]
Yea, I'm happy to ignore the landscape issue.

Have you checked what happens on Android? Do we need a similar fix to make sure the title bar has the right size?

**Comment by salockhart** [comment]
Good point about Android.. the issue was just reported to me as being on iOS so I didn't think to check.

Android seems to have a similar issue, but it presents differently (which might explain why I didn't hear about it).

Here's a long title using the `TitleBar` component:

<img width="300" alt="Screenshot 2021-04-28 at 14 22 18" src="https://user-images.githubusercontent.com/6651364/116411189-64055d80-a82d-11eb-901d-41f3ed36fb5d.png">

And here's the same title, but using the `title` prop on the `NavigationBar`:

<img width="300" alt="Screenshot 2021-04-28 at 14 22 56" src="https://user-images.githubusercontent.com/6651364/116411264-767f9700-a82d-11eb-9e0b-8363c22edc7c.png">

With the `TitleBar` it does appear to be getting the wrong width, it's not truncating it with the ellipses properly and the red square is not visible.

Trusty Layout Inspector says that's about what's happening (hard to see, but the upper most layer is the text and red square view, and you can see that they extend far beyond the bounds of the title area):

<img width="300" alt="Screenshot 2021-04-28 at 14 44 39" src="https://user-images.githubusercontent.com/6651364/116414352-4be30d80-a830-11eb-90d4-0f8b45cea499.png">

I can dig further into this. Let me know if you have any thoughts!

**Comment by salockhart** [comment]
Getting closer to a solution. If I call `uiManager.updateNodeSize(viewTag, w, h);` inside `onSizeChanged` we get a lot closer:

<img width="300" alt="Screenshot 2021-04-28 at 15 33 44" src="https://user-images.githubusercontent.com/6651364/116422248-784e5800-a837-11eb-86f1-229a5e0c92ef.png">

The only issue now is that it loses the padding on the left hand side - something about declaring the width wipes the position. Odd stuff.

I'll continue to dig in. While I do, any tips on tackling this?

**Comment by grahammendick** [comment]
>> call uiManager.updateNodeSize(viewTag, w, h); inside onSizeChanged

I had the same idea and I'm puzzled why it doesn't work. I tried it myself and saw the same left hand side issue as you. I got an extra problem when I rotated it from portrait to landscape and back again. The title bar flickers with the width yo-yo-ing between two values. It seems that the `onSizeChanged` keeps getting called with these two values.  Do you see this same problem, too?

**Comment by grahammendick** [comment]
Breakthrough! I added the following to the `ToolbarManager` - the Toolbar is the direct parent of the TitleBar. 

```obj-c
@Override
public boolean needsCustomLayoutForChildren() {
    return true;
}
```
This together with the `onSizeChanged` in the `TitleBarView` gives us what we're after!

![Screenshot 2021-04-29 at 01 48 23](https://user-images.githubusercontent.com/1761227/116489487-ff79eb00-a88c-11eb-9af9-dcf45b1717fd.png)

I'm going to need to do some more testing but it looks promising. Can you try out these two changes together and see if it works for you, please?

**Comment by salockhart** [comment]
Oh well done, that's a great solution!

I've tested it on my end, portrait/landscape with both using the `TitleBar` as well as just the `title` prop - looks to be working great. I'll add these changes to my PR

**Comment by grahammendick** [comment]
Thanks for testing the changes and adding them to the PR
