### ISSUE TITLE
Navigating back to a previous navigator?

### ISSUE THREAD

**Issue by hlynurstef** [grahammendick/navigation#518]
I'm using react native with the following versions:

```
"navigation": "5.4.1",
"navigation-react": "4.2.0",
"navigation-react-native": "7.4.2",
```
I've been following the docs and I've added a TabBar. I'm using the same configuration as here: https://grahammendick.github.io/navigation/documentation/native/tab-bar.html

So I have a root stateNavigator that contains the tab scene as well as a login page and the tab scene contains two tabs 'home' and 'profile'. So my question is how do I allow the user to log out from the profile tab and navigate back to the login page in the root navigator?

So basically my `App.tsx` file contains this navigator:

```
const stateNavigator = new StateNavigator<RootNavigator>([
    { key: 'tabs' },
    { key: 'login' },
  ]);

const { tabs, login } = stateNavigator.states;
tabs.renderScene = () => <Tabs />;
login.renderScene = () => <Login />;
stateNavigator.navigate('login');

const App: React.FC = () => (
  <NavigationHandler stateNavigator={stateNavigator}>
    <NavigationStackIOS />
  </NavigationHandler>
);
```

and my Tabs component contains the following:

```
// Home tab navigator
const homeNavigator = new StateNavigator<HomeTabNavigation>([
  { key: 'home', trackCrumbTrail: true },
]);
const { home } = homeNavigator.states;
home.renderScene = () => <Home />;
homeNavigator.navigate('home');

// Profile tab navigator
const profileNavigator = new StateNavigator<ProfileTabNavigation>([
  { key: 'profile', trackCrumbTrail: true },
]);
const { profile } = profileNavigator.states;
profile.renderScene = () => <Profile />;
profileNavigator.navigate('profile');

const Tabs: React.FC = () => (
  <>
    <NavigationBar hidden />
    <TabBar
      primary
      bottomTabs
      barTintColor="#FFFFFF"
      selectedTintColor="#EC418E"
      unselectedTintColor="#B5B5B5"
    >
      <TabBarItem title="Home">
        <NavigationHandler stateNavigator={homeNavigator}>
          <NavigationStack />
        </NavigationHandler>
      </TabBarItem>
      <TabBarItem title="Profile">
        <NavigationHandler stateNavigator={profileNavigator}>
          <NavigationStack />
        </NavigationHandler>
      </TabBarItem>
    </TabBar>
  </>
);
```

Do I need to structure this in some other way or is there some way for me to navigate back from the profile tab to the login screen?

**Comment by grahammendick** [comment]
Hey @hlynurstef, thanks for getting in touch and for the clear explanation.

You’ve structured your app great. You need to navigate to the login screen in your **root stateNavigator.** You can try it out by adding a useEffect to the App component that navigates to the login after some time. I’ve set it to 20 seconds below to give you time to login and select the profile tab.

```jsx
const App = () => {
  useEffect(() => {
    setTimeout(() => {
      stateNavigator.navigate('login')
    }, 20000)
  }, [])
  return (
    <NavigationHandler stateNavigator={stateNavigator}>
      <NavigationStackIOS />
    </NavigationHandler>
  );
}
```

The `setTimeout` is just for demo purposes. To implement it for real you need to communicate from the Profile scene up to the App. It makes sense to use React Context for this. You can create a Provider in the App that passes a logout function and the Profile scene can call it.

Hope this is clear, but  if it isn’t just let me know.

**Comment by hlynurstef** [comment]
@grahammendick thanks for the quick reply!

I implemented what you suggested using React Context and it works like a charm 👌

The only thing that I'm now wondering is if I can disable the "push" animation when navigating? I'm wondering because when I navigate to the login page, the login page gets animated in, but I'd like it to be an instant transition like when you switch tabs in the TabBar. Is this possible?

Another use case for this would be that I have a splash screen in the root stateNavigator that is the first screen of the app. This screen checks if the user is already loggedin or not to know if it should navigate to the login page or the tabs page. Ideally I'd want the transition from splash -> login or splash -> tabs to be an instant transition with no animation as well.

It would be great if I could somehow specify if it should animate or not in the navigate function.

**Comment by hlynurstef** [comment]
I was running into an issue where the old login screen was still on the stack and was triggering the login action twice instead of once so I changed it to not track crumb trail and now the login action is only triggered once as excepted and the "push" animation was replaced by the "pop" animation.

```
const stateNavigator = new StateNavigator<RootNavigator>([
    { key: 'tabs' },
    { key: 'login', trackCrumbTrail: false },
  ]);
```

But I'm still curious if I can disable the animation from splash -> login or splash -> tabs when I have the root stateNavigator defined like this:

```
const stateNavigator = new StateNavigator<RootNavigator>([
    { key: 'tabs' },
    { key: 'splash', trackCrumbTrail: false },
    { key: 'login', trackCrumbTrail: false },
  ]);
```

**Comment by grahammendick** [comment]
Yes, you can disable the animation using the `unmountStyle` prop on the `NavigationStack`.  It accepts a function and you return an empty string to turn off the animation. The second parameter is the current scene so you can disable the animation for just the 'login' and 'tabs scenes. This should go in the `NavigationStack` of your `App` component
```jsx
<NavigationStack
  unmountStyle={(_, { key }) => (key === 'login' || key === 'tabs') ? '' : null} />
```

**Comment by hlynurstef** [comment]
@grahammendick I was already using the `unmountStyle` prop to create an iOS like animation on Android but I didn't realise I could pass in an empty string to disable the animation, now I know 👌

Awesome library btw, I'm really enjoying using it.

Since you've answered all my questions I'm going to close this issue 🙏

**Comment by grahammendick** [comment]
I'm really glad you like the Navigation router and I'm happy I could help you out
