### ISSUE TITLE
navigation-react-mobile breaks on SSR

### ISSUE THREAD

**Issue by maman** [grahammendick/navigation#549]
Hi!

The latest `navigation-react-mobile@3.5.0` introduces a performance enhancement to "suspend" background scenes. This uses `Suspense`, which isn't enabled yet on React's server-side renderer.

I believe that the [isomorphic sample](https://github.com/grahammendick/navigation/tree/master/NavigationReactMobile/sample/isomorphic) is affected too - since it uses the `NavigationMotion` component to perform rendering on both client and server

**Comment by grahammendick** [comment]
Hey! Thanks, that's a great spot. Think I was too excited by `Suspense` and forgot to check SSR.

**Comment by grahammendick** [comment]
I just released `navigation-react-mobile v3.5.1` and I [thanked you in the release notes](https://github.com/grahammendick/navigation/releases/tag/v3.5.1-NavigationReactMobile)!
