### ISSUE TITLE
useUnloaded does not fire when Scenes are from different StateNavigators

### ISSUE THREAD

**Issue by Dwar3xwar** [grahammendick/navigation#551]
Hey @grahammendick, hope you are doing well. 

Was just using the `useUnloaded` hook, and noticed that `useUnloaded` does not fire when Scenes are from different StateNavigators. For example this will occur if a scene navigates to a scene that is using a different navigation stack(ie. modal). 

Just wondering, if you are looking to support this feature or have any recommendations for alternatives. 

Thank you!

**Comment by grahammendick** [comment]
Hey @Dwar3xwar, it's good to hear from you.

The `useUnloaded` only fires on the Scene that's being unloaded. For example, if you navigate from A to B then `useUnloaded` fires on scene A but not on B. If you then navigate to C, the `useUnloaded` fires on scene B but not on A or C. 

Could you tell me what it is you’re trying to do and I’ll try and help out?

**Comment by Dwar3xwar** [comment]
Lets say, when navigating from Scene A of StateNavigator A to Scene A of StateNavigatorB. I'm assuming because the scene part of different navigation stacks, the `useUnloaded` event doesn't seem to get fired.  

To be more specific, in our code, we do not have a single StateNavigator that handles navigation in our app but multiple StateNavigator that handles different parts of the app. 

Hope this makes sense!

**Comment by grahammendick** [comment]
Right, if you're on scene A and open a Modal then `useUnloaded` doesn’t fire on A. Could you tell me what you’re actually trying to do, please? For example, "I want to change the parent scene's background when I open a Modal".

**Comment by Dwar3xwar** [comment]
> Right, if you're on scene A and open a Modal then `useUnloaded` doesn’t fire on A

Ah I figured as much 

> Could you tell me what you’re actually trying to do, please

We are trying to do some side effects when Scene A navigates to a new screen, ie. opening a modal and pushing a new scene on the navigation stack.

**Comment by grahammendick** [comment]
Opening a Modal is in your control so you can run your `useEffect` when the modal visibility changes.

The following works for when a new scene is pushed onto the modal stack.

```jsx
const SceneA = () => {
  const {stateNavigator} = useContext(NavigationContext);
  const modalNavigator = useMemo(() => {
    const navigator = new StateNavigator(stateNavigator);
    navigator.navigate('sceneA');
  }, [stateNavigator]);
  useEffect(() => {
    // Fires every time you navigate within the Modal
    const yourSideEffect = () => {
    }
    modalNavigator.onNavigate(yourSideEffect);
    return modalNavigator.offNavigate(yourSideEffect);
  }, [modalNavigator])
  return (
    <Modal>
      <NavigationHandler stateNavigator={modalNavigator}>
        <NavigationStack />
      </NavigationHandler>
    </Modal>
  )
}
```

**Comment by grahammendick** [comment]
@Dwar3xwar Did my answer work for you?

**Comment by Dwar3xwar** [comment]
Hey @grahammendick, looks like we no longer have this use case. Thanks for the help! Will close for now
