### ISSUE TITLE
Docs Suggestion: Navigation Router works with expo-dev-client and EAS build

### ISSUE THREAD

**Issue by karlsander** [grahammendick/navigation#553]
Navigation Router seems to work without any further setup with the recent "modern" expo workflow, using a custom dev client and `eas build`. So the parts of expo that don't work are using Expo Go and `expo build` (which they want to deprecate). I think that's very important to know because "no expo support" probably throws a lot of people off.

I would suggest changing

"The Navigation router for React Native uses the underlying native APIs to provide faithful navigation on Android and iOS. Because it contains native code you have to eject from Expo or create your application using react-native init."

to something like

"The Navigation router for React Native uses the underlying native APIs to provide faithful navigation on Android and iOS. Because it contains native code you have to create a custom development build or eject when using Expo or create your application using react-native init."

and link "custom development build" to https://docs.expo.dev/development/introduction/

Those docs then make clear than you have to use EAS Build or a fully local build and cannot use classic expo build / expo go. Using just EAS Build and not custom development client will work, but is a pretty terrible workflow and not worth mentioning imho.

I would have made a PR instead of an issue, but I don't think the docs are on GitHub, are they?

**Comment by grahammendick** [comment]
Wow, that’s great, I had no idea. The [docs are on Github](https://github.com/grahammendick/navigation/blob/e1c2057a659cb5cddcdbc5fa0dabde05b9e1acc1/documentation/native/setup.html#L48) in a `gh-pages` branch. I’d really appreciate a PR. How about the following text?

>> The Navigation router for React Native uses the underlying native APIs to provide faithful navigation on Android and iOS. Because it contains native code you have to create your application using `react-native init` or a custom development build in Expo.

**Comment by grahammendick** [comment]
@karlsander Hi, are you still interested in putting a PR together to update the docs?

**Comment by grahammendick** [comment]
Fixed by #562
