### ISSUE TITLE
Scenes with trackCrumbTrail set to true turn blank on second visit (iOS)

### ISSUE THREAD

**Issue by 10000multiplier** [grahammendick/navigation#576]
The scenes are setup like this:

```jsx
const stateNavigator = new StateNavigator([
  { key: 'email', trackCrumbTrail: false },
  { key: 'phone', trackCrumbTrail: false },
  { key: 'reset', trackCrumbTrail: true }
])
```

The `reset` scene goes blank after the first visit.

If I open and close the modal, the `reset` scene reappears, but on consecutive visits goes blank again.

See full video to illustrate:

https://user-images.githubusercontent.com/57633368/151881807-1e88638c-df1e-4df0-9a0a-ab4e229fc68c.MOV

**Comment by grahammendick** [comment]
It's hard for me to tell exactly what your setup is from the video. But it looks to me like you’ve created your own Back button in the `LeftBar` and that you're manually navigating to the email screen. I’m guessing that's why the email has disappeared from the TextInput. And the blank email is probably what's causing your reset screen to be blank the second time.

If you want to go back from the reset screen then you should set `trackCrumbTrail` to true on the reset State. Then iOS will provide the back navigation automatically. It will also keep the email screen in memory so that the TextInput stays populated.

**Comment by 10000multiplier** [comment]
Sorry I realized the video was quite confusing.

Hopefully this one will provide more clarity.https://user-images.githubusercontent.com/57633368/151890426-a3cc9d89-8d6a-4b53-9240-85b1e188ad15.MOV

The example is not using any custom navigation. 

The blank screen seems to happen with any component that is being used to render the scene, as long as the `trackCrumbTrail` is set to `true`.

**Comment by grahammendick** [comment]
Take a look at the [medley sample](https://github.com/grahammendick/navigation/tree/master/NavigationReactNative/sample/medley). That has a modal with a stack and there's no problem navigating back and forward

**Comment by grahammendick** [comment]
I’ve tried your scenario in the medley example and it works fine for me. There's no blank screen. Please can you follow the steps I took and see if it works for you, too.

1. Change the 'north' and 'east' States to trackCrumbTrail false
```jsx
const stateNavigator = new StateNavigator([
  {key: 'north', trackCrumbTrail: false},
  {key: 'east', trackCrumbTrail: false},
  {key: 'south', trackCrumbTrail: true},
  {key: 'west', trackCrumbTrail: true},
]);
```
2. Add 3 buttons to the `Direction` component. They’re hard-code to navigate 'north', 'east' and 'west'
```jsx
<TouchableHighlight
  underlayColor={color}
  onPress={() => {
    stateNavigator.navigate('north');
}}>
  <Text style={styles.text}>North</Text>
</TouchableHighlight>
<TouchableHighlight
  underlayColor={color}
  onPress={() => {
    stateNavigator.navigate('east');
}}>
  <Text style={styles.text}>East</Text>
</TouchableHighlight>
<TouchableHighlight
  underlayColor={color}
  onPress={() => {
    stateNavigator.navigate('west');
}}>
  <Text style={styles.text}>West {crumbs.length}</Text>
</TouchableHighlight>
```
3. Run the medley sample and press the ‘North' and 'East' buttons a few times.
4. Open the Modal.
5. Press the 'West’ button.
6. Press back.
7. Press the 'West' button.

https://user-images.githubusercontent.com/1761227/151938251-aa4867c5-a6cf-45bd-96a4-453cf9da735c.mov

**Comment by 10000multiplier** [comment]
Thanks for trying it out on your end.  I guess there is something strange happening here, maybe in my case expo dev-client is causing this behaviour?

**Comment by 10000multiplier** [comment]
The medley example works.

So this should be fixeable :)

Will let you know if I find the root cause.

**Comment by grahammendick** [comment]
I'm closing this because it's not an issue with the Navigation router. But let me know how you get on

**Comment by grahammendick** [comment]
@10000multiplier Thanks for the nice comment on your React Native docs PR! I've contacted a few people who have contributed to the Navigation router and asked them to add a comment. Let's see what happens

**Comment by 10000multiplier** [comment]
You're welcome sir. Let's see if anything comes from it.

**Comment by 10000multiplier** [comment]
https://github.com/grahammendick/navigation/commit/fa198b8c493ad91600d9c680d87b26eb253ee75e fixed it!

**Comment by grahammendick** [comment]
Oh that's sweet. It was probably that commit plus #584. Took me ages to work out what was wrong
