### ISSUE TITLE
Android Tab layout when rendering more than 3 tabs

### ISSUE THREAD

**Issue by SourceErr0r** [grahammendick/navigation#577]
Hi,

I've run into an issue where, when adding more than 3 TabBarItems to a TabBar on Android, it is removing the title from inactive tabs and centring the icon. The only title visible is that of the active Tab, as you can see in the screenshot below.

![Tab issue](https://user-images.githubusercontent.com/24960356/152191357-90079012-e92b-4891-9711-ae27e0232c17.png)

Would it be possible to somehow disable this behaviour and force the tabs to render their full contents (as they do on iOS)?

**Comment by grahammendick** [comment]
Hey, it's great to hear from you!

The default behaviour on Android is to only show text and labels when there are three or less tabs. But there's a [setLabelVisibilityMode method](https://developer.android.com/reference/com/google/android/material/navigation/NavigationBarView#setLabelVisibilityMode(int)) we can use. If we pass in `LABEL_VISIBILITY_LABELED` then it will show a label on all tabs. 

Are you interested in working on a PR to add this functionality? I'll help you if you need it, of course.

**Comment by SourceErr0r** [comment]
Hi Graham, 

I did not expect a response so quickly, but that sounds like exactly what I'm looking for, thanks!

I can certainly have a go at implementing this, I'll have a closer look tomorrow to determine what will be involved.

**Comment by grahammendick** [comment]
That's great, thanks! Let me know if you have any questions. I'm always happy to help

**Comment by grahammendick** [comment]
@SourceErr0r How you getting along? Do you need any help?

**Comment by SourceErr0r** [comment]
@grahammendick I'm not really sure what I'm doing here, and my Android Studio is full of errors so it's very hard to figure out which classes and methods are available to me. But I've tried to copy the pattern you've used for other props and added: 

```    
@ReactProp(name = "labelVisibility")
public void setLabelVisibilityMode (NavigationBarView view, int labelVisibilityMode) { view.setLabelVisibilityMode(labelVisibilityMode); }
```

To NavigationBarManager.java. I've also attempted to expose this in the props on the RN component but I'll worry about that part later - right now I'm getting an error from the module:

```
symbol:   method setLabelVisibilityMode(int)
  location: variable view of type com.navigation.reactnative.NavigationBarView
```

Which I think means that the view (NavigationBarView) does not have the setLabelVisibilityMode method? But according to the docs it should be there. Any advice?

**Comment by grahammendick** [comment]
Thanks for having a go!

You should run the [Twitter sample](https://github.com/grahammendick/navigation/tree/master/NavigationReactNative/sample/twitter) from inside Android studio. It's easier to work on the code from inside a running app because then everything compiles without errors. Then you can test java changes directly inside Android studio and copy them back to the Navigation router when you're happy. Any JavaScript changes you should make inside the [NavigationReactNative source](https://github.com/grahammendick/navigation/tree/master/NavigationReactNative/src) and then run `npm run package` from the root of the repository. This generates a new `navigation.react.native.js` file inside the [build/npm/navigation-react-native folder](https://github.com/grahammendick/navigation/tree/master/build/npm/navigation-react-native). Then you can drop this file inside the navigation-react-native folder of the node_modules of the Twitter sample.

Does that make sense?

Also, remember that you're working on the `TabBar` not the `NavigationBar` ;)

**Comment by SourceErr0r** [comment]
> Also, remember that you're working on the TabBar not the NavigationBar

Yeah I've just had a look at the imports on the navigation bar and realised that it isn't actually the same as the one you linked above, d'oh. I'll move this across to the tab bar and see if that will compile :)

**Comment by grahammendick** [comment]
Ah, I see the confusion. But the weirdly-named `NavigationBarView` is actually the parent of the `BottomNavigationView`, the bottom tab bar

**Comment by grahammendick** [comment]
The `NavigationBarView` I linked to is the one from the java library, not the one from the Navigation router. I didn't spot they had the same name!

**Comment by SourceErr0r** [comment]
It's working 🥳  I'll just tidy up a bit and then I'll open a PR

**Comment by SourceErr0r** [comment]
Hmmm, I seem to have a bug with the LABEL_VISIBILITY_SELECTED option. 

```
Exception in native call
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
```

Not entirely sure how to debug this. I'm thinking it might be best to remove the 'selected' option and just have show/hide/auto. @grahammendick are you happy with that?

**Comment by grahammendick** [comment]
You should see what's going on. If you run the [Twitter sample](https://github.com/grahammendick/navigation/issues/577#issuecomment-1034794236) from within Android Studio then you can debug it.

**Comment by SourceErr0r** [comment]
I have a very simple app running already to test; It's just setting up a basic nav structure and opening a tab group with 5 tabs.

It seems like it is trying to work out which tab is selected, before we actually have one set. Possibly a race condition? I was thinking if we set the default tab that might resolve it, but no luck. Maybe setting this prop on creation is the issue, and we need to delay it until the tabgroup has been created, but before it is rendered? 

The main problem is, I don't really know enough Java to attempt to fix this 😬

**Comment by grahammendick** [comment]
That's interesting. The default visibilityMode is SELECTED when there's more than 3 tabs. I wonder why that doesn't have the same problem? Can you paste in the error stack trace?

**Comment by SourceErr0r** [comment]
Yeah it's very strange, the default setting ('auto') has the same behaviour when > 3 tabs, so it should be working. That's why I'm thinking it's the timing of setting the flag, I may be setting it too early. Stack trace:

```
E/unknown:ReactNative: Exception in native call
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
        at com.google.android.material.bottomnavigation.BottomNavigationMenuView.onMeasure(BottomNavigationMenuView.java:86)
        at android.view.View.measure(View.java:24530)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6828)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:24530)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.updateLayout(NativeViewHierarchyManager.java:189)
        at com.facebook.react.uimanager.UIViewOperationQueue$UpdateLayoutOperation.execute(UIViewOperationQueue.java:169)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:721)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

I'm going to open a PR in a moment if you'd like to pull and take a look.
