### ISSUE TITLE
iOS Navbar height

### ISSUE THREAD

**Issue by SourceErr0r** [grahammendick/navigation#604]
Hi!

For some reason it seems like the navbar on iOS is rendering at double height. I've tried running through various props on the `<NavigationBar>` component but with no luck. You can see an example below:

![You can see an example here](https://user-images.githubusercontent.com/24960356/175518836-6f03d8ba-d980-4b6b-b7f5-3a49f5f1c9a4.png)

Do you happen to know why this might be happening, and how to resolve? I'm using a fairly standard TabBar implementation, and this issue is occurring both top level and on children with breadcrumbs.

**Comment by grahammendick** [comment]
Could you show me your TabBar implementation, please? Not all the code, just the high level layout

**Comment by SourceErr0r** [comment]
Sure,

```
<TabBar
      scrollable={false}
      defaultTab={0}
      labelVisibilityMode="labeled"
      primary={true}
      tab={0}
      barTintColor={'rgb(247,247,247)'}
      selectedTintColor="#3B852A"
    >
      <TabBarItem title="Home" image={require('../assets/home.png')}>
        <NavigationHandler stateNavigator={homeNavigator}>
          <NavigationStack />
        </NavigationHandler>
      </TabBarItem>
      <TabBarItem title="Profile" image={require('../assets/profile.png')}>
        <NavigationHandler stateNavigator={profileNavigator}>
          <NavigationStack />
        </NavigationHandler>
      </TabBarItem>
      <TabBarItem title="More" image={require('../assets/more.png')}>
        <NavigationHandler stateNavigator={menuNavigator}>
          <NavigationStack />
        </NavigationHandler>
      </TabBarItem>
    </TabBar>
```

**Comment by grahammendick** [comment]
Thanks, and can you show me one of the scenes with the NavigationBar in. Again just the high level layout

**Comment by grahammendick** [comment]
Does it render double height if you rendered it outside of the TabBar?

**Comment by SourceErr0r** [comment]
Correct height when rendered outside of Tabs

**Comment by grahammendick** [comment]
Can you try the [twitter sample](https://github.com/grahammendick/navigation/tree/master/NavigationReactNative/sample/twitter) and see if you get the double height issue, please?

**Comment by SourceErr0r** [comment]
Also, if I do not include the <NavigationBar> component, I get the default navbar rendered still at double height (which is the oddest part for me - I thought it might be stacking with the default)

Just need to pop out and grab lunch, I'll give the sample a try when I get back!

**Comment by grahammendick** [comment]
Oh thanks, I think I've got it. You need to [hide the NavigationBar` in the scene with the tabs in](https://github.com/grahammendick/navigation/blob/73f07d63fa911dd3cef260a767805ad75be3ca41/NavigationReactNative/sample/twitter/Tabs.js#L23).

**Comment by grahammendick** [comment]
Otherwise you're getting 2 navigation bars. One from the tabs scene and then the actual one you want from the tab content scene

**Comment by SourceErr0r** [comment]
Ahhh that's done it, brilliant, thanks!
