### ISSUE TITLE
TabBarItem - iOS Icons

### ISSUE THREAD

**Issue by gezquinndesign** [grahammendick/navigation#610]
Hello, I've adapted the twitter example for use in an app that I'm building.  The TabBar looks good on android:
![0](https://user-images.githubusercontent.com/7525980/178139409-dbf93bca-d7ff-422f-aa81-3cd9898b5579.png)

but on ios, the icons are not sized correctly:
![1](https://user-images.githubusercontent.com/7525980/178139414-a0b5c470-491d-496b-80b3-e3d648eedb81.png)

If I change the image prop so that it uses `Image.resolveAssetSource()` and resize the icons, they look better but they are still grainy:
![2](https://user-images.githubusercontent.com/7525980/178139429-de062973-aeb3-49fe-a4d4-1095615cc7cc.png)

Just wondering if there's any way around this or if it would be possible for navigation to support SVGs as this would ensure the icons always look crispy.  Thanks.

**Comment by grahammendick** [comment]
Hey there, somebody else asked [the same question](https://github.com/grahammendick/navigation/issues/501#issuecomment-1022468719). I think, like them, you'll see the same blur with a React Native `Image` component. If so, then you can [fix that with static image resources](https://github.com/grahammendick/navigation/issues/501#issuecomment-1022628767)

**Comment by gezquinndesign** [comment]
Thanks for the prompt response. I still get the same enlarged image when using a plain `require` and adding the static image resources results in the same blurred image when using `Image.resolveAssetSource()`. Is there any additional config I need to do to get static images to work? I added the 3 different sized images to the root folder of Twitter example and referenced the main one as indicated in the docs but the result is still the same.

**Comment by gezquinndesign** [comment]
![bird](https://user-images.githubusercontent.com/7525980/178280991-a1a45997-7878-499b-ae05-cc73876ba448.png)
<img width="256" alt="bird@2x" src="https://user-images.githubusercontent.com/7525980/178280994-9539a0cb-56dd-4e40-885d-fe7b05b71ba5.png">
![bird@3x](https://user-images.githubusercontent.com/7525980/178280997-dc2b4dfa-b375-4aae-809d-942933e00a27.png)
These are the images I'm using, if it helps...

**Comment by grahammendick** [comment]
You should use images that are the right size for the tabs. If you use a React Native `Image` component then those images would show up large too, right?

**Comment by gezquinndesign** [comment]
I changed the main image to be 25px x 25 px and that sorted my issue out.  I was just confused because the same image was displaying nicely on Android. Thanks for your help. 👍
