### ISSUE TITLE
ColorValue typings

### ISSUE THREAD

**Issue by danilobuerger** [grahammendick/navigation#618]
In https://github.com/grahammendick/navigation/blob/master/build/npm/navigation-react-native/navigation.react.native.d.ts colors are defined as `string` instead of `ColorValue`, for example:

https://github.com/grahammendick/navigation/blob/18c2b2a9e8f1c1db6a797ddefe9303f127f04bf5/build/npm/navigation-react-native/navigation.react.native.d.ts#L95-L98

I would expect to be able to set a `ColorValue` on these.

**Comment by grahammendick** [comment]
Oh thanks, it looks like [ColorValue was added a couple of years ago](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45963). Would you be interested in working on the PR?

**Comment by grahammendick** [comment]
I see, `ColorValue` supports `PlatformColor` and `DynamicColorIOS` from [the Color APIs](https://reactnative.dev/docs/colors#color-apis) introduced in React Native 0.63

**Comment by danilobuerger** [comment]
Right, e.g. allowing native support for light / dark mode colors and smooth native transitioning between those modes.
