### ISSUE TITLE
Error on parse URL with incomplete query params

### ISSUE THREAD

**Issue by mazipan** [grahammendick/navigation#628]
Sometimes in production, we got incomplete query params since we can not control the user behaviour.
When we try to parse with `stateNavigator` it throw us an exeption.

```ts
const { state, data } = stateNavigator.parseLink(incompleteUrlQuery);
```

Example of incomplete URL: `/product/cengkeh-jywcmnfq?utm_source=blog&utm_medium=recipe&utm_campaign=`
The correct one: `/product/cengkeh-jywcmnfq?utm_source=blog&utm_medium=recipe&utm_campaign=test`

You can see `utm_campaign` doesn't pass any value from client side.

The error we got: 

```
Error: The Url /product/cengkeh-jywcmnfq?utm_source=blog&utm_medium=recipe&utm_campaign= is invalid
Empty string is not a valid array item
```

**Comment by grahammendick** [comment]
@mazipan I noticed you gave my answer a 👍 Can I close this?

**Comment by mazipan** [comment]
Just to following up, the return should be decoded

```ts
const {product} = stateNavigator.states;
product.urlDecode = (state, key, val) => key === 'utm_campaign' ? decodeURIComponent(val) || 'empty' : decodeURIComponent(val)
```

**Comment by grahammendick** [comment]
You're absolutely right. Sorry I missed it and thanks for correcting my answer
