### ISSUE TITLE
Expo Support 

### ISSUE THREAD

**Issue by chakravarthi-bb** [grahammendick/navigation#629]
Navigation Library can be used with Expo with this

https://docs.expo.dev/guides/config-plugins/

**Comment by grahammendick** [comment]
Hey there! I've never used expo but I know the Navigation router works with it [because other people are using them together](https://github.com/grahammendick/navigation/issues/553)

**Comment by grahammendick** [comment]
Hey, I wasn't sure if you were asking me something or telling me something. Are you ok if I close this?
