### ISSUE TITLE
Android (scene) background color

### ISSUE THREAD

**Issue by iamyellow** [grahammendick/navigation#639]
Hi! As always, it's so pleasant using your navigation library. This time a come w/ a couple of requests. This is for Android, next for iOS. I could manage to help w/ a PR if you let me know some guidelines in how to do it, eg how do you try things before release, because I've _touching_ sources under `node_modules` and obviously it's not the best approach!

Anyway, I have an app w/ dark background. I noticed on Android that there's a flash-y feeling just before all the screen is rendered, caused because the default background color for everything in RN Android is white. I tried the `underlayColor` prop but no success. After debugging with Flipper layout inspector I saw that changing the opacity of `SceneView` to zero, the background color from the stack `underlayColor` is there. First I tried to add this to. `SceneViewManager`:

```java
@ReactProp(name = "underlayColor", customType = "Color", defaultInt = Integer.MAX_VALUE)
public void setUnderlayColor(SceneView view, int underlayColor) {
    view.setBackgroundColor(underlayColor);
}
```

It doesn't work yet because I guess I need to change things on js land... btw, I preferred ask here before to check out how do you see this...

Thanks!

**Comment by grahammendick** [comment]
Hey there, it's really great to hear from you again! I missed you man. 

Why doesn't the dark background of your Scene content appear over the white background? I am open to a change though but just curious about when exactly the white is showing through.

**Comment by iamyellow** [comment]
txs for answering! yeah, ton of things happened :) still have in mind docs, found the lib but lost the time.

the dark bg does appear, BUT there's like idk... let's say 250ms where you can see the white bg. Actually is not even white because it happens so fast, but it's there enough time to notice something strange happens because is lighter than the dark bg.

My app is like twitte demo but reversed (aka from tweet to home). so it happens when push to the stack the home.

I'm pretty sure you'll notice just  changing the bg to black in the actual twitter example.

**Comment by grahammendick** [comment]
I'm away on a work do at the moment so can't check. Could you let me if it happens in my Twitter sample please? The Twitter sample has no data loading or useEffect so I'd like to know if it still happens there

**Comment by iamyellow** [comment]
sure! also I'll try to PR. I guess you're using the examples to test development, right?
Also, do you know if a can have a npm dep pointing to my fork?

**Comment by grahammendick** [comment]
Yes I use the Twitter sample mostly. I run `npm run package` at the top level folder. Then I copy the `navigation-react-native` folder from the `build/npm` folder and paste it into the `node_modules` folder.

**Comment by burakgormek** [comment]
> Yes I use the Twitter sample mostly. I run `npm run package` at the top level folder. Then I copy the `navigation-react-native` folder from the `build/npm` folder and paste it into the `node_modules` folder.

No need to copy. You can specify path from `package.json`

`"navigation-react-native": "file:../../../build/npm/navigation-react-native"`

**Comment by iamyellow** [comment]
morning!  can you notice it?

https://user-images.githubusercontent.com/726613/189314625-72e71991-fce5-4d26-9970-22176c85b416.mp4

I changed to black the list bg and removed
```jsx
crumbStyle={from => from ? 'scale_in' : 'scale_out'}
unmountStyle={from => from ? 'slide_in' : 'slide_out'}
```

actually with the slide is not noticable since it's a slower animation. I'll be working on the PRs. BTW, I managed to get rid of the hassle of copying stuff into node_modules 😉

**Comment by grahammendick** [comment]
Are you talking about the white flash of the clicked item? Isn't that because you haven't chsnged the `underlayColor` of the `<TouchableHighlight` to black?

**Comment by iamyellow** [comment]
no, I'm talking about all the screen view. It's because RN or android is setting somewhere white as default bg. So, even if you have a full sized `View` (`flex: 1` or whatever) there's a few ms where you can see that white bg. 

Anyway, I think I'm missing something. I'm trying to edit java sources but I'm always getting this:
<img width="755" alt="Screenshot 2022-09-09 at 12 42 45" src="https://user-images.githubusercontent.com/726613/189332748-15b2da70-d6f4-4836-aa16-e3ddcf498824.png">

That file does not exist, but the app compiles correctly :(

**Comment by iamyellow** [comment]
(spoiler to myself: probably it has something to do w/ new arch. trying to build everything w/ the new arch enabled)

**Comment by grahammendick** [comment]
I'm still not clear where you're saying the white flash appears. I only see it on the clicked item?

**Comment by iamyellow** [comment]
Well, I hope I can show what I meant this time!

We have this simple app:
```typescript
import { NavigationHandler } from 'navigation-react'
import { NavigationStack, Scene } from 'navigation-react-native'
import { Button, View } from 'react-native'
import { rootNavigator } from './state/navigation'

const SimpleRooms = () => {
  return (
    <View style={{ flex: 1, backgroundColor: 'black' }}>
      <Button title="go" onPress={() => rootNavigator.navigate('room')} />
    </View>
  )
}

const App = () => {
  return (
    <NavigationHandler stateNavigator={rootNavigator}>
      <NavigationStack underlayColor="black">
        <Scene stateKey="rooms">
          <SimpleRooms />
        </Scene>
        <Scene stateKey="room" underlayColor="black">
          <SimpleRooms />
        </Scene>
      </NavigationStack>
    </NavigationHandler>
  )
}

export default App
```

Ok, now the effect: 

https://user-images.githubusercontent.com/726613/189361632-293d3b6e-4975-4848-9d92-93d008094898.mp4

Clearly there's a flash there, you can check it frame by frame with a video editor or even quicktime:

<img width="522" alt="Screenshot 2022-09-09 at 15 27 46" src="https://user-images.githubusercontent.com/726613/189361866-d7174569-25dc-400b-bbb7-07b60203866e.png">

See like light gray area going on? It's because the `room` screen has a default white background that comes from `ReactViewGroup` (superclass of ScreenView) I bet. It should not happen because we set everything to `black`.

**Comment by grahammendick** [comment]
Thanks so much for all the detail. It's so helpful because I can't try it myself at the moment. If I understand, it's because the animation has an alpha transition, right? 

You can probably get a better vid if you slow down the animation by.setting [a duration of 3000ms](https://github.com/grahammendick/navigation/blob/3eca2abbfc6c8d60bc7aa776e253ee0e6c447421/NavigationReactNative/sample/twitter/android/app/src/main/res/anim/scale_in.xml#L12) for example.

I'm curious why you're setting an alpha transition at all or are you saying there is one on the default animation?

**Comment by iamyellow** [comment]
Thanks to you man! 
No, I'm not setting anything, is the default thing. The previous code is what you need to see the flashy thing.
It's not a problem with alphas, because if I add something like 
`view.setBackgroundColor(0xFFF612);`
in the SceneView, instead of flashy white we'll have flashy red. The problem is something is setting white background to the root view!

**Comment by grahammendick** [comment]
Can you try one thing for me please? Run the Twitter example with a [background color black like you already did](https://github.com/grahammendick/navigation/issues/639#issuecomment-1241715209). This time keep the animations but remove the alpha from the [scale_jn](https://github.com/grahammendick/navigation/blob/master/NavigationReactNative/sample/twitter/android/app/src/main/res/anim/scale_in.xml) and [scale_out](https://github.com/grahammendick/navigation/blob/master/NavigationReactNative/sample/twitter/android/app/src/main/res/anim/scale_out.xml) and up the duration in all four animation xmls to 3000ms. For example, this is what the scale_in.xml will be as follows. Can you upload the vid too, please? 
```xml
<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android">
    <scale android:fromXScale="80%p"
        android:toXScale="100%p"
        android:fromYScale="80%p"
        android:toYScale="100%p"
        android:pivotX="50%p"
        android:pivotY="50%p"
        android:duration="3000" />
</set>
```

**Comment by iamyellow** [comment]
https://user-images.githubusercontent.com/726613/189417488-12a4d7f0-a07d-41d5-81c6-57a1940f286b.mp4

the problem is mounting, without the sliding... btw.

**Comment by grahammendick** [comment]
There's no flash there right?

**Comment by iamyellow** [comment]
no, as I said it happens with the default animation: no slide, fast scale.with the slide didn't happen before with alpha or now without slpha. you can reproduce easily with the simple app up there.

**Comment by grahammendick** [comment]
But I'm pretty sure that's because the [default animation I play when navigating](https://github.com/grahammendick/navigation/blob/3eca2abbfc6c8d60bc7aa776e253ee0e6c447421/NavigationReactNative/src/android/src/main/java/com/navigation/reactnative/NavigationStackView.java#L63) has an alpha transition. So the default animation is changing opacity. If we provide our own animation that doesn't change alpha/opacity values then there won't be a flash

**Comment by grahammendick** [comment]
No, but [the Navigation router applies the built-in activity open enter transition](https://github.com/grahammendick/navigation/blob/3eca2abbfc6c8d60bc7aa776e253ee0e6c447421/NavigationReactNative/src/android/src/main/java/com/navigation/reactnative/NavigationStackView.java#L63) which looks like [it has an opacity animation](https://android.googlesource.com/platform/frameworks/base/+/ee0b3e9/core/res/res/anim/activity_open_enter.xml). It would be great it you try with a custom animation without any opacity/alpha, please? I'm confident that will remove the flash.

That doesn't mean we shouldn't do anything, but it will give us a clue to what we should do.

**Comment by iamyellow** [comment]
I'll try as soon as I can, I'm out now! thanks!

**Comment by grahammendick** [comment]
No probs, cheers 👍

**Comment by iamyellow** [comment]
btw, how cool is this... not only your lib is amazing, you're so responsive, kind and always helping! we're making and app that is going to be great, I can feel it! and people will know the nav library behind.

**Comment by grahammendick** [comment]
Ah, that's so nice. I'm happy you're using my Navigation router for your awesome app

**Comment by anhtuank7c** [comment]
I'm not involved to this issue but must be agree that this library is awesome, and the owner is great. He response quite fast. I defenitely practice more and will soon use this for real project.

**Comment by iamyellow** [comment]
morning! you were absolutely right @grahammendick !

https://user-images.githubusercontent.com/726613/189474514-563f5122-58c1-47fc-af0d-0fcaffa0ca1b.mp4

no white flash if alpha is not involved.

**Comment by grahammendick** [comment]
@anhtuank7c Thanks I'm glad you like the Navigation router!

@iamyellow Thanks for trying this out - and for slowing down the animation! Great news there's no flash if no alpha. I think the fix is to remove the [default white background from the Scene](https://github.com/grahammendick/navigation/blob/3eca2abbfc6c8d60bc7aa776e253ee0e6c447421/NavigationReactNative/src/Scene.tsx#L170). I can vaguely remember adding this because React Native used to add a white background to their host View on Android. So I think I was just copying them. But that was years ago and they don't do that anymore. So what do you think about dropping the `backgroundColor` from the style in `Scene.tsx`?
```jsx
const styles = StyleSheet.create({
    scene: {
        position: 'absolute',
        top: 0, right: 0,
        bottom: 0, left: 0,
    },
});
```

**Comment by iamyellow** [comment]
sounds crazy good!

**Comment by grahammendick** [comment]
Great. In the PR, could you show a before and after vid with a slow animation so I can see the difference, please?

**Comment by iamyellow** [comment]
no problem.

**Comment by iamyellow** [comment]
[PR done, closing ](https://github.com/grahammendick/navigation/pull/641) 😄

**Comment by grahammendick** [comment]
Reopening because need to find a way to bring this in in a non-breaking way. Also large titles on iOS doesn't work with a transparent background

**Comment by grahammendick** [comment]
The plan is to add a `backgroundColor` prop to `NavigationStack`. The prop accepts a function that returns the background color for a scene. To support transparent scenes on android and large titles on iOS you could have
```jsx
<NavigationStack backgroundColor={() => Platform.OS === 'android' ? "rgba(0,0,0,0)" : "#fff"}>
```
The function has `state`, `data` and `crumbs` parameters so can have a different background color per scene. This makes it consistent with other similar props, like the `unmountStyle` and `crumbStyle` animation props.

@iamyellow what do you think?

**Comment by iamyellow** [comment]
mmm... but it already has underlayColor, is not the same?

**Comment by grahammendick** [comment]
The `underlayColor` is the backdrop color of the stack. It defaults to black and only shows when the [scenes are animating](https://github.com/grahammendick/navigation/issues/639#issuecomment-1242661262). 

The long term plan is to bring some of the props from the `NavigationStack` to the `Scene`. Then I could call it `underlayColor` instead of `backgroundColor` as it doesn't clash anymore. I don't want to do this yet though because it needs quite a bit of thought and not everyone uses the new `Scene` component api.
```jsx
<NavigationStack>
  <Scene
    crumbAnimation={from => from ? 'scale_in' : 'scale_out'}
    underlayColor={Platform.OS === 'android' ? "rgba(0,0,0,0)" : "#fff"} />
</NavigationStack>
```

**Comment by grahammendick** [comment]
Ok, I'm going to have a go at adding the props to the Scene. They'll be on the NavigationStack as well for convenience, backward compatibility and for people not using the Scene component api.

**Comment by grahammendick** [comment]
You can [follow along in the issue-639 branch](https://github.com/grahammendick/navigation/compare/issue-639) 👍

**Comment by grahammendick** [comment]
Aha, it's working nicely. I moved the `crumb` and `unmount` animations onto the `Scene` to test it out. It slides and scales the Tweet scene but the other scenes have the default animations. So, for example, you could provide the general animations using the `NavigationStack` props and use the `Scene` props to override for particular scenes .
```jsx
<NavigationStack>
  <Scene stateKey="tabs"><Tabs /></Scene>
  <Scene stateKey="home"><Home /></Scene>
  <Scene stateKey="notifications"><Notifications /></Scene>
  <Scene
    stateKey="tweet"
    crumbStyle={from => from ? 'scale_in' : 'scale_out'}
    unmountStyle={from => from ? 'slide_in' : 'slide_out'}>
      <Tweet />
  </Scene>
  <Scene stateKey="timeline"><Timeline /></Scene>
</NavigationStack>
```
I'm going to apply the same idea to a new `backgroundColor` prop to fix this bug.

**Comment by iamyellow** [comment]
I tried `backgroundColor` but doesn't work. something weird is happening because the typing don't reflect that prop. I re-installed of the deps from scratch, cleaned up caches, etc. and I can even see version 8.11.0 in `package.json` of the lib inside `node_modules`...

**Comment by grahammendick** [comment]
The `backgroundColor` prop is in version 8.12.0. I released it yesterday 👍

**Comment by grahammendick** [comment]
@iamyellow I thanked you in [the release notes](https://github.com/grahammendick/navigation/releases/tag/v8.12.0-NavigationReactNative)

**Comment by iamyellow** [comment]
really appreciate it! happy to help, mate
