### ISSUE TITLE
iOS back button image

### ISSUE THREAD

**Issue by iamyellow** [grahammendick/navigation#640]
As I said in the previous issue, this time is about iOS.

It turns out we can change the back button image, so it would be great if we could expose the option in js. I added (hardcoding to test) this to `NVNavigationBarView`: 

```objective-c
// - (UINavigationBarAppearance *) appearance: (UIColor *) color { ...
UIImage* backIndicatorImage = [[UIImage imageNamed:@"back"] imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal];
[appearance setBackIndicatorImage:backIndicatorImage transitionMaskImage:backIndicatorImage];
```

(`back` is obviously a local image)

As I said in my previous issue, I could help with a PR but I'd like to know your thoughts as well!

Thanks!

**Comment by grahammendick** [comment]
The only thing better than hearing from you is hearing from you twice!

Yes, I'm happy for a new backImage prop on the NavigationBar. There's already a backTitle. Could you just tell me about your usecase? Why do you want to change the image?

I'm always grateful for a PR. But it's a bit harder now because you have to do everything at least twice. Once in the old architecture and again in the new. Image props in the new architecture are a total pain too. But I'll help of course if you're up for it.

**Comment by iamyellow** [comment]
as simple as the UX/UI guy of our team designed with different back button than the usual. that being said, as Apple docs even explain how to do it and is supported by the SDK free of workarounds IMHO could be a nice addition to your lib!

**Comment by grahammendick** [comment]
Yes, it would be a great addition. Whenever you need help with the PR just let me know. Like I said, brace yourself for more work than you might expect

**Comment by iamyellow** [comment]
hey! I've started with this. As an example to understand how fabric works and use the same code style I'm taking `NVTabBarItemComponentView` because it also has an `image` prop. BTW, I've seen all of those `RCTImageResponseObserverProxy`, `ImageResponseObserverCoordinator`... Is the fabric way for image props?

**Comment by grahammendick** [comment]
I suggest you get it working in the old architecture to start with. It's much simpler to iterate on features in the old architecture. You don't need component specs, codegen etc. Once you're happy with the feature, we can talk about how to get it working in Fabric

**Comment by grahammendick** [comment]
@iamyellow Would you be ok if I picked this up or are you still working on it?

**Comment by grahammendick** [comment]
I had a go and it's pretty difficult, even on the old architecture. The problem is that React Native loads images async so the `viewWillAppear` fires before the image is loaded (even in release mode). You can see the problem in the videowhere the default back image is shown before the custom image loads.

I'll try delaying the screen transition until the back image is loaded. This should fix the problem but it's quite tricky to do.

https://user-images.githubusercontent.com/1761227/193450835-8eb79e95-7a36-4001-a063-94ec1d0b1ca2.mov

**Comment by iamyellow** [comment]
hey! sorry, missed the last message :(
yeah, I looked back then and saw the async nature... I've been really busy last weeks and didn't have the time to go deeper.
Anyway, I think workarounds don't worth the time, specially those tricky one. In my case and in my opinion, I prefer to use drawables / resources for navigation items, even for in app images... it's cheap, fast and works really well. I've never liked the idea of require's... but you know, I'm used to native things and there're a lot of RN devs that surely never open the platform IDE, which is good and it's kinda the point of RN.
If I'd ask you for something, I'd say please add the option to -for this particular case- pass the native resource 😄  but I'd understand as a la library maintainer that this kind of options fit this library, I can always `patch-package` it.

**Comment by grahammendick** [comment]
>  I prefer to use drawables / resources for navigation items, even for in app images

Can you show me how you use drawables/resources, please? I'm not I follow what you're doing

**Comment by grahammendick** [comment]
Early results are promising. Here's a custom back image behaving as expected on the old architecture. You can follow along in [the issue-640 branch](https://github.com/grahammendick/navigation/compare/issue-640)

https://user-images.githubusercontent.com/1761227/193456963-f3eba111-7b9a-4539-9b1f-a4f7c958778d.mov

**Comment by iamyellow** [comment]
looks good! about using native resources, as simple as passing the src with the uri being the name of the resource. on android, the drawable file and on ios the name on the xcode image set editor. using native resources i'm pretty sure we can avoid being async and just pass the uri beacuse that's how it works on native (see my first comment with the imageNamed).

**Comment by grahammendick** [comment]
Thanks for the explanation. You don't need patch package because image props already [support native resources](https://reactnative.dev/docs/images#images-from-hybrid-apps-resources) (I've tested this on both the old and new architecture)
```jsx
<NavigationBar backImage={{ uri: 'arrow' }} />
```
```
