### ISSUE TITLE
Pod not installed starting from NavigationReactNative v8.11.0

### ISSUE THREAD

**Issue by alexstanbury** [grahammendick/navigation#651]
From NavigationReactNative v8.11.0 onwards there is no pod installed when running `pod install`, making this library unusable.

**Comment by grahammendick** [comment]
I've [update the Twitter sample to the latest navigation-react-native](https://github.com/grahammendick/navigation/pull/652) and it works find on iOS and Android

**Comment by alexstanbury** [comment]
Interesting, my project is using:

"react": "17.0.2",    
"react-native": "0.67.2",
"navigation": "^6.1.0",
"navigation-react": "^4.5.1",
"navigation-react-native": "8.10.1",

**Comment by grahammendick** [comment]
There's nothing wrong with the `navigation-react-native` package. Are you upgrading `react-native` to a later version because that's likely the problem - it's quite error prone?

**Comment by grahammendick** [comment]
Oh, maybe it's because you're on an old version of `react-native`? Could you try deleting `react-native.config.js` file from the `navigation-react-native` folder and see if it works?

**Comment by alexstanbury** [comment]
No, I'm not upgrading react native. I just tried updating this library to the latest version and noticed that on iOS at runtime it wasn't finding NvNavigationStack which I then realised was because no pod was installed. Through trial and error I worked backwards to the version that actually installs the pod.

**Comment by alexstanbury** [comment]
> Oh, maybe it's because you're on an old version of `react-native`? Could you try deleting `react-native.config.js` file from the `navigation-react-native` folder and see if it works?

Yes, this works

**Comment by grahammendick** [comment]
Oh great, thanks. Are you ok with that workaround for now and I'll keep this open while I work on a proper fix?

**Comment by alexstanbury** [comment]
Yeah no problem 👍

**Comment by grahammendick** [comment]
@alexstanbury Hey, I've put together a PR. Could you try out the [react-native-config from that PR](https://github.com/grahammendick/navigation/pull/653/files) and let me know if it works for you, please?

**Comment by grahammendick** [comment]
@alexstanbury You free to test this out, please?

**Comment by alexstanbury** [comment]
@grahammendick Sorry, I've been away. Tested it and it works, thanks.

**Comment by grahammendick** [comment]
Great, thanks for testing 👍
