### ISSUE TITLE
Jest cannot test the component which use the RightBar

### ISSUE THREAD

**Issue by anhtuank7c** [grahammendick/navigation#654]
## Issue
![image](https://user-images.githubusercontent.com/3163410/198843081-94d04a46-00a9-43e5-b2e4-e39a5ae8c9eb.png)

## code

```
//devSetting component

import {NavigationContext, NavigationEvent} from 'navigation-react';
import {BarButton, NavigationBar, RightBar} from 'navigation-react-native';
import React, {useContext} from 'react';
import {ScrollView, Text} from 'react-native';
import { RootNavigationTypes } from '../../../../app.types';

export const DevSettingsScreen = () => {
  const {stateNavigator} = useContext<NavigationEvent<RootNavigationTypes>>(NavigationContext);
  return (
    <>
      <NavigationBar
        title="Dev Settings"
        backTitle=""
        onNavigationPress={() => stateNavigator.navigateBack(1)}
        navigationImage={require('../../../../../assets/arrow-left.png')}>
        <RightBar>
          <BarButton title="Reset" show="ifRoom" />
        </RightBar>
      </NavigationBar>
      <ScrollView contentInsetAdjustmentBehavior="automatic">
        <Text>Dev Settings Screen</Text>
      </ScrollView>
    </>
  );
};

// test file
import 'react-native';
import React from 'react';
import {DevSettingsScreen} from './dev-settings-screen';
import {render, screen} from '@testing-library/react-native';

it('renders correctly', () => {
  render(<DevSettingsScreen />)
  expect(screen).toBeTruthy();
});


```

**Comment by grahammendick** [comment]
Thanks for the interesting issue. I've got more digging to do, but it looks like I need to provide jest mocks for the Navigation router components

**Comment by grahammendick** [comment]
I've started working on this. You can [follow along in the issue-654 branch](https://github.com/grahammendick/navigation/compare/issue-654)

**Comment by anhtuank7c** [comment]
Great, I think you must add `BarButton: ({children}) => children,` to the list too.
I added it myself and work great.

**Comment by grahammendick** [comment]
Yep, thanks 👍 I might mock it as a ReactNative `Button` because then you can do `getByRole('button')`. 
```jsx
BarButton: (props) => <ReactNative.Button {...props} />
```
I'll make sure all the mocks have the expected accessibility roles so that you can find them in your unit tests. Android and iOS give them the right accessibility roles when the app runs for real because all the components render to the native primitives on both platforms

**Comment by anhtuank7c** [comment]
Great work

**Comment by grahammendick** [comment]
Mocking it as a `Button` also means you can press it
```jsx
const reset = getByRole('button', {name: 'Reset'});
fireEvent.press(reset);
```

**Comment by anhtuank7c** [comment]
Should we close this issue or wait for the merge of Jest mock?

**Comment by grahammendick** [comment]
I'll keep this open until I merge in the mocking work. I'm really enjoying working on the mocks so thank you so much for raising this issue! I plan to mock every component so that everything is unit-testable. That will allow me to add extra functionality that only exists in native, for example, I can mock the 'native' back button in the `NavigationBar`

```jsx
const reset = getByRole('button', {name: 'Back'});
fireEvent.press(reset);
```

**Comment by grahammendick** [comment]
Hey there! I've finished [the PR that mocks all the Navigation router components](https://github.com/grahammendick/navigation/pull/657) so they work with React Native Testing Library. Could you test out [the mocks](https://github.com/grahammendick/navigation/pull/657/files#diff-7d1f250cf8a40c4888c00b3400c3e903c5ee78d935fd41ff5234aa21b2fbe064) and let me know if you're happy, please?

**Comment by anhtuank7c** [comment]
@grahammendick Sure I will. Thanks for your hard work

**Comment by grahammendick** [comment]
@anhtuank7c How you getting on?

**Comment by anhtuank7c** [comment]
@grahammendick Sorry for the late reply. It works just great.
