### ISSUE TITLE
hidesTabBar does not work on Android

### ISSUE THREAD

**Issue by anhtuank7c** [grahammendick/navigation#655]
## Issue

* Cannot hide tabbar in the stack of an Android platform, it work great on iOS.
* Missing hidesTabBar props on the document page?? (I haven't found anything related)

## Code
```
<NavigationHandler stateNavigator={feedNavigator}>
      <NavigationStack>
        <Scene<FeedTypes> stateKey="feed">
          <FeedScreen />
        </Scene>
        <Scene<FeedTypes> stateKey="post" hidesTabBar>
          <PostScreen />
        </Scene>
      </NavigationStack>
    </NavigationHandler>
```

## Video
https://user-images.githubusercontent.com/3163410/198862661-9285f2f4-5e4d-4307-b794-76a87f06ef6b.mov

**Comment by grahammendick** [comment]
The aim of the Navigation router is to provide the same navigation primitives as you'd get if you were building a native app without react native. On iOS there is a [native hidesBottomBarWhenPushed property](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621863-hidesbottombarwhenpushed) but there's no equivalent primitive on Android.

I haven't documented every prop in the online docs. The typescript definition files provide the full API documentation. But I can see the value in documenting the full API online, too.

**Comment by anhtuank7c** [comment]
Oh thank you for that

**Comment by grahammendick** [comment]
I [sketched out a way to hide the tab bar on Android](https://github.com/grahammendick/navigation/discussions/765#discussioncomment-8267764). It's not quite the same as ios because can't have A -> B -> C with tab bar on A and C but not B. Once the tab bar is hidden on B it stays hidden for navigations from B
