### ISSUE TITLE
Is there any chance to switch to another tab?

### ISSUE THREAD

**Issue by anhtuank7c** [grahammendick/navigation#656]
I would like to switch to another tab but not sure how to do it.

**Comment by grahammendick** [comment]
Hey there! Yes, you can take control of the active tab.
```jsx
const [tab, setTab] = useState(0);
<TabBar tab={tab} onChangeTab={setTab}>
```
Then you can call `setTab(1)`, for example, to change tabs programmatically.

**Comment by anhtuank7c** [comment]
Thanks. it works great.
