### ISSUE TITLE
Qs (navigation-react) Dynamically change title?

### ISSUE THREAD

**Issue by greenais** [grahammendick/navigation#658]
I there a way to change page title on the fly? 
Once I create states 
```
const stateNavigator = new Navigation.StateNavigator([
  {key: 'OrgList', route: 'orglist', title: 'Lista de organizadores: ', trackTypes: false},
  {key: 'OrgView', route: 'orgview', title: 'Organizador', trackTypes: false},
], new HTML5HistoryManager());
```
is there option to change title, replacing default 'Organizador' with actual org name programmatically on usage of .navigate function?

Couldn't find such a mention anywhere in docs...

**Comment by grahammendick** [comment]
Hey there, thanks for the question. You could use an `onNavigate` listener but I prefer `useEffect` because you likely already have access to the organisation name within your component.

```jsx
useEffect(() => {
  document.title = name;
}, [name]);
```

**Comment by greenais** [comment]
Yep, I've already made document.title  in componentDidMount (personally I prefer old-school reactiveness)), just was wondering if it's possible via navigation.
Thank you!
