### ISSUE TITLE
Simple NavigationMotion without any animation

### ISSUE THREAD

**Issue by RichardLindhout** [grahammendick/navigation#660]
![Scherm­afbeelding 2022-12-22 om 12 09 48](https://user-images.githubusercontent.com/6492229/209121765-fd60700a-9b9b-4d45-b18a-b453ff26c150.png)

I currently have an NavigationMotion without any animation. It works but it gives me warnings. Is there a possibility to have a 'simpler' <NavigationMotionBasic> component which only does push screens on top of each other
```tsx
    <NavigationMotion
      duration={0}
      renderMotion={(_, scene, __, ___, state, data) => (
        <View
          style={[
            StyleSheet.absoluteFill,
            {
              backgroundColor: theme.layout.backgroundColor,
            },
          ]}
        >
          <OptimizedContextProvider screenKey={state.key} data={data}>
            {scene}
          </OptimizedContextProvider>
        </View>
      )}
    />
```

**Comment by grahammendick** [comment]
Hey there. Happy Xmas! You can set duration to 0. I tried it out in the [twitter sample and didn't get any warnings](https://github.com/grahammendick/navigation/blob/9bea5b9c72a1d49f14fe576fe59f47a627149607/NavigationReactMobile/sample/twitter/Twitter.js#L11). It looks like those warnings are coming from your code (`AnimatedWithChildren` isn't a Navigation router component).

**Comment by RichardLindhout** [comment]
Ok, thank you!
