### ISSUE TITLE
Bottom Sheet sheet collapsed as soon as you start scrolling down ?

### ISSUE THREAD

**Issue by a-eid** [grahammendick/navigation#666]
I'm trying to use the BottomSheet component on android, with a nested scrollable component, it works fine when your scroll down, but as soon as you start scrolling to the top it dismisses the BottomSheet. it should only do that if there is no more scrollable area to scroll to.

https://user-images.githubusercontent.com/19273413/217121541-fe301da9-c7cb-41c5-b7fc-7fea17035590.mp4

```ts
<CoordinatorLayout>
  <Button title={detent === "collapsed" ? "Expand" : "Collapse"} onPress={() => setDetent(detent => (detent === "collapsed" ? "expanded" : "collapsed"))} />
  <BottomSheet peekHeight={0} expandedHeight={400} defaultDetent="collapsed" detent={detent} onChangeDetent={setDetent}>
    <ScrollView nestedScrollEnabled>
      <View style={{ height: 100, backgroundColor: "green" }} />
      <View style={{ height: 100, backgroundColor: "blue" }} />
      <View style={{ height: 100, backgroundColor: "red" }} />
      <View style={{ height: 100, backgroundColor: "yellow" }} />
      <View style={{ height: 100, backgroundColor: "green" }} />
      <View style={{ height: 100, backgroundColor: "blue" }} />
      <View style={{ height: 100, backgroundColor: "red" }} />
      <View style={{ height: 100, backgroundColor: "yellow" }} />
    </ScrollView>
  </BottomSheet>
</CoordinatorLayout>
```

is there any intention to bring this component to IOS as well, what do you use as an alternative on android  ?

**Comment by grahammendick** [comment]
Your example code works great for me. You can see in the vid below that the `BottomSheet` doesn't start dismissing until the scrollable content is scrolled to the top.

https://user-images.githubusercontent.com/1761227/218250672-0d2ab380-b660-4315-a080-c8254b334b6a.mov

I did try to implement the `BottomSheet` on iOS, but ran into the [same problems that React Native are facing adding detents to their Modal](https://github.com/facebook/react-native/pull/34834#issuecomment-1420488482). I'm hopeful BottomSheet on iOS will be possible when React Native implement synch rendering on Fabric.

**Comment by a-eid** [comment]
hmm that's weird, I'll test again with another emulator and/or an actual phone.

**Comment by grahammendick** [comment]
Hey, could you paste this code into the [Grid component of the zoom sample](https://github.com/grahammendick/navigation/blob/master/NavigationReactNative/sample/zoom/Grid.js) and then run it on your emulator, please? It works great for me. Make sure you take the latest code because the zoom sample has the latest navigation-react-native and android material components.

```jsx
import React, {useState} from 'react';
import {View, ScrollView, Button} from 'react-native';
import {CoordinatorLayout, BottomSheet} from 'navigation-react-native';

const Grid = ({colors}) => {
  const [detent, setDetent] = useState('collapsed');
  return (
    <CoordinatorLayout>
      <Button title={detent === "collapsed" ? "Expand" : "Collapse"} onPress={() => setDetent(detent => (detent === "collapsed" ? "expanded" : "collapsed"))} />
      <BottomSheet peekHeight={0} expandedHeight={400} defaultDetent="collapsed" detent={detent} onChangeDetent={setDetent}>
        <ScrollView nestedScrollEnabled>
          <View style={{ height: 100, backgroundColor: "green" }} />
          <View style={{ height: 100, backgroundColor: "blue" }} />
          <View style={{ height: 100, backgroundColor: "red" }} />
          <View style={{ height: 100, backgroundColor: "yellow" }} />
          <View style={{ height: 100, backgroundColor: "green" }} />
          <View style={{ height: 100, backgroundColor: "blue" }} />
          <View style={{ height: 100, backgroundColor: "red" }} />
          <View style={{ height: 100, backgroundColor: "yellow" }} />
        </ScrollView>
      </BottomSheet>
    </CoordinatorLayout>
  );
};

export default Grid;
```

**Comment by grahammendick** [comment]
I'll keep this open for another 2 weeks. Hopefully I'll hear back from you by then 🙏
