### ISSUE TITLE
How to make StatusBar translucent on android ?

### ISSUE THREAD

**Issue by a-eid** [grahammendick/navigation#667]

**Comment by grahammendick** [comment]
Could you tell me what you're trying to do, please? Are you trying to [display edge to edge content](https://developer.android.com/develop/ui/views/layout/edge-to-edge)?

**Comment by a-eid** [comment]
yes exactly, I'm trying to display edge to edge content.

**Comment by grahammendick** [comment]
Cool. Would you be interested in [working through the android doc](https://developer.android.com/develop/ui/views/layout/edge-to-edge) and letting me know if there's anything the Navigation router should be doing?

**Comment by a-eid** [comment]
I usually use expo managed workflow by default for all my apps, expo allows me to set an app.json option to have a translucent statusbar, however it break keyboard handling on android for some reason.

so to achieve that I either use `ExpoStatusbar` with the translucent option or the react navigation native stack option [statusbartranslucent](https://github.com/software-mansion/react-native-screens/tree/main/native-stack#statusbartranslucent-android-only)

I thought it might be something you add to the statusbar component since I can't use either expo statusbar or RN statusbar component.

**Comment by grahammendick** [comment]
Yea, I can see how making the status bar translucent would opt in to edge to edge. Would you be interested in working on this?

**Comment by RichardLindhout** [comment]
You can apply 
```
    androidStatusBar: {
      translucent: true,
    },
```
to the expo config

**Comment by a-eid** [comment]
@RichardLindhout that is correct, however it misses up how the keyboard is handled on android.

**Comment by burakgormek** [comment]
> @RichardLindhout that is correct, however it misses up how the keyboard is handled on android.

Not sure if it's related but if you wrap your app with KeyboardAvoidingView, try to set behavior prop to "padding" like iOS.

**Comment by grahammendick** [comment]
I got it working on Android. I turned on [edge to edge](https://developer.android.com/develop/ui/views/layout/edge-to-edge#lay-out-in-full-screen) in the Activity
```java
@Override
protected void onCreate(Bundle savedInstanceState) {
  super.onCreate(savedInstanceState);
  WindowCompat.setDecorFitsSystemWindows(getWindow(), false);
}
```

Then I made the `NavigationBar` and `StatusBar` transparent and shifted the content up with -60 margin top.
```jsx
<View collapsable={false} style={{flex: 1}}>
  <NavigationBar title="Home" barTintColor="transparent">
    <StatusBar barTintColor="transparent" tintStyle="dark" />
  </NavigationBar>
  <ScrollView style={{ marginTop: -60}}>
</View>
```

**Comment by grahammendick** [comment]
I'll keep this open for another 2 weeks. Hopefully I'll hear back from you 🙏

**Comment by afkcodes** [comment]
@grahammendick  Just here, for appreciating the amazing work you have done and the efforts you have put in. Do you have a discord channel or something where all can basically join and interact/ask questions and other stuff

**Comment by grahammendick** [comment]
Thanks @afkcodes, it's great to hear you like the Navigation router. Please ask me any question you want by raising an issue or a discussion (or, if you don't want to ask in public, you can message me on Twitter [@grahammendick](https://twitter.com/grahammendick)). I'm looking forward to chatting with you.

**Comment by grahammendick** [comment]
Closing this [as agreed](https://github.com/grahammendick/navigation/issues/667#issuecomment-1472658856)
