### ISSUE TITLE
IOS Tabbar [__NSArrayM insetObject:atIndex:]: object cannot be nil.

### ISSUE THREAD

**Issue by a-eid** [grahammendick/navigation#668]
I'm trying to use Tabbar on ios but getting this error.

<img width="409" alt="Screenshot 2023-02-06 at 20 00 57" src="https://user-images.githubusercontent.com/19273413/217128778-bc3398f6-63f1-4ba7-8f7d-7f02bb816ecc.png">

```tsx
<NavigationHandler stateNavigator={stateNavigator}>
  <NavigationStack>
    <Scene stateKey="hello" backgroundColor="red">
      <TabBar bottomTabs rippleColor="transparent" labelVisibilityMode="auto" tab={0}>
        <TabBarItem title="Personal" image={require("./bird.png")}>
          <Hello />
        </TabBarItem>
        <TabBarItem title="Work" image={require("./bird.png")}>
          <World />
        </TabBarItem>
      </TabBar>
    </Scene>
  </NavigationStack>
</NavigationHandler>
```

**Comment by grahammendick** [comment]
Hey again, long time no hear. On iOS, the `TabBar` defaults to primary so it expects each `TabBarItem` to have a `NavigationHandler/Stack` child. That's how the native [UITabBarController](https://developer.apple.com/documentation/uikit/uitabbarcontroller) works on iOS. If you want tabs without stacks then set the `primary` prop to false on the `TabBar`.

**Comment by grahammendick** [comment]
I saw your 👍 You happy to close?

**Comment by a-eid** [comment]
@grahammendick sure, I was just waiting to try it tonight or tomorrow :)
