### ISSUE TITLE
Option to disable freeze

### ISSUE THREAD

**Issue by RichardLindhout** [grahammendick/navigation#687]
I think some bugs in my apps are due too freezing the screen is it possible to disable freezing?

**Comment by grahammendick** [comment]
Can you tell me what kind of problems you're getting, please?

**Comment by RichardLindhout** [comment]
https://youtube.com/shorts/g_j9SoBObAI

**Comment by RichardLindhout** [comment]
Seems like this exact issue: https://stackoverflow.com/questions/38017780/scrolling-content-inside-a-fixed-position-div-on-mobile-safari-suddenly-stops

**Comment by RichardLindhout** [comment]
I think i've pinned it down. In the edited example the issue also occurs if https://g037fr.csb.app/ 
```
 body {
        overflow: hidden;
      }
      ```
      
      is commented. So just need to add that!
