### ISSUE TITLE
Remove or Hide Flashing while Navigating [Font Family not getting reflected]

### ISSUE THREAD

**Issue by afkcodes** [grahammendick/navigation#691]
Hello, Graham, thanks for this amazing navigation library was pretty simple to setup, also how can i theme the bottom navigation bar

How can i reduce flashing while navigation. I am attaching a screen-record of the same. This is not visible in some of the apps that are built natively also on react native that i know.

https://user-images.githubusercontent.com/17390257/229299259-a9912a49-4372-4d8f-b7ef-e374a38bcc95.mp4

**Comment by grahammendick** [comment]
Hey Ashish, thanks for getting in touch.

You'll find the [documentation for the bottom tabs under the section titled 'Adding Top Level Navigation Tabs'](https://grahammendick.github.io/navigation/documentation/native/tab-bar.html). You can also see [tabs in action in the Twitter sample](https://github.com/grahammendick/navigation/tree/master/NavigationReactNative/sample/twitter).

The default [Android transition animates the opacity which causes the white background to show through](https://github.com/grahammendick/navigation/pull/646). With a dark scene like yours you'll see a gray flash. Setting a transparent background on Android prevents the scene going gray.
```jsx
<NavigationStack
  backgroundColor={() => Platform.OS === 'android' ? 'rgba(255,255,255,0)' : 'white'}>
```

**Comment by afkcodes** [comment]
thanks for the quick reply @grahammendick  i went through the earlier issues and tried this i think the opacity value was not there i will check this out. also i am unable to change the color of the unselected tab text color i have set 

unselectedTintColor ="white"

**Comment by grahammendick** [comment]
Make sure you update to the latest `navigation-react-native` because it fixes the [unselectedTintColor not working on iOS](https://github.com/grahammendick/navigation/issues/682)

**Comment by afkcodes** [comment]
i am on android 13.

**Comment by grahammendick** [comment]
I set `unselectedTintColor` to 'red' in the Twitter sample on android and it's working. Can you try the same in [the Twitter sample](https://github.com/grahammendick/navigation/blob/5420aba1eca8097ddab298dda9d3f9ea0a7dcd2b/NavigationReactNative/sample/twitter/Tabs.js#L24), please?

![image](https://user-images.githubusercontent.com/1761227/229303591-73e2ce8c-0e68-40c9-8ead-7727d5ca1b9b.png)

**Comment by afkcodes** [comment]
i am trying the same , but not able to run the twitter sample its giving me some error

**Comment by grahammendick** [comment]
You [followed the instructions](https://github.com/grahammendick/navigation/tree/master/NavigationReactNative/sample/twitter#run) in the readme (make sure you've pod installed)?

**Comment by grahammendick** [comment]
I can never remember if you need to pod install on Android (you do on the new architecture so I get confused)

**Comment by afkcodes** [comment]
yes for android its not required to do pod install

**Comment by grahammendick** [comment]
Can you try a fresh clone of the Navigation router repo?

**Comment by afkcodes** [comment]
sure will try out

**Comment by afkcodes** [comment]
![Screenshot_20230402-010538_twitter](https://user-images.githubusercontent.com/17390257/229310755-4c9a0a7d-a368-462e-8e29-14f6aa9f46e9.png)



for me its coming like this

**Comment by grahammendick** [comment]
How did you get it running when you got an error before?

**Comment by grahammendick** [comment]
I'm not sure why but it looks like React Native is defaulting everything to white/transparent when it hasn't been explicitly set. Can you set the `tintColor` of the `NavigationBar` and the `color` of the `Text` in the `TweetItem` to 'black, for example?

**Comment by afkcodes** [comment]
> How did you get it running when you got an error before?

Cleaned the whole project and recloned and then it worked

**Comment by afkcodes** [comment]
> I'm not sure why but it looks like React Native is defaulting everything to white/transparent when it hasn't been explicitly set. Can you set the `titleColor` of the `NavigationBar`, `unselectedTintColor` of the `TabBars` and the `color` of the `Text` in the `TweetItem` to 'black', for example?

What i found is when i have less than 4 TabBarItem the unselectedTintCOlor works fine but if i add 4th then the issue happens

**Comment by afkcodes** [comment]
Found the fix in closed issue thanks @grahammendick

**Comment by grahammendick** [comment]
That's great. Could you explain what the problem was and, if you're happy, close this issue please?

**Comment by afkcodes** [comment]
so basically by default if you have more than 3 items in tab bar then only selected ones will show the text, we have to explicitly set labelVisiblity to labeled. 

also i wanted to know why the font family is not getting applied to bottom navigation text

**Comment by grahammendick** [comment]
Found out that passing [custom font family strings to TypefaceSpan](https://github.com/grahammendick/navigation/blob/f787baef76c3e4e9f73f5f6e37dd61fec02369d7/NavigationReactNative/src/android/src/main/java/com/navigation/reactnative/TabBarItemView.java#L137) doesn't work. Instead, the Navigation router needs to get the `TypeFace` from the `ReactFontManager` instead.

Would you be interested in making a PR with the fix outlined below? It would need to go into 4 places (TabBarItemView, BarButtonView, ExtendedFloatingActionButtonView, ToolBarView)  

```java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P)
    titleSpannable.setSpan(new TypefaceSpan(ReactFontManager.getInstance().getTypeface(fontFamily, 0, null)), 0, title.length(), 0);
else
    titleSpannable.setSpan(new TypefaceSpan(fontFamily), 0, title.length(), 0);
```

**Comment by afkcodes** [comment]
@grahammendick i would try but not sure, how efficient it will be, have very little idea about native code.

**Comment by grahammendick** [comment]
It's up to you, no pressure. Whatever you decide is cool. Let me know either way so I know whether or not to put it on my list

**Comment by afkcodes** [comment]
I have raised a PR: #694 Please have a look @grahammendick

**Comment by grahammendick** [comment]
Thanks v much for the PR. I really appreciate it!

Now for you other question about svg's. The `image` prop on the `TabBarItem` works the same as the `source` prop on the React Native `Image` component. So I think you can use [svg's if they're bundled with the native app](https://reactnative.dev/docs/images#images-from-hybrid-apps-resources).

**Comment by afkcodes** [comment]
I tried with svg, but it was not getting shown

**Comment by grahammendick** [comment]
From [React Native Images From Hybrid App's Resources doc](https://reactnative.dev/docs/images#images-from-hybrid-apps-resources).
> For images included via Xcode asset catalogs or in the Android drawable folder, use the image name without the extension:
```jsx
<Image
  source={{uri: 'app_icon'}}
  style={{width: 40, height: 40}}
/>
```

**Comment by afkcodes** [comment]
will try this later currently i have used png. also i have added ripple color but it doesnt seems to be visible

**Comment by afkcodes** [comment]
I am closing this issue as this has been a pretty long thread. please update once the PR gets merged

**Comment by grahammendick** [comment]
Ripple color is only relevant if you're using a Material3 Theme, for example, [Theme.Material3.DayNight.NoActionBar like in the zoom sample](https://github.com/grahammendick/navigation/blob/352ac3823bc87a9bdcd1fc54018527d0b08c9e9a/NavigationReactNative/sample/zoom/android/app/src/main/res/values/styles.xml#L4). Android added ripple color when it updated its [Bottom Tab Bar to Material 3](https://m3.material.io/components/navigation-bar/overview). I recommend you use a Material3 theme because you'll get the modern android look and feel.

**Comment by grahammendick** [comment]
You can leave this open. GitHub will automatically close it when the PR is merged

**Comment by afkcodes** [comment]
found another issue, where bottom navigation title fontsize is small for first two items and bigger for next two items
it happens when we use labelVisiblity="labeled"

**Comment by afkcodes** [comment]
Also can you tell me what i might be doing wrong here, so that the history is messed up. if you can see i go back from any path it comes back to home tab
https://user-images.githubusercontent.com/17390257/229365668-30b11b14-f133-40c0-b344-06cfe95f0de9.mp4

**Comment by grahammendick** [comment]
When you press the Android back, the TabBar always goes back to the first tab. Have you seen a native app that goes back through all the tabs in the order you visited them?

**Comment by grahammendick** [comment]
I added labelVisibilityMode="labeled" to the Twitter sample and the font size is the same for all tabs

![image](https://user-images.githubusercontent.com/1761227/229366724-282a83c1-cfa6-4aa6-9d72-c160e09413ef.png)

**Comment by grahammendick** [comment]
You can add your own Android back button handler and go back through the tabs if you want. You can track the active tab by storing it in state.
```jsx
const [tab, setTab] = useState(0);
<TabBar tab{tab} onChangeTab={setTab} >
```

**Comment by afkcodes** [comment]
> When you press the Android back, the TabBar always goes back to the first tab. Have you seen a native app that goes back through all the tabs in the order you visited them?

yes i have checked other apps it goes through all the visited tabs

**Comment by afkcodes** [comment]
> I added labelVisibilityMode="labeled" to the Twitter sample and the font size is the same for all tabs
> 
> ![image](https://user-images.githubusercontent.com/1761227/229366724-282a83c1-cfa6-4aa6-9d72-c160e09413ef.png)

can you make the 3rd tab active and check

**Comment by afkcodes** [comment]
> You can add your own Android back button handler and go back through the tabs if you want. You can track the active tab by storing it in state.
> 
> ```js
> const [tab, setTab] = useState(0);
> <TabBar tab={tab} onChangeTab={setTab} >
> ```

This can probably fix tab but history will still be messed up i guess here is an example of nested history.


https://user-images.githubusercontent.com/17390257/229376835-873460ea-2e84-4e28-bc63-3e24e8284559.mp4

**Comment by afkcodes** [comment]
if you see above the tab bar and and stack history is synced the tab only changes when the particular tab history/stack is empty and then it moves to previous tab

**Comment by afkcodes** [comment]
Also one more thing i wanted to say please don't think that i am nitpicking stuff, i have used React Navigation before and i can easily say that this navigation router is super fast and performant than react navigation. I had left react native for almost a year now and when i came across your library i was blown away. The amount of hardwork you have put in is commendable. I want this to be the go to for all my apps and same goes for others as well. once people start using it this will have more contributors as well. There are some minor things such as i mentioned above like history and might be others as well. but so far this is so good to use.  Thanks again @grahammendick

**Comment by grahammendick** [comment]
> if you see above the tab bar and and stack history is synced the tab only changes when the particular tab history/stack is empty and then it moves to previous tab

If you add your own Android back handler then it will work exactly like you want. React Native will go through the stack history first and only when it's back to the beginning will it call your back handler.

**Comment by grahammendick** [comment]
> can you make the 3rd tab active and check

![image](https://user-images.githubusercontent.com/1761227/229377754-72750d02-f302-47f6-811a-8c762e106687.png)

**Comment by grahammendick** [comment]
> Also one more thing i wanted to say please don't think that i am nitpicking stuff

Not at all. I'm so glad you're enjoying using the Navigation router. I appreciate you taking the time to provide feedback. Keep it coming. Please tell all your friends about the Navigation router because I've had no luck getting the word out!

**Comment by afkcodes** [comment]
> > if you see above the tab bar and and stack history is synced the tab only changes when the particular tab history/stack is empty and then it moves to previous tab
> 
> If you add your own Android back handler then it will work exactly like you want. React Native will go through the stack history first and only when it's back to the beginning will it call your back handler.

will try this out and let you know. if possible you can provide a simple example.

**Comment by afkcodes** [comment]
> > Also one more thing i wanted to say please don't think that i am nitpicking stuff
> 
> Not at all. I'm so glad you're enjoying using the Navigation router. I appreciate you taking the time to provide feedback. Keep it coming. Please tell all your friends about the Navigation router because I've had no luck getting the word out!

Sure i will voice it out once i am done with the stuff i am working on. Also you have to be more active on reddit as i came to know about navigation router from one of the comments you made on  a post on react native subreddit.

**Comment by grahammendick** [comment]
>  if possible you can provide a simple example.

```jsx
const [tab, setTab] = useState(0);
useEffect(() => {
  const goToPreviousTab = () => setTab(1);
  const backHandler = BackHandler.addEventListener('hardwareBackPress', goToPreviousTab);
  return () => backHandler.remove();
});
return (
  <TabBar tab={tab} onChangeTab={setTab}>
```

**Comment by afkcodes** [comment]
https://user-images.githubusercontent.com/17390257/229562678-56812627-0294-4bcb-90da-ac52cf465f8f.mp4

Tried the above snippet the it goes in a navigation loop kinda thing

**Comment by grahammendick** [comment]
That's code snippet is just a clue. It's not the actual code. You'll need to keep track of which tab is active and then see if you have to go back.

**Comment by afkcodes** [comment]
> That code snippet is just a clue. It's not the actual code. You'll need to keep track of which tab is active and then see if you have to go back.

understood thanks

**Comment by grahammendick** [comment]
> i came to know about navigation router from one of the comments you made on a post on react native subreddit

Can you remember what comment got you interested?

**Comment by afkcodes** [comment]
> > i came to know about navigation router from one of the comments you made on a post on react native subreddit
> 
> Can you remember what comment got you interested?

It think this is the one https://www.reddit.com/r/reactnative/comments/snsqlg/react_navigation_v6_vs_react_native_navigation/

**Comment by grahammendick** [comment]
It takes me a while to merge because I have to test it. I have to test out TabBarItemView, BarButtonView, ExtendedFloatingActionButtonView and ToolBarView with/out Custom Font. I have to repeat this testing on Fabric (the new architecture), too. 

I should get round to it in the next few days.

**Comment by grahammendick** [comment]
I realised that going [back through the visited tabs was a bit harder than I first thought](https://github.com/grahammendick/navigation/issues/691#issuecomment-1493845788) so I've written a hook that will do it for you

```jsx
useTabBackAndroid = () => {
  const [tab, setTab] = useState(0)
  const tabsVisited = useRef([0]);
  useEffect(() => {
    if (tab) {
      const i = tabsVisited.current.indexOf(tab);
      if (i > -1) tabsVisited.current.splice(i, 1);
      tabsVisited.current.push(tab);
    }
  }, [tab]);
  useEffect(() => {
    const goBack = () => {
      const visited = tabsVisited.current;
      if (visited.length > 1) {
        visited.pop();
        setTab(visited[visited.length - 1]);
        return true;
      };
      return false;
    }
    const backHandler = BackHandler.addEventListener('hardwareBackPress', goBack);
    return () => backHandler.remove();
  }, []);
  return [tab, setTab];
}
```

And you use it like this
```jsx
  const [tab, setTab] = useTabBackAndroid();
  return (
      <TabBar tab={tab} onChangeTab={setTab}
```

**Comment by grahammendick** [comment]
Actually, that's not working with stacks per tabs because of the sequence that the back handlers run in. I'm looking into it

**Comment by grahammendick** [comment]
The tricky part is that sequence that React calls `useEffect` clashes with the sequence React Native calls the Android back handlers. 

In React, the useEffect calls go up the tree. It calls children `useEffects` before the parent.
In React Native, the Android back handlers are called in the reverse order that they're added.

So the Navigation router TabBar back handler (child) is called before any custom back handler you add in your Tabs component (parent).

I plan to add a `handleBack` prop to the TabBar component so that you can provide your own back behaviour. I've tried it with the following code and it works great. I'm going to sleep on it and see if I still think it's a good idea in the morning.


```jsx
const [tab, setTab] = useState(0)
const tabsVisited = useRef([0]);
useEffect(() => {
  if (tab) {
    const i = tabsVisited.current.indexOf(tab);
    if (i > -1) tabsVisited.current.splice(i, 1);
    tabsVisited.current.push(tab);
  }
}, [tab]);
const handleBack = () => {
  const visited = tabsVisited.current;
  if (visited.length > 1) {
    visited.pop();
    setTab(visited[visited.length - 1]);
    return true;
  };
  return false;
}
return (
    <TabBar tab={tab} onChangeTab={setTab} handleBack={handleBack}>
```

**Comment by grahammendick** [comment]
I merged in [support for custom `TabBar` back behaviour](https://github.com/grahammendick/navigation/pull/699). The PR includes a code sample that steps back through through the visited tabs after the active stack is back at the first scene. Thanks @afkcodes
