### ISSUE TITLE
document SSR support

### ISSUE THREAD

**Issue by alidcast** [grahammendick/navigation#697]
from searching commits and examples, looks like SSR is supported (I've yet to try it)

creating an issue so it can be documented on website

**Comment by grahammendick** [comment]
Yes, SSR is supported. The Navigation router documentation isn't just the docs. It's also the samples. I've written [SSR samples for web](https://github.com/grahammendick/navigation/tree/master/NavigationReact/sample/isomorphic) and [mobile](https://github.com/grahammendick/navigation/tree/master/NavigationReactMobile/sample/isomorphic).
