### ISSUE TITLE
rippleColor Prop on TabBar doesnot reflect any color

### ISSUE THREAD

**Issue by afkcodes** [grahammendick/navigation#712]
I have added rippleColor Prop on TabBar but it seems its not changing the color

![Screenshot 2023-07-16 at 1 23 51 PM](https://github.com/grahammendick/navigation/assets/17390257/b6379e28-d218-40fd-843b-2949de1c26dc)

can you tell what i am doing wrong here

**Comment by grahammendick** [comment]
The `rippleColor` works if you configure a Material3 theme in styles.xml, for example,

```xml
<style name="AppTheme" parent="Theme.Material3.DayNight.NoActionBar">
```

Before Material3, the only way to change the ripple color of the `TabBar` is via the `colorControlHighlight` in styles.xml 
```xml
<item name="colorControlHighlight">#ff0000</item>
```

**Comment by afkcodes** [comment]
so there is no option to control the ripple/splash/highlight color when we use material2

**Comment by afkcodes** [comment]
This worked as expected closing this thanks
