### ISSUE TITLE
How to make keyboard as an overlay to the bottom navigation

### ISSUE THREAD

**Issue by afkcodes** [grahammendick/navigation#713]
Currently it pushes up the bottom navigation on top of keyboard. I have added adjustResize in AndroidManifest.xml
![Screenshot 2023-08-03 at 12 21 18 AM](https://github.com/grahammendick/navigation/assets/17390257/446073e2-2ddc-4536-8d85-41fa7d6026c4)

**Comment by grahammendick** [comment]
You could try `adjustPan` instead of `adjustResize`?

**Comment by afkcodes** [comment]
Adjust pan seems to work fine thanks
