### ISSUE TITLE
Goes into a render loop when setting tab with valtio

### ISSUE THREAD

**Issue by afkcodes** [grahammendick/navigation#719]
Hello, mate I was trying to set Tab with a 3rd party state manager, valtio. I have tried a very basic implementation. whenever i change the tab it goes into render loop. useState works fine though.

Below is how i am updating tab
![Screenshot 2023-09-18 at 8 18 37 PM](https://github.com/grahammendick/navigation/assets/17390257/71930ede-b0bb-4768-9e19-6262ad01b749)

here is the valtio state object and setter
![Screenshot 2023-09-18 at 8 17 58 PM](https://github.com/grahammendick/navigation/assets/17390257/051fa127-9568-45e9-ba7e-1ae490e34ffa)

https://github.com/grahammendick/navigation/assets/17390257/5dc0ea18-1237-4933-8b43-7cbc29d9471b

Please let me know if i am doing anything wrong

**Comment by afkcodes** [comment]
Also is it possible to change tab and also pass data to the destination tab ?

**Comment by grahammendick** [comment]
Hey and thanks for the great bug! I'm [testing out a fix](https://github.com/grahammendick/navigation/compare/issue-719).

> Also is it possible to change tab and also pass data to the destination tab ?

When the tab changes update your `valtio` store with the data you want to pass. You can access this data in your destination tab.

**Comment by afkcodes** [comment]
thanks for the suggestion was doing the same, i thought there might be some other way of passing data

**Comment by afkcodes** [comment]
Hello mate, any update on this

**Comment by grahammendick** [comment]
I have to test on iOS and Android and on the old and new architecture. I have to check whether other components with controlled props have the same problem, for example, the 'text' prop on the `SearchBar`.

You're not blocked because you can `useState` for now.

**Comment by grahammendick** [comment]
I was struggling to fix this for ages before I realised [React also suffers from the problem](https://github.com/pmndrs/valtio/issues/270). Turns out if you want to use valtio as backing for a controlled prop then you have to [update synchronously](https://github.com/pmndrs/valtio#update-synchronously)
```jsx
const snap = useSnapshot(tabState, { sync: true })
```

**Comment by afkcodes** [comment]
Thanks for the update i have used my custom solution that works great, will try this as well

**Comment by grahammendick** [comment]
I'll close because I've [tested the sync valtio solution](https://github.com/grahammendick/navigation/issues/719#issuecomment-1732646880)

**Comment by afkcodes** [comment]
cool thanks
