### ISSUE TITLE
ios how to disable navigation borderline

### ISSUE THREAD

**Issue by salisuabubakar** [grahammendick/navigation#720]
Hi, is it possible to disable the  borderline in ios navigation ? below is a picture of the borderline. Thanks

![6QqBy](https://github.com/grahammendick/navigation/assets/6886556/dc9bb956-b072-493f-90b9-777254235420)

**Comment by grahammendick** [comment]
Hey, I don't see any border

```jsx
<View style={{flex: 1, backgroundColor: 'lightblue'}} />
```

![image](https://github.com/grahammendick/navigation/assets/1761227/4082cb67-eb71-4561-8cb9-9688330fdc47)

**Comment by salisuabubakar** [comment]
Hi, thanks for your response. When you set:

 <NavigationBar
        title="Action movies"
        backTitle='Action'
        titleFontWeight={"bold"}
        largeTitle={true}
        titleFontFamily={"GoogleSans-Bold"}
        titleColor={'#ffffff'}
        barTintColor={'black'}
        navigationAccessibilityLabel="Action movies"
        tintColor={"#ffffff"}
        onNavigationPress={() => stateNavigator.navigateBack(1)}>
        <StatusBar tintStyle='light' barTintColor={Platform.OS == "android" ? "black" : 'black'} />
      </NavigationBar>


You will will see 1px gray borderline. Thanks

**Comment by grahammendick** [comment]
Remove the `barTintColor` prop and set the `backgroundColor` on the `SafeAreaView` instead

```jsx
<>
  <NavigationBar title="Action movies" />
  <SafeAreaView style={{flex: 1, backgroundColor: 'lightblue'}} />
</>
```
![image](https://github.com/grahammendick/navigation/assets/1761227/aef0074e-ddf5-45f8-b002-2768fe30a359)

**Comment by grahammendick** [comment]
I'll close this but let me know if you have any further questions
