### ISSUE TITLE
Sample CollapsingBar

### ISSUE THREAD

**Issue by salisuabubakar** [grahammendick/navigation#721]
Hi, do you have a sample code on how to use CollapsingBar.

**Comment by grahammendick** [comment]
Hey, the [Timeline scene in the Twitter sample](https://github.com/grahammendick/navigation/blob/7431e68ee167915f69600fc1c09ae6c7a29ff06f/NavigationReactNative/sample/twitter/Timeline.js#L19) uses the `CollapsingBar`

**Comment by grahammendick** [comment]
Closing, but let me know if you have any questions
