### ISSUE TITLE
Android Large Title

### ISSUE THREAD

**Issue by salisuabubakar** [grahammendick/navigation#722]
Hi, Can i use large title on Android ? ios is very cool . Thanks

**Comment by grahammendick** [comment]
Hey, you can see it in action in the [Timeline scene in the Twitter sample](https://github.com/grahammendick/navigation/blob/7431e68ee167915f69600fc1c09ae6c7a29ff06f/NavigationReactNative/sample/twitter/Timeline.js#L19). Add `largeTitle` prop to the `NavigationBar` and remove the `overlap` prop from the `CoordinatorLayout`
```
<CoordinatorLayout>
  <NavigationBar
    largeTitle
    ...
``` 

https://github.com/grahammendick/navigation/assets/1761227/164ce044-a515-4590-b9b8-7ced27cd2bb4

**Comment by salisuabubakar** [comment]
Hi, Thanks. Its working perfectly.
