### ISSUE TITLE
React native reanimated not working with fabric

### ISSUE THREAD

**Issue by salisuabubakar** [grahammendick/navigation#723]
Hi, am unable to get react native 0.72.4 and react native reanimated 3.5.4 to work with the navigation router fabric. I have the example fabric you ptovided but still the same. No error message. Can you please check. Thank you

**Comment by grahammendick** [comment]
Could you show me the reanimated code that you're adding to the fabric sample, please?

**Comment by salisuabubakar** [comment]
Hi, below is the code:

            <Animated.View
              entering={FadeInDown
                .duration(2000)
                .delay(200)
              }
              layout={Layout.springify().stiffness().mass(0)}>
              <Image
                style={styles.image}
                source={require("../../assets/images/logobg.png")}
              />
            </Animated.View>

Thanks

**Comment by salisuabubakar** [comment]
> Thanks. Are you getting the problem on Android or iOS or both?

Both Android and iOS.

**Comment by salisuabubakar** [comment]
I guess the issue is with my installation. I have tried several time but still the same.

**Comment by grahammendick** [comment]
Have you tried [pasting that code](https://github.com/grahammendick/navigation/issues/723#issuecomment-1743324549) over [the Tabs component in the fabric sample](https://github.com/grahammendick/navigation/blob/master/NavigationReactNative/sample/fabric/Tabs.js)? It worked for me on both Android and iOS

**Comment by salisuabubakar** [comment]
Hi, thanks for your quick response. I had to alot of research and realised react native reanimated layout animation does not work in fabric. I have used transform and its working perfectly. Thanks
