### ISSUE TITLE
Bottom Sheet (IOS)

### ISSUE THREAD

**Issue by salisuabubakar** [grahammendick/navigation#726]
Hi, Can i use bottom sheet on ios using The navigation Router ? If no, can you suggest what the best alternative. Thanks

**Comment by grahammendick** [comment]
No, it's Android-only at the moment. I've tried very hard to get it working on iOS but ran into the same problem [React Native](https://github.com/facebook/react-native/pull/34834#issuecomment-1420488482) and [react native screens](https://github.com/software-mansion/react-native-screens/issues/1722) did when supporting detents. I'm going to have another go when React Native supports synchronous round-trip rendering.

There are many 3rd-party bottom sheet libraries you can try.

**Comment by salisuabubakar** [comment]
Ok. Thanks soo much.

**Comment by grahammendick** [comment]
Hey, I managed to get [Bottom Sheet working on iOS](https://github.com/grahammendick/navigation/pull/744). It'll be in the next release. It's not 100% smooth but it's pretty close. Should be able to smooth it out completely when React Native bring in synchronous rendering

**Comment by grahammendick** [comment]
Just [released navigation-react-native v9.6.0](https://github.com/grahammendick/navigation/releases/tag/v9.6.0-NavigationReactNative) with Bottom Sheet on iOS
