### ISSUE TITLE
Custom Data Type Support

### ISSUE THREAD

**Issue by grahammendick** [grahammendick/navigation#73]
I'm starting this discussion in response to a [question turkish_gold asked on reddit](https://www.reddit.com/r/reactjs/comments/4s8ulw/you_might_not_need_react_router/d593mfd) regarding the navigation data types supported:

> Can you specify a type like month? Or is it constrained to just date?

The answer is 'not currently'. The data types supported are 'string', 'number', 'boolean' and 'date'.
Is there any interest in making the data type support extensible so users can define custom types?
What are the common use cases for passing custom data types?

**Comment by grahammendick** [comment]
I think month type is already supported because you can represent a month as either a 'string', 'number' or a 'date', e.g., `'DEC'`, `12` or `new Date(2000, 11, 1)`.

Maybe what turkish_gold is driving at is supporting a month specified as an object like `{ month: 12 }`? Let me give a bit of background to the Navigation router to explain why custom object types present a problem.

The Navigation router is a data-first router. What that means is that you navigate by passing typed data and that you don't have to think about your Urls until the end. For example, you select an item with id 2 as follows:

    var stateNavigator = new StateNavigator([{
        {key: 'details'}
    });
    stateNavigator.navigate('details', {id: 2});

Notice that, although it's not specified anywhere that id is a 'number', the Navigation router still passes it as a number. The router remembers the id's type by storing it in the Url, '/details?id=21_2'. Whenever you want, you can tidy up the Url to 'details?id=2' by setting the type for the id parameter:

    {key: 'details', defaultType: {id: 'number'}}

This is what I mean by a data-first router. You think in terms of states and typed data. Once you're happy, you can go back and tidy up the Urls without having to touch your code. For example, you could set the Url to 'item/2' by defining the route as well as type: 

    {key: 'details', route: 'item/{id}', defaultType: {id: 'number'}}

After that brief detour, let's return to the object `{ month: 12 }`. If there's no type configured then there's no way to know that it represents a month type. This is different to a number in JavaScript because you can tell it's a number by calling the following:

    Object.prototype.toString.call(obj);

The above call on `{ month: 12 }` will only tell you it's an object, not that it's a month. That means there's no way to store what type it represents in the Url and so it can't be successfully parsed from a string back to the month object. But, forcing the type to be specified upfront breaks the data-first nature of the Navigation router.

**Comment by KaySackey** [comment]
What I was thinking of is that in Django for example, you can represent a route like so

` url(r'^articles/([0-9]{4})/([0-9]{2})/([0-9]+)/$', views.article_detail),`

In this instance, it'll accept a date in YYYY/MM/DD format, as given by the regex. Using regex like that lets you set up fairly complex transforms back and forth between numbers, etc. 

With Rails for example, you can go even further than that and specify constraints for the numbers so you can say YYYY must be >= 1980 and <= 2020. So you'll be sure that any data passed in via the URL router is valid.

What would be nice here is if we could register a handler for converting a URL part. The handler is just a pair of functions to_url() and from_url(), that will handle conversion to/from the url string to a native javascript or app specific object.

That way in the end you'd be able to write something like:

var stateNavigator = new StateNavigator([
  {key: 'articles', route: ''},
  {key: 'article', route: '{year}{month}/{day}/{title}', defaultTypes: {date: 'date', month': 'month', 'day': 'day'}}
]);

Or alternatively, you can parse the default type directly from the route string definition as such:

 route: '{year:year}{month:month}/{day:day}/{string:title}-{number:article_id}',

Where the format is {<parser name>:<variable name>}


What do you think here?

**Comment by grahammendick** [comment]
Thanks for getting involved. I see that you're talking about constraints rather than custom types. That's great news because I'm keen on adding constraints. I've got a great way to implement them that isn't that far away from your first suggestion of conversion functions.

Before I go into my constraints proposal, I'll explain why the second idea of using the route string doesn't work so well. The Navigation router is a data-first router, which means you can change your Urls at any time without impacting your code. In particular, I can change a route parameter to a query string parameter and all the code has to work exactly the same. If the constraint lives with the route then it'll be lost when the parameter is moved to the query string.

My constraints proposal is to add a `validate` function to the state. It's like the `navigated` function you're familiar with but, instead of rendering the content, it validates the incoming navigation data. Here's what it might look like for the year validation you mentioned:

    stateNavigator.states.article.validate = (data) => {
      if (data.getFullYear() < 1980 || data.getFullYear() > 2020)
        return false;
      return true;
    }

You can see that the data's passed in as a Date, not a string. If the data isn't a Date then it would've been rejected earlier and won't reach the validate function. It's more flexible than the Django route constraints because you can run any JavaScript you want. It works on query string and route parameters alike so is in keeping with the Navigation router's data-first approach.

**Comment by grahammendick** [comment]
@KaySackey You happy that my proposal fits the bill?

**Comment by grahammendick** [comment]
@KaySackey I'll close the issue but am happy to reopen if you've anything more to add. If you or anybody else would like to work on the constraints feature proposal I outlined let me know.

**Comment by grahammendick** [comment]
Happy to say that constraints are in Navigation 3.0.0

**Comment by a-lucas** [comment]
@grahammendick  Not sure where to put that, your conception is great!

**Comment by a-lucas** [comment]
To come back on custom data type, I understand your point, a url is a string, no point for trying to pass encoded json in it, (+ it is really ugly ).

I am thinking on a  way to construct object after an url has been matched.

for example: 

    /car/123

would provide 

 {
     id: 123,
     model: 'flying prototype',
     ...
 }


and the logic would be : 

 ```javascript
{
   key: 'carDetails,'
   route: '/car/{id}',
   defaultType: '{id: number}',
   class: 'Car',
   constructor: 'byId'
  }
```

Which would then display the full Object

```javascript
stateNavigator.states.inbox.navigated = function(data) {
    console.log(data.Car);
   /*  
    {
       id: 123,
       model: 'flying prototype',
        ...
      }
   */
}
```

This could be made possible by registering Object Constructors: 

```javascript
//This is a basic model
class CarConstructor {
   static cache = {} // an uuuid indexed obj storing cached data

   static byId(id) {
      // check if it is in the cache first
      // makes an async  fetch() the flux way,
      return toJSON(data); 
   }

   static toJSON(data) {
    //...
   }

   // it could also be possible to 
}
stateNavigator.registerConstructors('Car', CarConstructor);
```

Having such a functionality would make it possible to design an ORM for Redus or FLUX. I know GraphQL exists, and by design GraphQL has bulk queries to bypass the fact that Components define their  own dependencies (For example, a Page contains 1000 Component each having 2 GraphQL - the Page won't make 2000 simultaneous queries ...)

An URL is an index, which represent data. All this information is condensed in a string, making it hard to extract the relevant data from the storages. your approach, imo, allows to overcome this limitation.

Also, this is a suggestion, I am not planning to use such an advanced functionality in the near future - but would love see someone doing it :)

**Comment by grahammendick** [comment]
Hey @a-lucas, thanks for taking the time to share your ideas. I really appreciate it.

Good news. You can already do what you want with the Navigation router. Here's a little example that shows your [car constructor in action](https://codepen.io/grahammendick/pen/KWoWjJ).

In the example I added a `construct` function to the `State` that turns the navigation data into a `Car` fetched from a `cars` cache.
```js
var stateNavigator = new StateNavigator([
  {
    key: 'carDetails',
    route: 'car/{id}',
    defaultType: {id: 'number'},
    construct: data => JSON.parse(cars[data.id])
   }
]);
```
I then listen for when navigations happen and call this `construct` function on the `State` passing in the navigation data.
```js
stateNavigator.onNavigate((oldState, state, data) => {
  console.log(state.construct(data));
});
```
I hope this is what you're after!
