### ISSUE TITLE
TopTabs for Android & iOS

### ISSUE THREAD

**Issue by salisuabubakar** [grahammendick/navigation#730]
Hi, IS there a way to create TopTabs for both android and iOS. Thanks

**Comment by grahammendick** [comment]
Hi, you can have `primary` top tabs on Android but not on iOS. The `UITabBarController` from UIKit doesn’t support top tabs. But you can have non-primary top tabs on iOS if you want?
```jsx
<TabBar primary={Platform.OS === 'android'}  bottomTabs={false}>
```

**Comment by salisuabubakar** [comment]
Hi, its working but i would like to know on iOS is it the same as segment control ?

**Comment by grahammendick** [comment]
Yea, it's the segmented control

**Comment by salisuabubakar** [comment]
I saw this and wanted to share. Is it the same ? When i change it non primary the segmented controls is on top of the navigationbar.
<img width="642" alt="Anatomy-2" src="https://github.com/grahammendick/navigation/assets/6886556/151906bd-ffb9-45f3-b2ab-126a585549d9">

**Comment by grahammendick** [comment]
Yea, it's the same. You need to wrap it in a `SafeAreaView` like in [the notifications scene of the twitter sample](https://github.com/grahammendick/navigation/blob/b332c63d778e72b909da105eeebe3698aaa02ddf/NavigationReactNative/sample/twitter/Notifications.js#L12)

**Comment by salisuabubakar** [comment]
Yeah its cool. Just tried it. Thanks
