### ISSUE TITLE
Flatlist without scrollview for large title to scroll

### ISSUE THREAD

**Issue by salisuabubakar** [grahammendick/navigation#732]
Hi, is there a way to use only flatlist without using scrollview in a component. I want to large title and when i scroll the large title stays sticky but i want it to scroll. When i use scrollview and and add fatlist inside scrollview it works perfect but react native give me error :

****
 ERROR  VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead.
****

Thank you

**Comment by grahammendick** [comment]
Yea, you can use a `FlatList` with a `ScrollView`. Set the `contentInsetAdjustmentBehavior` prop to 'automatic' on the `FlatList` then the large title will work

**Comment by grahammendick** [comment]
Sorry, I had a typo above. I've edited it out now (but, yea, you can use a FlatList without a ScrollView
