### ISSUE TITLE
Login from Tab to another Tab

### ISSUE THREAD

**Issue by salisuabubakar** [grahammendick/navigation#735]
Hi, i have two tabs namely loggedintab.js and loggedouttab.js In one of the scenes in loggedouttab.js  i have a login form and if the form is successful, i want to navigate to the loggedintab.js. I tried using stateNavigator.navigate("loggedintab") but i get an error :

++++
loggedintab is not a valid state.
++++
 Is there anyway i can do that. I also see this error in my xcode log:

++++
Require cycle: app/screen/LoggedInTab.js -> app/screen/LoggedOutTab.js -> app/screen/LoggedInTab.js
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
++++

Thanks

**Comment by grahammendick** [comment]
You asked me before how to [switch tabs](https://github.com/grahammendick/navigation/discussions/725).

```jsx
const [tab, setTab] = useState(0);
<TabBar tab={tab} onChangeTab={setTab}>
```
Then you can call `setTab(1)`, for example, to change tabs programmatically.

**Comment by salisuabubakar** [comment]
Hi, thanks for your response. I have used the example above already and its working but here am talking about group of scenes that tabbed. i used react context and its working fine. Thank

**Comment by salisuabubakar** [comment]
React Context  worked so am closing it. Thanks
