### ISSUE TITLE
BackTitle not aligned properly when screen is push

### ISSUE THREAD

**Issue by salisuabubakar** [grahammendick/navigation#737]
Hi, the backtitle on iOS does not align properly when you push a screen from A which does not have a NavigationBar to screen B which has a navigationBar with the backtitle added to the navigationBar.  Below is sample image :
![unnamed (1)](https://github.com/grahammendick/navigation/assets/6886556/c503ddde-252a-4b1c-98f4-3db261bdf1f1)

**Comment by grahammendick** [comment]
I tried it in the twitter sample and it aligns properly. I set the `NavigationBar` to `hidden` on the 'home' scene and added a `backTitle` to the 'tweet' scene. 

https://github.com/grahammendick/navigation/assets/1761227/f8880ec9-b114-449d-bfde-0fdc2c2643d5

**Comment by grahammendick** [comment]
But there's also no need to set a `backTitle`. On your first scene set a title and then the back button on the pushed scene with use it
```jsx
<NavigationBar title="Service" hidden />
````

**Comment by salisuabubakar** [comment]
Its working. Thanks
