### ISSUE TITLE
HidesTabBar not working on Android

### ISSUE THREAD

**Issue by mHvNG** [grahammendick/navigation#741]
Just as the title says, the `hidesTabBar` property works for iOS, but not for Android. Is this by design or a bug?

**Comment by grahammendick** [comment]
The Navigation router is 100% native. It doesn't implement UI logic at all. It only wraps the underlying native apis. The `hidesTabBar` prop wraps the [native hidesBottomBarWhenPushed on iOS](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621863-hidesbottombarwhenpushed?language=objc). But there is no equivalent native api on Android.

**Comment by mHvNG** [comment]
Alright, I would suggest mentioning this is an iOS-only feature. As there's no mention of it now.

**Comment by grahammendick** [comment]
That's fair comment, thanks 👍

**Comment by grahammendick** [comment]
I've added [a platform qualifier to each prop/component](https://github.com/grahammendick/navigation/compare/master...issue-741) that is specific to either Android or iOS. Does this work for you?

**Comment by grahammendick** [comment]
@mHvNG will you get a chance to look through my changes ☝️ ?

**Comment by grahammendick** [comment]
@mHvNG If I don't hear back from you in the next couple of weeks I'll close this (and your other issues). If you're too busy, don't worry, we can always reopen them when you're free

**Comment by grahammendick** [comment]
@mHvNG Closing this down because you're unavailable. Can always reopen when you're free

**Comment by mHvNG** [comment]
Hi, I've been unavailable, because of sickness and my graduation. So I've been offline from GitHub and programming. The comments seem fine. This way we can use intellisense for this instead of trying if it works, so thanks!

**Comment by grahammendick** [comment]
Hey, congrats on your graduation. Thanks, I've reopened

**Comment by grahammendick** [comment]
@mHvNG I've had an idea for how `hidesTabBar` could work on Android. If you're interested let me know

**Comment by grahammendick** [comment]
I [sketched out the idea](https://github.com/grahammendick/navigation/discussions/765#discussioncomment-8267764). It's not quite the same as ios because can't have A -> B -> C with tab bar on A and C but not B. Once the tab bar is hidden on B it stays hidden for navigations from B
