### ISSUE TITLE
Change BarButton Color

### ISSUE THREAD

**Issue by salisuabubakar** [grahammendick/navigation#742]
Hi, on iOs when i change the tincolor it changes the back button and the BarButton colors, is it possible to change the BarBotton colors only ? Thanks

**Comment by grahammendick** [comment]
Hi, it's currently not possible. We could add a `tintColor` prop to the `BarButton` that takes precedence over the `tintColor` of the `NavigationBar`?

**Comment by salisuabubakar** [comment]
Yes i think that will be wonderfull.

**Comment by grahammendick** [comment]
Just released this in navigation-react-native v9.11.0. [I thanked you in the release notes](https://github.com/grahammendick/navigation/releases/tag/v9.11.0-NavigationReactNative)
