### ISSUE TITLE
change the bottomTab border

### ISSUE THREAD

**Issue by see2ever** [grahammendick/navigation#746]
currently, the TabBar with {"primary": true} can't modify the border appearance, and there's no way to hide it also, which i can add an absolute line view to imitate one

**Comment by grahammendick** [comment]
Hey, great to hear from you. Are you talking about iOS or Android or both?

**Comment by grahammendick** [comment]
Ok, thanks. A bit of background. The Navigation router is 100% native on both Android and iOS. There's no UI code in React at all. Instead everything renders to the underlying native primitive. For example, the `TabBar` component renders to the [UITabBarController on iOS](https://developer.apple.com/documentation/uikit/uitabbarcontroller?language=objc) and [BottomNavigationView on Android](https://developer.android.com/reference/com/google/android/material/bottomnavigation/BottomNavigationView).

So first we have to work out how to modify the border appearance if we were building a native app without React Native. Once we know how to modify the border appearance of the `UITabBarController`, for example, then we'll try and wrap this underlying native behavior behind a `TabBar` prop.

Do you know how to natively modify the border appearance? If not, I'll do some investigation.

**Comment by see2ever** [comment]
sorry, actually I'm totally newbie for native develop, don't know how to modify them, but I saw the api in React-Native-Navigation.

Just suffer memory leak from React-Navigation, and I decide to migrate to Navigation-React-Native.

if you could add this api, may be add a children props to it will be best, so we can add any View component to it.

thank you for your work!

**Comment by grahammendick** [comment]
No problem. Could you explain exactly what you're trying to do, please? If I have the full picture of what you want your tabs to look like it would help me to understand the problem.

Because the Navigation router is 100% native, it can only support what the underlying native platform supports. For example, the `UITabBarController` doesn't support custom views.

**Comment by grahammendick** [comment]
Thanks. That's from iOS, right?

**Comment by see2ever** [comment]
> Thanks. That's from iOS, right?

yes, it is. but I don't see any props in TS, so it has not supported in android yet too

**Comment by grahammendick** [comment]
Fixed by #753

**Comment by grahammendick** [comment]
@see2ever I just released navigation-react-native v9.9.0 and [thanked you in the release notes](https://github.com/grahammendick/navigation/releases/tag/v9.9.0-NavigationReactNative)
