### ISSUE TITLE
yoga/style/Style.h' file not found

### ISSUE THREAD

**Issue by salisuabubakar** [grahammendick/navigation#759]
Hi @grahammendick , i saw you poste this on react native webview :

  if ENV['RCT_NEW_ARCH_ENABLED'] == '1' then
    install_modules_dependencies(spec)
  end

Am having similar issue with react native 0.73 and the navigation router 9.11.0. I havre tried it and it didnt work. Not sure if am doing the right thing. I edited the react-native-webview.podspec file. Is it the right place ?

Thanks

**Comment by grahammendick** [comment]
Hi, I've updated the [zoom sample to react native 0.73](https://github.com/grahammendick/navigation/tree/master/NavigationReactNative/sample/fabric). There's nothing you need to edit, I've already updated the Navigation router podspec.

You're probably having a problem with a different one of your dependencies.

**Comment by grahammendick** [comment]
If you're using Fabric, in order to upgrade to react native 0.73 all of your dependencies need to be ready for react native 0.73. The Navigation router is ready but are your other dependencies?

**Comment by grahammendick** [comment]
Oh I see. You're editing the react-native-webview.podspec - I missed that bit. Yea, you can try that and it should work. It worked on the Navigation router, but I never tried it in react-native-webview. I just suggested it because that's the correct fix

**Comment by salisuabubakar** [comment]
OK this is what am doing in react-native-webview.podspec : 

  if ENV['RCT_NEW_ARCH_ENABLED'] == '1' then
    s.compiler_flags = folly_compiler_flags + " -DRCT_NEW_ARCH_ENABLED=1"
    s.pod_target_xcconfig    = {
        # "HEADER_SEARCH_PATHS" => "\"$(PODS_ROOT)/boost\"",
        # "OTHER_CPLUSPLUSFLAGS" => "-DFOLLY_NO_CONFIG -DFOLLY_MOBILE=1 -DFOLLY_USE_LIBCPP=1",
        # "CLANG_CXX_LANGUAGE_STANDARD" => "c++17"
        install_modules_dependencies(spec)
    }

**Comment by grahammendick** [comment]
Replace `spec` with `s` and get rid of the other stuff
```ruby
if ENV['RCT_NEW_ARCH_ENABLED'] == '1' then
  install_modules_dependencies(s)
end
```

**Comment by grahammendick** [comment]
@salisuabubakar please let me know if it works

**Comment by grahammendick** [comment]
I'm gonna assume this worked because you haven't got back to me

**Comment by salisuabubakar** [comment]
It didnt work. Sorry for the late response.

**Comment by grahammendick** [comment]
Ok, you should raise this on the react-native-webview repo

**Comment by grahammendick** [comment]
Maybe you should give react-native-webview time to make a version that works with 0.73. I'm sure it's on their radar

**Comment by salisuabubakar** [comment]
Its unfortunate. Android is working perfectly but ios is the issue. Thanks

**Comment by grahammendick** [comment]
There's a [react-native-webview PR that you can try](https://github.com/react-native-webview/react-native-webview/pull/3231)
