### ISSUE TITLE
My App craches when i navigate back from react native webview screen

### ISSUE THREAD

**Issue by salisuabubakar** [grahammendick/navigation#763]
Hi,
Below is the error i get when i navigate back from react native webview screen on my app.
""""
NSInvalidArgumentException: -[RNCWebViewImpl destroyWebView]: unrecognized selector sent to instance 0x10b1e9a00
""""

Thank you.

**Comment by grahammendick** [comment]
This looks like a bug with React Native Webview to me. [Somebody else has raised it with them](https://github.com/react-native-webview/react-native-webview/issues/3043)

**Comment by grahammendick** [comment]
It looks like you've [not got fabric enabled on react native webview](https://github.com/react-native-webview/react-native-webview/blob/6960a1903c3c32e1e77be11e6370f1c384ed7ee4/apple/RNCWebViewImpl.m#L561C8-L561C28)?
