### ISSUE TITLE
How to celar trackCrumbTrail before navigating to a previous scene

### ISSUE THREAD

**Issue by salisuabubakar** [grahammendick/navigation#768]
Hello, Thanks for your time. I have an app with four tabs. Each tab has multiple scenes to navigate to. When i navigate to a scene on a first tab and then leave that scene and click on the second that how can i clear the scene i navigated to from the first tab to the tab scene itself? Am not sure if it is clear. 

Basically i have an app that users have to login before they book an appointment. After you book appointment you navigate back to the homeTab.js which containers the form to book the appointment. When i navigate to the bookappointment.js and without submitting the appointment form and then i press on  logout button which is on another tab and after logout i used prop function to navigate to the homeTab.js but then i see the bookappointment.js form. How can i clear the book appointment form so that users who have logged out will not see the book bookappointment form but rather go straight to the homeTab.js.

Hopefully you understand my questions. 

Thanks

**Comment by grahammendick** [comment]
You can register 2 different lists of scenes. One list for when the user is logged in and the other for when they're logged out. Then if the user logs out when they're on the 'appointment' scene, the Navigation router will navigate them to the first scene of the logged out stack (the home scene in this example).
```jsx
<TabBar>
  <TabBarItem>
    <NavigationHandler stateNavigator={homeNavigator}>
      <NavigationStack>
        {loggedIn ? 
          <>
            <Scene stateKey="home"><Home /></Scene>
            <Scene stateKey="appointment"><Appointment /></Scene>
          </>
          : 
          <>
            <Scene stateKey="home"><Home /></Scene>
          </>}
      </NavigationStack>
    </NavigationHandler>
  </TabBarItem>
```

**Comment by salisuabubakar** [comment]
Hi,Below is an example video. 

https://github.com/grahammendick/navigation/assets/6886556/9bcbb79d-b12a-4f28-9b94-8ae9450a258d

**Comment by grahammendick** [comment]
Thanks for the vid. The [answer I gave](https://github.com/grahammendick/navigation/issues/768#issuecomment-1939566912) will work for that

**Comment by salisuabubakar** [comment]
> Thanks for the vid. The [answer I gave](https://github.com/grahammendick/navigation/issues/768#issuecomment-1939566912) will work for that

I can confirm its working perfect. Thanks soo much for this wonderfull library.
