### ISSUE TITLE
Animation API examples 

### ISSUE THREAD

**Issue by afkcodes** [grahammendick/navigation#773]
Hey Hi Played around the animations changes that has been added, i am not good with animations so, would you please help me , or if you can update the medly example to have different sorts of route animations

Also if you can help me suggesting the animation config for this ?

https://whatpwacando.today/view-transitions

Please check the scale one in this on mobile. Thank you for all the hardwork,

**Comment by afkcodes** [comment]
Hey, Sorry probably i was not able to make the question clear. I was asking about, if we can get the similar scale transition as that of the pwa with react native. not the web.

**Comment by grahammendick** [comment]
Yea, here's something similar to the scale transition
```jsx
<NavigationStack
  crumbStyle={{type: 'scale', startX: 1.2, startY: 1.2}}
  unmountStyle={{type: 'scale', startX: 0.8, startY: 0.8}}>
```

**Comment by afkcodes** [comment]
Thanks will try this out. you are awsome

**Comment by grahammendick** [comment]
Thanks. Let me know if you have any trouble
