### ISSUE TITLE
How to get the height of bottom nav bar?

### ISSUE THREAD

**Issue by afkcodes** [grahammendick/navigation#776]
Hi, @grahammendick   i want to place something on top of bottom nav bar but for that i need to know the height of the bottom nav bar. is there any way to get the same ?

**Comment by grahammendick** [comment]
Do you mean the tab bar? It's a [fixed height so you can hard code it](https://github.com/grahammendick/navigation/blob/2a37da88def53d431696a1fed153a5ba51ee5072/NavigationReactNative/src/TabBar.tsx#L55). But you'll notice the height is different depending on the platform and whether you're using material 3, for example. You can also get these values from the Android/iOS specs - that's where I got them from.
