### ISSUE TITLE
Expo with The Navigation Router

### ISSUE THREAD

**Issue by salisuabubakar** [grahammendick/navigation#792]
Hi, is it possible to use Expo with the Nativation Router. Thanks

**Comment by grahammendick** [comment]
Yea, you can use the Navigation router and Expo. Expo doesn't restrict the packages you use anymore

**Comment by grahammendick** [comment]
I haven't used Expo but I think [it's development builds](https://docs.expo.dev/workflow/overview/#development-builds) that you want

**Comment by RichardLindhout** [comment]
I use expo and I can confirm it works :)

**Comment by salisuabubakar** [comment]
Yeah i can confirm it works perfectly. Thanks
