### ISSUE TITLE
Android crash error NoSuchMethodError   com.navigation.reactnative.ToolbarView in setTintColor

### ISSUE THREAD

**Issue by salisuabubakar** [grahammendick/navigation#799]
Hi, am having this error on android and the app crashes automatically after launch. Below is the sentry screenshot crash report. Thanks

![image](https://github.com/user-attachments/assets/7a960b28-0388-4a04-99cd-370b808c879b)

![image](https://github.com/user-attachments/assets/953894a8-f370-4c60-a431-2bc015864275)

**Comment by grahammendick** [comment]
Thank you for reporting 🙏 
I've just released [navigation-react-native v9.21.2 and thanked you in the release notes](https://github.com/grahammendick/navigation/releases/tag/v9.21.2-NavigationReactNative)

**Comment by salisuabubakar** [comment]
I can confirm its working perfectly. Thanks
