### ISSUE TITLE
Shared Element Transitions for iOS?

### ISSUE THREAD

**Issue by gerzonc** [grahammendick/navigation#809]
Hi, hope you're doing well.
Is there any chance we can get shared element transitions for iOS? Currently Apple [added](https://developer.apple.com/videos/play/wwdc2024/10145/) a transition API for iOS 18 that handles this, but I believe it is still possible to do it using custom transitions (see [here](https://medium.com/@tungfam/custom-uiviewcontroller-transitions-in-swift-d1677e5aa0bf)) for previous iOS versions.

**Comment by grahammendick** [comment]
Hey! Yea, I'm very excited to get shared element transitions for iOS using the new iOS 18 API as soon as possible! 

I'm less interested in adding it for previous iOS versions because the Navigation router only wraps native platform functionality. But what would interest me is to expose the necessary extension points that would enable a 3rd party package to add shared elements transitions to the Navigation router for iOS < 18. For example, the Navigation router could fire transition events so that a 3rd party could animate elements alongside the transition. This isn't something I plan on working on any time soon though.

I'm pretty busy at the moment working on [shared element transitions for the web](https://github.com/grahammendick/navigation/compare/sharedel-animation). I'm moving them over to the [Web Animations API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API). The idea is to have the same shared elements API working across Android, iOS and Web using the native primitives on all 3 platforms under the hood.

Would you be interested in integrating the new iOS 18 shared elements transitions into the Navigation router?

**Comment by gerzonc** [comment]
Hey, thanks for reaching out!

> I'm less interested in adding it for previous iOS versions because the Navigation router only wraps native platform functionality.
I think it would be possible, but currently the codebase is written with Objective-C, which doesn't have an API for it. On the other hand, SwiftUI has the `.matchedGeometryEffect()` (see [here](https://developer.apple.com/documentation/swiftui/view/matchedgeometryeffect(id:in:properties:anchor:issource:)) that does handle it pretty well. 

> I'm pretty busy at the moment working on [shared element transitions for the web](https://github.com/grahammendick/navigation/compare/sharedel-animation). I'm moving them over to the [Web Animations API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API). The idea is to have the same shared elements API working across Android, iOS and Web using the native primitives on all 3 platforms under the hood.

This indeed looks interesting. I might need to take some time to read on how it's done on Android so we can implement the iOS 18's SET accordingly. If you're also interested on the `matchedGeometryEffect`, let me know and we will see how we can make both work together.

**Comment by grahammendick** [comment]
Hey, It's great to hear from you again!

I'd only look into iOS < 18 if somebody came along with a SET implementation written natively that they wanted to hook up to the Navigation router.

For now, let's concentrate on wrapping the native SET that's landed in iOS 18. I'll give you some background on how the SET works in Android. The Navigation router is 100% native so pretty much all the code I'll talk about below is Java code (there's almost no JavaScript code involved). I've used `` to single out the Navigation router code. For example, the `NavigationStackView` is from the Navigation router and FragmentManager is from Android.

The Navigation router uses the native FragmentManager stack provided by Android. When a user navigates from A → B the `NavigationStackView` starts a FragmentTransaction. It sets up A's exit transition, B's entry transition, adds any shared elements and finally replaces scene B with scene A. When the Navigation router commits the transaction Android takes care of running all these animations together.

So how does the `NavigationStackView` know what shared elements to add? Each `SharedElementView` adds itself to the 'sharedElements' property of its root scene A (by traversing the view hierarchy until it reaches the root `SceneView`). The `NavigationStackView` can then read this 'sharedElements' collection and add them to the FragmentTransaction.

But the `NavigationStackView` doesn't add every shared element. The user-supplied 'sharedElements' prop on the `NavigationStackView` says which ones to add. For example, every picture in a gallery is a shared element but it's only the one that's tapped that should take part in the transition.

The Navigation router anticipates that It might take a few renders for the matching `SharedElement(s)` in scene B to appear. So scene B (`SceneFragment`) postpones its entry to wait for them all to draw. Once the coordinator (`SharedElementMotion`) has received notification that each shared element is ready then it starts the postponed transition.

I hope this helps you out. I'm always happy to answer any questions and chat over this with you whenever you want.

**Comment by grahammendick** [comment]
Hi @gerzonc how you getting along with this? Want to chat over anything?

**Comment by gerzonc** [comment]
> Hi @gerzonc how you getting along with this? Want to chat over anything?

Hi man, hope you're doing well. Currently I paused my progress due to some releases at work, and the migration of my app to native SwiftUI last month. I will be free from this friday till the end of the month, so I'll be actively working on this, probably even better since now I have some experience using the Hero library and the fluent transitions!

**Comment by grahammendick** [comment]
Hi @gerzonc, I guessed you were busy with other things so I got cracking with shared elements on iOS 18. Please [try them out in navigation react native v9.27.0](https://github.com/grahammendick/navigation/releases/tag/v9.27.0-NavigationReactNative) and let me know what you think
