### ISSUE TITLE
iOS: Nav Bar Title not updated when changing Accessibility Font Size

### ISSUE THREAD

**Issue by danilobuerger** [grahammendick/navigation#817]
```
import React from "react";
import { CoordinatorLayout, NavigationBar, TitleBar } from "navigation-react-native";
import { Text } from "react-native";

const HomeScene: React.FC = () => {
  return (
    <CoordinatorLayout>
      <NavigationBar>
        <TitleBar>
          <Text>Hello World qq</Text>
        </TitleBar>
      </NavigationBar>
    </CoordinatorLayout>
  );
};

export default HomeScene;
```

https://github.com/user-attachments/assets/17228c00-bed1-455c-896a-4617a6a59774

Only after reloading, the text is not cut off

**Comment by grahammendick** [comment]
Hi, thanks for getting in touch and for the clear issue description. Would you be interested in working on a PR to fix this? My initial thoughts are you'd subscribe to [the UIContentSizeCategoryDidChangeNotification](https://developer.apple.com/documentation/uikit/uicontentsizecategorydidchangenotification?language=objc) and then update the [title size on the old](https://github.com/grahammendick/navigation/blob/828458530e7ab809b8753519f09e240c30ed0234/NavigationReactNative/src/ios/NVTitleBarView.m#L35) and [new arch](https://github.com/grahammendick/navigation/blob/828458530e7ab809b8753519f09e240c30ed0234/NavigationReactNative/src/ios/NVTitleBarComponentView.mm#L49).

**Comment by danilobuerger** [comment]
I don't think your proposed solution is a good idea. Its just another hack on top of the hack from https://github.com/grahammendick/navigation/pull/516 . Setting the size there is whats leading to this issues. Reverting the mentioned PR, fixes this issue.

**Comment by grahammendick** [comment]
If you just want to change the title text then don't use the `TitleBar` component. You should use the title prop instead. This will resize correctly when the user changes the accessiblity font size.
```jsx
<NavigationBar title="Hello World" />
```
The `TitleBar` component is for when you want custom UI in place of the title, for example, the zoom sample [shows the selected color](https://github.com/grahammendick/navigation/blob/828458530e7ab809b8753519f09e240c30ed0234/NavigationReactNative/sample/zoom/Detail.js#L13). The Navigation router has to get the correct size of the title bar so that the custom UI is sized correctly by React Native.

**Comment by danilobuerger** [comment]
Yes, I know, but I wanted to make an easy and concise and example for the bug report. I am using it for a custom UI and not only a custom title.

**Comment by danilobuerger** [comment]
Have you tested that code snippet? For me it displays nothing.

**Comment by grahammendick** [comment]
How about something like this?
```jsx
<NavigationBar>
  <TitleBar style={{flex: 1, flexDirection: 'row'}}>
    <View style={{flex: 1, backgroundColor: 'red', height: 10}}>
  </View>
  </TitleBar>
</NavigationBar>

**Comment by grahammendick** [comment]
Although I'm not sure it's working quite right (I only checked iOS on old arch just now). Looks like the `TitleBarView` reports height 0 to React Native so can't flex it to be full height. I wonder if it needs some auto resizing mask to make it take up the available space?

**Comment by grahammendick** [comment]
Something that seems to work is to use the height of `navigationBar` and the width of the `titleView` [in the TitleBarView](https://github.com/grahammendick/navigation/blob/28c92f9c6f55d0f8f85da5fe83a7d9e0aa83a83f/NavigationReactNative/src/ios/NVTitleBarView.m#L32)
```obj-c
- (void)layoutSubviews {
    [super layoutSubviews];
    CGRect rect = self.reactViewController.navigationController.navigationBar.frame;
    rect = CGRectMake(0, 0, self.frame.size.width, rect.size.height);
    if (!CGRectEqualToRect(_lastViewFrame, rect)) {
        [_bridge.uiManager setSize:rect.size forView:self];
        _lastViewFrame = rect;
    }
}
```

```jsx
<TitleBar>
    <View style={{width: 150, flex: 1, backgroundColor: 'lightblue', borderColor: 'orange', borderWidth: 5}}/>
</TitleBar>
```

![image](https://github.com/user-attachments/assets/80176df0-b5e1-4e74-8c4e-edace9d7ebd0)

**Comment by grahammendick** [comment]
Ok, new idea. The `TitleBar` listerns for the `UIContentSizeCategoryDidChangeNotification` and updates its React key to force a remount

**Comment by grahammendick** [comment]
Simpler way, can probably set the key to be [the fontScale](https://reactnative.dev/docs/usewindowdimensions#fontscale)
```jsx
const fontScale = useWindowDimensions().fontScale;
<NVTitleBar key={fontScale}>
```

**Comment by grahammendick** [comment]
Ha, yea, it works!

https://github.com/user-attachments/assets/e441f48b-d770-42f6-853f-100af111c92a

**Comment by grahammendick** [comment]
I think it's better to leave this out of the Navigation router because the custom view might have state. My suggestion is you use this workaround in your home scene. This fix also works if you want to dynamically change the custom view

```jsx
const HomeScene = () => {
  const {fontScale} = useWindowDimensions();
  return (
    <CoordinatorLayout>
      <NavigationBar>
        <TitleBar key={fontScale}>
          <Text>Hello World</Text>
        </TitleBar>
      </NavigationBar>
    </CoordinatorLayout>
  );
};
```
