### ISSUE TITLE
Custom TypeConverter

### ISSUE THREAD

**Issue by danilobuerger** [grahammendick/navigation#818]
As a follow up to https://github.com/grahammendick/navigation/issues/108

Use Case: When using navigation for react native only, I don't see a need to care about "pretty urls". However, when pushing a lot of state around, it becomes cumbersome to having to flatten the whole state.

Proposed Solutions:
1. Allow for custom TypeConverters
2. Add a default object TypeConverter (sorting f.x. alphabetically for deterministic results)

**Comment by grahammendick** [comment]
Hi @danilobuerger thanks for the suggestion. Please can you give me examples of the kinds of things you're passing around. Please give as many examples as you can because the more context you provide the better I can understand your request.

**Comment by danilobuerger** [comment]
For example an app that collects data on each screen before registration. Now you have to pass each along individually:
```
{ name, gender, dob, ...}
```
instead of just collecting it in an object.

**Comment by grahammendick** [comment]
Wouldn't this work for that scenario?
```jsx
// on the 'name' scene
stateNavigator.navigate('gender', { name });

// on the 'gender' scene
const {data} = useContext(NavigationContext);
stateNavigator.navigate('dob', {...data, gender});

// on the 'dob' scene
const {data} = useContext(NavigationContext);
stateNavigator.navigate('next', {...data, dob});

```

**Comment by danilobuerger** [comment]
And now on the same Scene I want to capture a dogs name and race:
```
{ ...data, dogName, dogRace }
```
instead of being able to do
```
{ ...data, dog }
```
I know everything is already possible with the current type converters. I just think it makes for a bad dev ux not being able to group things.

**Comment by grahammendick** [comment]
You can do `{ ...data, ...dog }`. But do you mean the destructuring back into data and dog on the next scene is tricky without grouping?

**Comment by danilobuerger** [comment]
If I had `dog = { name, race }` I cant do `{ ...data, ...dog }` as that would override the existing `name` from the name scene.

**Comment by grahammendick** [comment]
Yea, gotcha. Do you prefer to pass all this data through navigation rather than using React context or a 3rd party state library?

**Comment by danilobuerger** [comment]
I do.

**Comment by grahammendick** [comment]
Please tell me why. The more information you give me the easier it is for me to think about the issue

**Comment by danilobuerger** [comment]
Because I don't want to integrate a 3rd party library when I don't have to. And for context vs prop drilling: no magic, explicit and easier testing.

**Comment by grahammendick** [comment]
Did you know you could use React state like this with the Navigation router?
```jsx
const Stack = () => {
  const [data, setData] = useState({})
  return (
    <NavigationStack>
      <Scene stateKey="name" setData={setData}><Name /></Scene>
      <Scene stateKey="gender" setData={setData}><Gender /></Scene>
      <Scene stateKey="dob" setData={setData}><Dob /></Scene>
    </NavigationStack>
  )
};

// on the 'name' scene
setData(data => ({...data, name, dog}));
stateNavigator.navigate('gender');
```

**Comment by danilobuerger** [comment]
Again, not what I want to do. Its fine if you don't agree. I am just saying it makes for a bad dev experience not being able to use objects. Allowing for custom type converters, anything could be serialized.

**Comment by grahammendick** [comment]
I'm not agreeing or disagreeing. I'm just trying to understand what you're requesting. Like I say, the more information you give me the better. So please explain why the [useState pattern](https://github.com/grahammendick/navigation/issues/818#issuecomment-2395431981) isn't suitable for what you're trying to do. Give as much detail as possible. For example, you could show me how you test and explain why that approach doesn't fit with the useState pattern. Or, if you're saying the useState pattern is 'magic', please expand on what you mean.

**Comment by danilobuerger** [comment]
The thing is, I don't want to have to explain why I don't do thing x, y or z. I just want to code the way I want to code. I feel like a big library like yours, thats going to be integrated heavily into apps, should allow for escape hatches and not force a dev to do things exactly the way you want. I have used and contributed a lot to `wix/react-native-navigation` for a couple of years now and always wanted to try out your library. It feels good so far but I don't want to be forced into a corner. It should just work. And using objects in data feels like a trivial thing to have. I never had to change my style of coding while using rnn. Just some food for thought.

**Comment by grahammendick** [comment]
> I don't want to have to explain why I don't do thing x, y or z.

Ok, that’s a shame. I’m going to have to close this. If you change your mind I’m very happy to reopen this.

**Comment by danilobuerger** [comment]
So I guess no food for thought. This is why I was always skeptical about your library. Just you working on it, really no other major contributors. Now I was here, having an idea, willing to implement it. Could it be you are unwilling to compromise? Its fair if you are, just good to know. Is this the reason why you haven't been able to foster a contributor community around this library?

**Comment by danilobuerger** [comment]
For anybody else looking for a Object TypeConverter (https://github.com/grahammendick/navigation/issues/108), you can use [patch-package](https://github.com/ds300/patch-package) and the following patch:

```
diff --git a/node_modules/navigation/navigation.js b/node_modules/navigation/navigation.js
index d68f0e4..555dda1 100644
--- a/node_modules/navigation/navigation.js
+++ b/node_modules/navigation/navigation.js
@@ -405,13 +405,31 @@ var StringConverter = /** @class */ (function (_super) {
     return StringConverter;
 }(TypeConverter));
 
+const stringify = require('json-stable-stringify');
+var ObjectConverter = /** @class */ (function (_super) {
+    __extends(ObjectConverter, _super);
+    function ObjectConverter(key) {
+        return _super.call(this, key, 'object') || this;
+    }
+    ObjectConverter.prototype.convertFrom = function (val) {
+        if (typeof val !== 'string')
+            throw new Error(val + ' is not a valid object');
+        return JSON.parse(val);
+    };
+    ObjectConverter.prototype.convertTo = function (val) {
+        return { val: stringify(val) };
+    };
+    return ObjectConverter;
+}(TypeConverter));
+
 var ConverterFactory = /** @class */ (function () {
     function ConverterFactory() {
         this.keyToConverterList = {};
         this.nameToConverterList = {};
         var converterArray = [
             new StringConverter('0'), new BooleanConverter('1'),
-            new NumberConverter('2'), new DateConverter('3')
+            new NumberConverter('2'), new DateConverter('3'),
+            new ObjectConverter('4')
         ];
         for (var i = 0; i < converterArray.length; i++) {
             var converter = converterArray[i];
```

It uses `json-stable-stringify` (already included via patch-package, but you can add it to your package.json just to be sure) to generate a deterministic object representation.
