### ISSUE TITLE
Date TypeConverter looses time portion

### ISSUE THREAD

**Issue by danilobuerger** [grahammendick/navigation#819]
The `DateConverter` drops the time portion of the date. When using react-native this leads to hard to debug issues as its not directly visible in a url. When passing a date, I would expect to get the same date by value back in the scene that was navigated to.

**Comment by danilobuerger** [comment]
What has the one thing to do with the other?

**Comment by grahammendick** [comment]
Requests like this involve discussions about what you're trying to do which you've already told me you aren't up for

**Comment by danilobuerger** [comment]
Only in that specific issue as it was going nowhere. Here we can try again. For me this is clearly a bug as there is a DateConverter already, accepting a Date object but only saving half of it. This is nowhere documented (I think) and leads to hard to debug issues. In my opinion there should either be no DateConverter at all (same logic as for the non-existing ObjectConverter, it can be done without a DateConverter as you can just serialize the Date as a string) or it should support the whole Date and not half of it.

**Comment by danilobuerger** [comment]
* Why are you forcing somebody who uses navigation just with react-native to worry about how a hypothetical url would look like? Whats the benefit of that?
* Why is `2024-10-08` "pretty" and `2024-10-08T12:46:34Z` is not? I don't understand why you are imposing your view on what makes urls pretty on other devs? Why can't I decide that for myself?
* Allowing for custom TypeConverters would solve this problem totally. I don't understand why you would be against this. navigation would come with a standard set (your standard set) of TypeConverters and if somebody wants to do it differently they could just register their own TypeConverters. Where do you see the harm in allowing that?

**Comment by grahammendick** [comment]
If you're not bothered about Urls on native why not do away with TypeConverters completely? 

The Navigation router believes in universal apps. You build an app once and it runs on Android, iOS and Web using the underlying navigation primitives of all 3 platforms. The underlying navigation primitive of the Web is Urls. But there's little point in Urls if they're not pretty. 

The Navigation router definitely shouldn't dictate what makes a Url look nice or not. You've always got the option of converting the Date into a string if you want to include the time as well. 

I'm always happy to explore ways to improve how the Navigation router passes data. Can you give me examples where you'd want to pass a Date including the seconds and time zone to another screen?
