### ISSUE TITLE
I get this error when i try to run android using expo

### ISSUE THREAD

**Issue by salisuabubakar** [grahammendick/navigation#820]
HI,
i get the below error on my android emulator after i login to my app. Thanks

![Screenshot_1728594094](https://github.com/user-attachments/assets/8994dd08-132a-4ef6-84f3-a0b4b92c0804)

**Comment by grahammendick** [comment]
Hi, could you run it from Android Studio and send me the full stack trace, please?

**Comment by grahammendick** [comment]
Ok, thanks but that didn't give me any more info.

Could you find out what prop is causing the trouble, please? 
So remove props from your `NavigationBar` and `SearchBar` until you don't get the error anymore. 
For example, if your code looks like this
```jsx
<SearchBar
  toolbar
  text={text}
  autoCapitalize="none"
  obscureBackground={false}
  barTintColor="#dcdcdc"
  placeholder={(toolbar) => toolbar ? 'Search' : ''}
  onChangeText={text => setText(text)}>
```

Then remove the props one by one to see which it is that's causing the problem. 
```jsx
<SearchBar
  toolbar
  text={text}
  placeholder={(toolbar) => toolbar ? 'Search' : ''}
  onChangeText={text => setText(text)}>
```
If the `SearchBar` isn't what's causing the problem then try the same process with the `NavigationBar`.

**Comment by salisuabubakar** [comment]
Yeah i was doing this in the navigationBar   titleFontSize={(standard) => standard ? "17" :  "28"}  instead of  titleFontSize={(standard) => standard ? 17 :  28}.

Thanks soo much.
