### ISSUE TITLE
RightBar  BarButton Colors

### ISSUE THREAD

**Issue by salisuabubakar** [grahammendick/navigation#825]
Hi, Is there a way to change RightBar  BarButton Colors. Thanks

**Comment by grahammendick** [comment]
Hi, the `tintColor` prop of the `BarButton` or the `tintColor` prop of the `NavigationBar`

**Comment by salisuabubakar** [comment]
Yeah its working. Can we also have backgroundColor? Thanks

**Comment by grahammendick** [comment]
Yep, use the `barTint` prop on the `NavigationBar`

**Comment by salisuabubakar** [comment]
Background color for each of the BarButton. Thanks

**Comment by grahammendick** [comment]
Nope, there's no option for that natively so the Navigation router can't support it. The Navigation router only wraps the underlying native behaviour
