### ISSUE TITLE
Nitro Modules

### ISSUE THREAD

**Issue by salisuabubakar** [grahammendick/navigation#828]
Hi, is there a way you can use nitro modules to improve the navigation router performance. Thanks

**Comment by grahammendick** [comment]
Hi,
1. What's wrong with the Navigation router performance?!
2. There aren't any modules in the Navigation router so Nitro modules wouldn't do anything
3. The Navigation router won't take on any 3rd party dependencies

**Comment by salisuabubakar** [comment]
Hi Graham, The Navigation Router for me is the best abd the performance is matched with any of the navigation modules. I was just thinking if if could help in anyway. I can assure you my friends and i are enjoying it abd we are not looking back.

Thanks for your time.

**Comment by grahammendick** [comment]
Hi, Thanks for getting in touch. It's always nice to hear from you. I'm glad you all are enjoying the Navigation router 🙏
