### ISSUE TITLE
android app crashes when Sheet is set to modal and hideable is true

### ISSUE THREAD

**Issue by advancedtw** [grahammendick/navigation#831]
the app crashes when I try to swipe down to dismiss the sheet. I've tried many things such as using a scroll container  and a CoordinatorLayout , collapsable false ...

example of Sheet usge. 
I moved the CoordinatorLayout around to see if it made any difference I still get a hard crash

```tsx
export default function DetailScreen() {
  return (
    <CoordinatorLayout>
      <Screen>
        <DetailNav />
        <Sheet modal={true} hideable={true} expandedHeight={300}>
          <View
            style={{
              backgroundColor: "pink",
              flex: 1
            }}
          >
            <Text>test</Text>
          </View>
        </Sheet>
      </Screen>
    </CoordinatorLayout>
  );
}
```

```

I have a report about a nil object reference below.
I'm running on an emulator I think it's a pixel 8 with sdk 35 


 ERROR  Your app just crashed. See the error below.
java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.uimanager.events.EventDispatcher.dispatchEvent(com.facebook.react.uimanager.events.Event)' on a null object reference
 com.navigation.reactnative.BottomSheetDialogView$BottomSheetFragment$1.onStateChanged(BottomSheetDialogView.java:132)
  com.google.android.material.bottomsheet.BottomSheetBehavior.setStateInternal(BottomSheetBehavior.java:1431)
  com.google.android.material.bottomsheet.BottomSheetBehavior$5.onViewDragStateChanged(BottomSheetBehavior.java:1883)
  androidx.customview.widget.ViewDragHelper.setDragState(ViewDragHelper.java:920)
  androidx.customview.widget.ViewDragHelper.captureChildView(ViewDragHelper.java:508)
  androidx.customview.widget.ViewDragHelper.tryCaptureViewForDrag(ViewDragHelper.java:943)
  androidx.customview.widget.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1095)
  com.google.android.material.bottomsheet.BottomSheetBehavior.onInterceptTouchEvent(BottomSheetBehavior.java:664)
  androidx.coordinatorlayout.widget.CoordinatorLayout.performEvent(CoordinatorLayout.java:548)
  androidx.coordinatorlayout.widget.CoordinatorLayout.performIntercept(CoordinatorLayout.java:503)
  androidx.coordinatorlayout.widget.CoordinatorLayout.onInterceptTouchEvent(CoordinatorLayout.java:570)
  android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2656)
  android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
  android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
  android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
  android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
  android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
  android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
  android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
  android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
  android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
  android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
  android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
  android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
  com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:458)
  com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1980)
  android.app.Dialog.dispatchTouchEvent(Dialog.java:935)
  androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
  com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:416)
  android.view.View.dispatchPointerEvent(View.java:16729)
  android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7947)
  android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7710)
  android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7106)
  android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7163)
  android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7129)
  android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7295)
  android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7137)
  android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7352)
  android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7110)
  android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7163)
  android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7129)
  android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7137)
  android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7110)
  android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10214)
  android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10165)
  android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10134)
  android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10356)
  android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:295)
  android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
  android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:259)
  android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:10313)
  android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:10449)
  android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
  android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
  android.view.Choreographer.doCallbacks(Choreographer.java:1015)
  android.view.Choreographer.doFrame(Choreographer.java:938)
  android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
  android.os.Handler.handleCallback(Handler.java:959)
  android.os.Handler.dispatchMessage(Handler.java:100)
  android.os.Looper.loopOnce(Looper.java:232)
  android.os.Looper.loop(Looper.java:317)
  android.app.ActivityThread.main(ActivityThread.java:8705)
  java.lang.reflect.Method.invoke(Native Method)
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

```

**Comment by grahammendick** [comment]
Hi, great to hear from you again and thanks for a great bug report. 

It [should be dialogView.getId() instead of getId()](https://github.com/grahammendick/navigation/blob/a9e0707f20369e992d9a08db2631e7022bfa7c89/NavigationReactNative/src/android/src/main/java/com/navigation/reactnative/BottomSheetDialogView.java#L131) when the `BottomSheetFragment` gets the `eventDispatcher`. So it should be
```java
EventDispatcher eventDispatcher = UIManagerHelper.getEventDispatcherForReactTag(reactContext, dialogView.getId());
```

I'd always appreciate a PR but if you don't fancy it for whatever reason that's obviously cool. Let me know either way, please

**Comment by grahammendick** [comment]
@advancedtw Don't worry, I'll take this one

**Comment by grahammendick** [comment]
I just fixed this in navigation-react-native v9.22.4 and [thanked you in the release notes](https://github.com/grahammendick/navigation/releases/tag/v9.22.4-NavigationReactNative)

**Comment by advancedtw** [comment]
Thanks I planned to work on it today but you beat me to it.
Just tested on android and indeed I can now have a modal Sheet that is draggable/hideable. 

btw the animation of the Sheet on android is stock ? there is no spring effect like on ios ?
compared to ios the animation is a bit unpleasant. Looks like a linear progress with some opacity change and the speed is a bit too fast.

**Comment by grahammendick** [comment]
Yea, the Navigation router is 100% native so it doesn't ever add any custom animations. It always uses the native primitives provided by the platform, in this case [the BottomSheetDialogFragment](https://developer.android.com/reference/com/google/android/material/bottomsheet/BottomSheetDialogFragment)

**Comment by grahammendick** [comment]
Did you know the Navigation router [supports Android's predictive back gesture](https://developer.android.com/guide/navigation/custom-back/predictive-back-gesture)? If you turn it on the dialog will animate smoothly closed as you swipe back

**Comment by grahammendick** [comment]
>  I don't really see a big difference

The difference you should see is that the screen transition follows the swipe progress. Without predictive back the screen transition doesn't begin until the swipe finishes.

https://github.com/user-attachments/assets/c6407768-7587-43d3-9c2c-d49a11edd5c1

> is there a threshold in px to confirm the back nav when we have it activated?

The crumb and unmount style only configuration the transition. The thresholds are all determined by the native platform.

**Comment by advancedtw** [comment]
compared to what I see in your video my animation are janky.
what is happening is as a release my finger, the current screen translate first from it's current position to the left edge of the device and from there move horizontally to the right at a very high speed to finally disappear.
there must be something wrong with my setup.

**Comment by advancedtw** [comment]
yes I am using androidx.activity:activity:1.9.3 at least that is what is in my graadle dependencies. I'm not sure if it is being picked up or not but I did make a fresh build

**Comment by grahammendick** [comment]
Well predictive back is working in [the fabric sample](https://github.com/grahammendick/navigation/tree/master/NavigationReactNative/sample/fabric) if you want to compare

**Comment by advancedtw** [comment]
I was using the medly example to compare and it seems like there is only 2 changes to make one in the manifest and the other is the dependency list.
I think predictive back is working in my app because I have the peek effect and return to home effect it's just my slide animation is weird as described earlier. 
anyways I have the repo already cloned so I will run the fabric example and see if I can find the problem.

**Comment by advancedtw** [comment]
seems it is happening with  the fabric app too. The funny thing is when I recorded the video using the android built in tool and played in in slow motion I could not see it so I recorded using the screenshot tool and I think it is visible. 

https://github.com/user-attachments/assets/d38e172e-d51a-4f85-8094-a664f7faa8d6

**Comment by grahammendick** [comment]
The vid I took is using the screenshoot tool, not the android built in one, too. What simulator you using?

**Comment by advancedtw** [comment]
pixel 8 , android 15  sdk 35. I will create a new one to test.

**Comment by grahammendick** [comment]
Create one with sdk 34 because that's what I'm using

**Comment by advancedtw** [comment]
works great on android 14 sdk 34

**Comment by grahammendick** [comment]
I tried android 15 sdk 35 and I see what you're seeing

**Comment by grahammendick** [comment]
It's [an Android bug](https://issuetracker.google.com/u/0/issues/362452854)

**Comment by grahammendick** [comment]
@advancedtw On my physical Pixel 6a Android 15 there's no predictive back flicker. Maybe it's a simulator only problem? Can you test on a physical device to check, too, please?
