### ISSUE TITLE
React native EdgeToEdge on Android

### ISSUE THREAD

**Issue by salisuabubakar** [grahammendick/navigation#839]
How to get the edge to edge to work on android.

**Comment by grahammendick** [comment]
Hi, I've just started investigating edge-to-edge on Android. I've got quite a bit to read up on but it looks like some of the Navigation router components need adjusting to handle the insets. I'll keep this issue updated with my progress.

**Comment by grahammendick** [comment]
I'm learning a lot about Inset handling from this [edge-to-edge guide from Android](https://medium.com/androiddevelopers/insets-handling-tips-for-android-15s-edge-to-edge-enforcement-872774e8839b)

**Comment by grahammendick** [comment]
I've hatched a plan and started work on it. You can [follow along in the edge-edge branch](https://github.com/grahammendick/navigation/tree/edge-edge)

**Comment by grahammendick** [comment]
I released navigation-react-native v9.25.0 with edge-to-edge support. I [thanked you in the release notes](https://github.com/grahammendick/navigation/releases/tag/v9.25.0-NavigationReactNative).

To [enable edge-to-edge](https://developer.android.com/develop/ui/views/layout/edge-to-edge#enable-edge-to-edge-display) call [enableEdgeToEdge from within the MainActivity](https://developer.android.com/reference/androidx/activity/ComponentActivity#(androidx.activity.ComponentActivity).enableEdgeToEdge(androidx.activity.SystemBarStyle,androidx.activity.SystemBarStyle))

```kt
override fun onCreate(savedInstanceState: Bundle?) {
    enableEdgeToEdge();
    super.onCreate(savedInstanceState)
}
```

**Comment by salisuabubakar** [comment]
Thanks soo much for getting it done. Does it work with expo? Thanks

**Comment by grahammendick** [comment]
I didn't test on expo. Please let me know how you get on

**Comment by salisuabubakar** [comment]
I did this with expe:

class MainActivity : ReactActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    // Set the theme to AppTheme BEFORE onCreate to support
    // coloring the background, status bar, and navigation bar.
    // This is required for expo-splash-screen.
    // setTheme(R.style.AppTheme);
    // @generated begin expo-splashscreen - expo prebuild (DO NOT MODIFY) sync-f3ff59a738c56c9a6119210cb55f0b613eb8b6af
    SplashScreenManager.registerOnActivity(this)
    // @generated end expo-splashscreen
    enableEdgeToEdge();
    super.onCreate(savedInstanceState)
  }


I get this error: 
> Task :app:compileDebugKotlin FAILED
e: file:///Users/salisu/Desktop/KEYSTORE/AfriDial/android/app/src/main/java/com/afridial/MainActivity.kt:23:5 Unresolved reference: enableEdgeToEdge

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

**Comment by grahammendick** [comment]
You need to `import androidx.activity.enableEdgeToEdge` in `MainActivity`

**Comment by salisuabubakar** [comment]
i can confirm its working flawlessly. Am very gratefull.

**Comment by grahammendick** [comment]
Thank you ❤️  It was very tricky
