### ISSUE TITLE
Can i use useNavigated to fetch data

### ISSUE THREAD

**Issue by salisuabubakar** [grahammendick/navigation#840]
Hi, I would like to know if its ok to use useNavigated or other lifecycle methods to fetch data. Thanks

**Comment by grahammendick** [comment]
Hi, you're better off using the React approach to fetching data like `useEffect`

**Comment by salisuabubakar** [comment]
OK. Thanks for the switft response. Very greatful.

**Comment by grahammendick** [comment]
Oh, no problem 🙏  It's always nice to hear from you
