### ISSUE TITLE
Sheet on iOS when orientation changed does not take full screen on Landscape

### ISSUE THREAD

**Issue by salisuabubakar** [grahammendick/navigation#843]
Hi, am am using Sheet and the orientation change from Landscape to Portrait the Sheet does not take full screen untill i reload the app.

Below is my code:

`            <Sheet
              detent={detent}
              onChangeDetent={setDetent}
              hideable={false}
              bottom={false}
              modal={true}
              fullScreen
            >
              <View style={{ flex: 1 }}>
                <ScrollView
                  contentInsetAdjustmentBehavior="automatic"
                  showsHorizontalScrollIndicator={false}
                  showsVerticalScrollIndicator={false}
                  contentContainerStyle={{
                    flexGrow: 1,
                  }}
                  nestedScrollEnabled={false}
                  automaticallyAdjustKeyboardInsets={true}
                  bounces={true}
                  style={styles.modalwatchmovie}
                >
                  <VideoView
                    ref={videoRef}
                    style={{
                      width: Dimensions.get("window").width,
                      height: Dimensions.get("window").height - 20,
                    }}
                    player={player}
                    allowsFullscreen
                    allowsPictureInPicture
                    startsPictureInPictureAutomatically
                    contentFit="contain"
                    nativeControls={true}
                  />
                  <Pressable
                    style={{
                      backgroundColor: "rgba(52, 52, 52, 0.7)",
                      borderRadius: 8,
                      alignItems: "center",
                      justifyContent: "center",
                      position: "absolute",
                      top: 6,
                      left: 104,
                      width: 34,
                      height: 31,
                      shadowColor: "#000",
                      shadowOffset: { width: 0, height: 2 },
                      shadowOpacity: 0.8,
                      shadowRadius: 2,
                      elevation: 5,
                      zIndex: 1000,
                    }}
                    onPress={() => {
                      setDetent("hidden");
                    }}
                  >
                    <Ionicons name="close" size={20} color="#C2C2C2" />
                  </Pressable>
                </ScrollView>
              </View>
            </Sheet>`

**Comment by grahammendick** [comment]
I added the following code to the [Tweet scene of the fabric example](https://github.com/grahammendick/navigation/blob/master/NavigationReactNative/sample/fabric/Tweet.js) and it works for me (see vid). Can you try the same code in the fabric example and let me know if it works for you too, please?

```jsx
const [detent, setDetent] = useState('hidden');
useEffect(() => {
  setTimeout(() => {
    setDetent('expanded');
  }, 1000);
}, [])

<Sheet modal bottom={false} detent={detent} onChangeDetent={setDetent}>
  <ScrollView style={{flex: 1}}>
    <View style={{height: 1000, borderColor: 'orange', borderWidth: 5, backgroundColor: 'lightblue'}} />
  </ScrollView>
</Sheet>
```
https://github.com/user-attachments/assets/6adce456-cf58-458b-b463-fcb09bccacb9

**Comment by grahammendick** [comment]
I'll close [because it's working](https://github.com/grahammendick/navigation/issues/843#issuecomment-2486206528) but let me know how you get on

**Comment by salisuabubakar** [comment]
Hi, am still having the same issue. Am using expo sdk 52 and expo-video. Thanks

**Comment by grahammendick** [comment]
I asked you [to try the following code](https://github.com/grahammendick/navigation/issues/843#issuecomment-2486206528) in the fabric example and let me know if it works for you too, please?
```jsx
const [detent, setDetent] = useState('hidden');
useEffect(() => {
  setTimeout(() => {
    setDetent('expanded');
  }, 1000);
}, [])

<Sheet modal bottom={false} detent={detent} onChangeDetent={setDetent}>
  <ScrollView style={{flex: 1}}>
    <View style={{height: 1000, borderColor: 'orange', borderWidth: 5, backgroundColor: 'lightblue'}} />
  </ScrollView>
</Sheet>
```
