### ISSUE TITLE
Qn. mock stateNavigator

### ISSUE THREAD

**Issue by bsr203** [grahammendick/navigation#89]
Hi,

In my tests, I get this error

```
 TypeError: Cannot read property 'url' of undefined
      
      at NavigationLink.Object.<anonymous>.NavigationLink.getNextState (node_modules/navigation-react/lib/NavigationLink.js:29:69)
      at new NavigationLink (node_modules/navigation-react/lib/NavigationLink.js:18:27)
      at node_modules/react/lib/ReactCompositeComponent.js:294:18
      at measureLifeCyclePerf (node_modules/react/lib/ReactCompositeComponent.js:74:12)

```

adding this solves the problem `jest.mock('navigation-react');`

but, is there a better way to solve it during test setup.

for example, I used to set it on the context during the dom setup

```
router = {
  push: noop,
  createHref: (pathOrLoc, query) => `path:${JSON.stringify(pathOrLoc)}, query:${JSON.stringify(query)}`, // 'test href', // eslint-disable-line no-unused-vars
  isActive: (location, onlyActiveOnIndex) => true, // eslint-disable-line no-unused-vars
  replace: noop,
};
```

having some realistic url also helps identify them in test or snapshot.

do you have any mock handy, or there a better way. I could also pass an actual `stateNavigator` (with setting up all routes!!) if it is really needed.

**Comment by grahammendick** [comment]
You can pass a stateNavigator,  but you don't need to set up any routes. This will generate hyperlinks with empty hrefs which is what you're after, I think. 

You only need to pass routes if you're testing the hrefs.

Shorter answer than normal because I'm on a train. Let me know what you think.  If needed, I can write a fuller answer when I get back tonight.

**Comment by grahammendick** [comment]
What I mean is you should create a StateNavigator without any States:

    new StateNavigator([]);

**Comment by grahammendick** [comment]
I'm back home so it's time for a fuller answer.

In most tests, you don't worry about the value of the hrefs. For these, you can pass in a StateNavigator with an empty States array. This generates Hyperlinks with no href attributes:

    new StateNavigator([]); 

You said that 'realistic' hrefs in your snapshots helps to identify them. In that case, you can pass in States with just the key attribute populated. This generates href attributes, but they won't match the actual hrefs:

    new StateNavigator([{ key: 'people' }]); 

In the few tests left where you want to check the actual href, then you must pass in the actual StateNavigator.

**Comment by bsr203** [comment]
thanks a ton for all the answers. I just got a chance to check them.  I think `new StateNavigator([{ key: 'people' }]); 
` would be quite enough. thanks again.
